(()=>{'use strict';
const $=id=>document.getElementById(id),{esc,get,mutate,safeUrl,date}=WorkAPI;
let dash=null,loading=false,pendingLoad=false,mutating=false,cache=new Map(),classes=[],detailStudent='',filter='all';
const auth=()=>({teacherKey:sessionStorage.getItem('v55teacherKey')||''});
function status(s,bad=false){$('v55Status').textContent=s;$('v55Status').classList.toggle('v54-miss',bad)}
async function run(button,fn){if(mutating)return;mutating=true;button.disabled=true;try{await fn()}catch(e){status(e.message,true)}finally{mutating=false;button.disabled=false}}
function init(){const nav=$('proTeacherNav');if(!nav||$('proWorkPane'))return;
 const b=document.createElement('button');b.type='button';b.dataset.mode='work';b.innerHTML='<span>📥</span><span>งานและคะแนน</span>';nav.insertBefore(b,nav.lastElementChild);b.onclick=()=>{window.setTeacherMode('work');if(auth().teacherKey)loadClasses()};
 const pane=document.createElement('section');pane.id='proWorkPane';pane.className='pro-pane';pane.innerHTML=`
 <div class="v55-connect"><label>กุญแจครู <input id="v55Key" type="password" autocomplete="off" placeholder="จาก setupV55 ใน Apps Script"></label><button id="v55Connect" class="pro-btn primary">เชื่อมต่อ</button><button id="v55Logout" class="pro-btn secondary">ออกจากระบบงาน</button><small>กุญแจเก็บเฉพาะแท็บนี้ • ตั้งค่าตาม README-V55.txt</small></div><p id="v55Status" role="status" aria-live="polite">พร้อมเชื่อมต่อระบบงานและคะแนน V55</p>
 <div class="v54-grid"><article class="pro-card"><div class="pro-kicker">CLASSROOM</div><h2>ห้องเรียน</h2><label>เลือกห้อง<select id="v54Class" class="pro-input"><option value="">เลือกห้องเรียน</option></select></label><div class="v55-actions"><button id="v54NewClass" class="pro-btn secondary">＋ สร้างห้องเรียน</button><button id="v55Roster" class="pro-btn secondary">รายชื่อ / รหัสเข้าเรียน</button></div><div id="v54ClassInfo"></div></article>
 <article class="pro-card"><div class="pro-kicker">ASSIGNMENT</div><h2>สร้างงาน / ใบงาน</h2><form id="v55WorkForm"><label>ชื่องาน<input id="v54Title" class="pro-input" required maxlength="200" placeholder="ใบงานที่ 1 กฎของโอห์ม"></label><label>ชื่อใบงาน<input id="v55Worksheet" class="pro-input" placeholder="กรณีเป็นใบงาน"></label><label>คำชี้แจง<textarea id="v55Description" class="pro-input" rows="2"></textarea></label><div class="v54-row"><label>ประเภท<select id="v54Type" class="pro-input"><option value="submission">งานทั่วไป</option><option value="worksheet">ใบงาน</option><option value="text">ส่งข้อความ</option><option value="link">ส่งลิงก์</option><option value="file">ส่งรูป / ไฟล์ / PDF</option><option value="exam">ข้อสอบออนไลน์</option></select></label><label>คะแนนเต็ม<input id="v54Max" class="pro-input" type="number" value="10" min="0.01" step="any" required></label></div><label id="v55ExamLabel" hidden>รหัสข้อสอบ<input id="v54Exam" class="pro-input" placeholder="EX_..."></label><label>กำหนดส่ง (เวลาไทย)<input id="v54Due" class="pro-input" type="datetime-local"></label><button id="v54Create" class="pro-btn primary pro-full">เผยแพร่งาน</button></form></article>
 <article class="pro-card v54-wide"><div class="pro-card-head"><div><div class="pro-kicker">GRADEBOOK</div><h2>คะแนนและงานที่ขาด</h2></div><div class="v55-actions"><button id="v55Export" class="pro-btn secondary">ส่งออก CSV</button><button id="v54Refresh" class="pro-btn secondary">รีเฟรช</button></div></div><div id="v55Summary" class="v55-stats"></div><div class="v55-actions"><label>แสดง <select id="v55Filter"><option value="all">นักเรียนทั้งหมด</option><option value="missing">มีงานขาด</option><option value="pending">มีงานรอตรวจ</option></select></label><small>แตะชื่อนักเรียนหรือช่องงานเพื่อตรวจ • อัปเดตอัตโนมัติทุก 45 วินาทีเมื่อเปิดหน้านี้</small></div><div id="v54Grade">เลือกห้องเรียน</div><div id="v55Detail"></div></article></div><dialog id="v55Dialog"></dialog>`;
 $('proResultsPane').insertAdjacentElement('afterend',pane);$('v55Key').value=auth().teacherKey;
 $('v55Connect').onclick=()=>run($('v55Connect'),async()=>{sessionStorage.setItem('v55teacherKey',$('v55Key').value.trim());cache.clear();await loadClasses(true)});
 $('v55Logout').onclick=()=>{sessionStorage.removeItem('v55teacherKey');$('v55Key').value='';classes=[];cache.clear();dash=null;$('v54Class').innerHTML='<option value="">เลือกห้องเรียน</option>';clearDash();status('ออกจากระบบงานแล้ว')};
 $('v54NewClass').onclick=()=>rosterDialog(false);$('v55Roster').onclick=()=>rosterDialog(true);
 $('v54Class').onchange=()=>{detailStudent='';clearDash();loadDash()};$('v54Refresh').onclick=()=>loadDash(true);
 $('v55Filter').onchange=()=>{filter=$('v55Filter').value;renderGrade()};$('v55Export').onclick=exportCSV;
 $('v54Type').onchange=()=>{$('v55ExamLabel').hidden=$('v54Type').value!=='exam';$('v54Exam').required=$('v54Type').value==='exam'};
 $('v55WorkForm').onsubmit=e=>{e.preventDefault();run($('v54Create'),async()=>{const classId=$('v54Class').value;if(!classId)throw Error('เลือกห้องเรียนก่อน');await mutate({action:'createWork',...auth(),classId,title:$('v54Title').value.trim(),worksheetName:$('v55Worksheet').value.trim(),description:$('v55Description').value,type:$('v54Type').value,maxScore:Number($('v54Max').value),dueAt:$('v54Due').value?$('v54Due').value+':00+07:00':'',examId:$('v54Exam').value.trim().toUpperCase()});$('v55WorkForm').reset();$('v55ExamLabel').hidden=true;$('v54Exam').required=false;cache.delete(classId);status('เผยแพร่งานสำเร็จ');await loadDash(true)})};
 setInterval(()=>{if(!document.hidden&&document.body.dataset.proMode==='work'&&!mutating&&!loading&&!$('v55Dialog').open&&!detailStudent&&$('v54Class').value)loadDash(true)},45000);
 if(auth().teacherKey&&document.body.dataset.proMode==='work')loadClasses();
}
function clearDash(){dash=null;$('v54ClassInfo').innerHTML='';$('v54Grade').textContent='เลือกห้องเรียน';$('v55Summary').innerHTML='';$('v55Detail').innerHTML=''}
let classLoading=false;
async function loadClasses(force=false){if(classLoading)return;if(!auth().teacherKey)return status('ใส่กุญแจครูก่อนเชื่อมต่อ');classLoading=true;const requestedKey=auth().teacherKey;try{
 if(!classes.length||force){const r=await get('listClasses',auth());if(auth().teacherKey!==requestedKey)return;if(r.apiVersion!=='V55')throw Error('กรุณา Deploy Apps Script V55');classes=r.classes;}
 const old=$('v54Class').value||localStorage.v54class;$('v54Class').innerHTML='<option value="">เลือกห้องเรียน</option>'+classes.map(c=>`<option value="${esc(c.classId)}">${esc(c.className)} • ${esc(c.subject)}</option>`).join('');
 if(classes.some(c=>c.classId===old))$('v54Class').value=old;status('เชื่อมต่อแล้ว • '+classes.length+' ห้อง');if($('v54Class').value)await loadDash();
 }catch(e){status(e.message,true)}finally{classLoading=false}}
async function loadDash(force=false){const id=$('v54Class').value;if(!id)return;if(loading){pendingLoad=true;return}loading=true;const requestedKey=auth().teacherKey;$('v54Refresh').disabled=true;localStorage.v54class=id;
 try{let r=cache.get(id);if(force||!r||Date.now()-r.at>20000){const data=await get('getClassDashboard',{...auth(),classId:id});r={at:Date.now(),data};cache.set(id,r)}if($('v54Class').value!==id||auth().teacherKey!==requestedKey)return;dash=r.data;renderClass();renderGrade();if(detailStudent)renderDetail(detailStudent);status('อัปเดต '+new Date(r.at).toLocaleTimeString('th-TH'));}
 catch(e){status(e.message,true)}finally{loading=false;$('v54Refresh').disabled=false;if(pendingLoad){pendingLoad=false;loadDash(true)}}}
function studentLink(){const u=new URL('student-work.html',location.href);u.searchParams.set('class',dash.classInfo.classId);return u.href}
function renderClass(){const c=dash.classInfo,url=studentLink();$('v54ClassInfo').innerHTML=`<p><b>${esc(c.className)}</b><br>${esc(c.subject)} ${esc(c.code)}</p><div class="v55-actions"><a class="pro-btn secondary" href="${esc(url)}" target="_blank" rel="noopener">เปิดหน้านักเรียน ↗</a><button id="v55Copy" class="pro-btn secondary">คัดลอกลิงก์</button><button id="v55QR" class="pro-btn secondary">QR ห้องเรียน</button></div>`;$('v55Copy').onclick=async()=>{try{await navigator.clipboard.writeText(url);status('คัดลอกลิงก์แล้ว')}catch{prompt('คัดลอกลิงก์ห้องเรียน',url)}};$('v55QR').onclick=()=>{const d=$('v55Dialog');d.innerHTML=`<h2>${esc(c.className)}</h2><div id="v55QRImage"></div><p>สแกนเพื่อเปิด “งานของฉัน”</p><p class="v55-link">${esc(url)}</p><p>ใช้รหัสนักเรียนและรหัสเข้าดูงานที่ครูแจก</p><button class="pro-btn secondary" id="v55Close">ปิด</button>`;new QRCode($('v55QRImage'),{text:url,width:240,height:240,correctLevel:QRCode.CorrectLevel.M});$('v55Close').onclick=()=>d.close();d.showModal()};}
function renderGrade(){if(!dash)return;const students=dash.students,missing=students.reduce((n,s)=>n+s.missing.length,0),pending=students.reduce((n,s)=>n+s.pending,0),avg=students.length?students.reduce((n,s)=>n+s.percent,0)/students.length:0;
 $('v55Summary').innerHTML=[['นักเรียน',students.length],['งานทั้งหมด',dash.works.length],['รายการงานขาด',missing],['รอตรวจ',pending],['เฉลี่ยคะแนน',avg.toFixed(1)+'%']].map(([k,v])=>`<div><small>${k}</small><strong>${v}</strong></div>`).join('');
 const visible=students.filter(s=>filter==='all'||(filter==='missing'?s.missing.length:s.pending));
 $('v54Grade').innerHTML='<div class="v54-tablewrap"><table class="v54-table"><thead><tr><th>นักเรียน</th>'+dash.works.map(w=>`<th>${esc(w.title)}<small>${w.maxScore} คะแนน</small></th>`).join('')+'<th>รวม</th><th>%</th><th>งานขาด</th></tr></thead><tbody>'+visible.map(s=>`<tr><td><button class="v55-name" data-student="${esc(s.studentId)}">${esc(s.studentName)}</button><small>${esc(s.studentId)}</small></td>`+s.items.map(i=>`<td class="${i.status==='ขาด'?'v54-miss':''}"><button class="v55-cell" data-student="${esc(s.studentId)}" data-work="${esc(i.workId)}">${i.score==null?'—':i.score} / ${i.max}<small>${esc(i.status)}${i.late?' • ส่งช้า':''}</small></button></td>`).join('')+`<td><b>${s.total} / ${s.max}</b></td><td>${s.percent}%</td><td>${s.missing.length}</td></tr>`).join('')+'</tbody></table></div>'+(visible.length?'':'<p>ไม่มีนักเรียนในรายการนี้</p>');
 $('v54Grade').querySelectorAll('[data-student]').forEach(b=>b.onclick=()=>{detailStudent=b.dataset.student;renderDetail(detailStudent,b.dataset.work);$('v55Detail').scrollIntoView({behavior:'smooth',block:'start'})});
}
function renderDetail(id,workId){if(!dash)return;const s=dash.students.find(s=>s.studentId===id);if(!s)return;const subMap=Object.fromEntries(dash.submissions.filter(x=>String(x.studentId)===id).map(x=>[x.workId,x]));
 $('v55Detail').innerHTML=`<div class="v55-detail-head"><h3>${esc(s.studentName)} • ${s.total}/${s.max} (${s.percent}%)</h3><button id="v55DetailClose" class="pro-btn secondary">ปิดรายละเอียด</button></div><p>ขาด: ${s.missing.length?esc(s.missing.join(', ')):'ส่งครบแล้ว'}</p>`+dash.works.filter(w=>!workId||w.workId===workId).map(w=>{const sub=subMap[w.workId],i=s.items.find(i=>i.workId===w.workId);let body='';
 if(w.type==='exam')body=`<p>คะแนนจากข้อสอบ ${esc(w.examId)} • ${esc(i.status)} • ${i.score??'—'} / ${w.maxScore}</p><small>ใช้ครั้งที่ส่งล่าสุด และปรับตามคะแนนเต็มของงาน${i.status==='รอตรวจข้อเขียน'?' • คะแนนยังไม่สมบูรณ์จนกว่าครูตรวจข้อเขียน':''}</small>`;
 else if(!sub)body='<p class="v54-miss">ยังไม่ส่งงาน</p>';
 else body=`<p>ส่งเมื่อ ${date(sub.submittedAt)}${i.late?' • ส่งช้า':''}</p><div class="v55-answer">${esc(sub.answerText)}</div>${safeUrl(sub.answerUrl)?`<p><a href="${esc(safeUrl(sub.answerUrl))}" target="_blank" rel="noopener noreferrer">เปิดลิงก์งาน ↗</a></p>`:''}<div class="v55-files">${(sub.attachments||[]).map(f=>safeUrl(f.url)?`<a href="${esc(safeUrl(f.url))}" target="_blank" rel="noopener noreferrer">📎 ${esc(f.name)} ↗</a>`:'').join('')}</div><small>ไฟล์ Drive ต้องเปิดด้วยบัญชีครูที่ Deploy ระบบ</small><form class="v55-gradeform" data-work="${esc(w.workId)}"><label>คะแนน / ${w.maxScore}<input name="score" type="number" min="0" max="${w.maxScore}" step="any" value="${sub.score===''?'':sub.score}" required></label><label>ความคิดเห็น<textarea name="feedback" rows="2">${esc(sub.feedback)}</textarea></label><button class="pro-btn primary">บันทึกคะแนน</button></form>`;
 return `<section class="v55-review"><h3>${esc(w.title)}</h3>${body}</section>`;}).join('');
 $('v55DetailClose').onclick=()=>{detailStudent='';$('v55Detail').innerHTML=''};
 $('v55Detail').querySelectorAll('form').forEach(f=>f.onsubmit=e=>{e.preventDefault();const sub=subMap[f.dataset.work];run(f.querySelector('button'),async()=>{await mutate({action:'saveWorkGrade',...auth(),classId:dash.classInfo.classId,workId:f.dataset.work,studentId:id,score:Number(f.elements.score.value),feedback:f.elements.feedback.value,revision:sub.revision||0});status('บันทึกคะแนนสำเร็จ');await loadDash(true)})});
}
function rosterDialog(edit){if(!auth().teacherKey)return status('กรุณาเชื่อมต่อด้วยกุญแจครูก่อน',true);if(edit&&!dash)return status('เลือกห้องก่อน',true);const d=$('v55Dialog'),roster=edit?dash.roster:[];
 d.innerHTML=`<h2>${edit?'รายชื่อและรหัสเข้าดูงาน':'สร้างห้องเรียน'}</h2><form id="v55RosterForm">${edit?'':`<label>ชื่อห้อง / กลุ่ม<input name="className" required placeholder="ปวช.1 ชฟ.1/1 กลุ่ม 1"></label><label>รายวิชา<input name="subject"></label><label>รหัสวิชา<input name="code"></label>`}<label>รายชื่อนักเรียน (หนึ่งคนต่อบรรทัด: รหัส,ชื่อ–สกุล)<textarea name="roster" rows="9" required placeholder="001,นายสมชาย ใจดี\n002,นางสาวสมใจ ใจดี">${esc(roster.map(s=>s.studentId+','+s.studentName).join('\n'))}</textarea></label><p>คงรหัสเดิมเมื่อแก้ชื่อ • เพิ่มรายชื่อได้ • ยังไม่ลบรายชื่อเดิม</p><p id="v55RosterError" role="alert"></p><div class="v55-actions"><button class="pro-btn primary">บันทึก</button><button type="button" id="v55Close" class="pro-btn secondary">ปิด</button></div></form>${edit?'<h3>รหัสส่วนตัว — แจกเฉพาะเจ้าของรหัส</h3><div class="v54-tablewrap"><table class="v54-table"><tr><th>รหัสนักเรียน</th><th>ชื่อ</th><th>รหัสเข้าดูงาน</th></tr>'+roster.map(s=>`<tr><td>${esc(s.studentId)}</td><td>${esc(s.studentName)}</td><td>${esc(s.accessCode||'ต้องรัน setupV55')}</td></tr>`).join('')+'</table></div>':''}`;
 $('v55Close').onclick=()=>d.close();$('v55RosterForm').onsubmit=async e=>{e.preventDefault();if(mutating)return;const f=e.target,b=f.querySelector('button');mutating=true;b.disabled=true;try{
 const students=f.elements.roster.value.split(/\n/).filter(x=>x.trim()).map(x=>{const at=x.indexOf(',');if(at<1)throw Error('ใช้รูปแบบ รหัส,ชื่อ–สกุล ทุกบรรทัด');return {studentId:x.slice(0,at).trim(),studentName:x.slice(at+1).trim()}});
 const r=await mutate({action:edit?'updateRoster':'createClass',...auth(),classId:edit?dash.classInfo.classId:undefined,className:f.elements.className?.value,subject:f.elements.subject?.value,code:f.elements.code?.value,students});if(r.classId)localStorage.v54class=r.classId;cache.clear();classes=[];d.close();await loadClasses(true);if(r.classId){$('v54Class').value=r.classId;await loadDash(true)}status('บันทึกรายชื่อแล้ว');
 }catch(e){$('v55RosterError').textContent=e.message}finally{mutating=false;b.disabled=false}};d.showModal();
}
function exportCSV(){if(!dash)return;const rows=[['รหัส','ชื่อ',...dash.works.map(w=>w.title),'รวม','เต็ม','%','งานขาด'],...dash.students.map(s=>[s.studentId,s.studentName,...s.items.map(i=>i.score??''),s.total,s.max,s.percent,s.missing.join('; ')])];const csv='\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='gradebook-'+dash.classInfo.classId+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
