(()=>{'use strict';
const API='https://script.google.com/macros/s/AKfycbxunyrg12A_Fv4fM-6GZZ4rVXz07-EN_rRGsTbBQZmsLcjFnLeLgNX3t-vyHH8d7Xfqgw/exec';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function jsonp(action,params={}){return new Promise((res,rej)=>{const cb='v54_'+Date.now()+'_'+Math.random().toString(36).slice(2),sc=document.createElement('script');window[cb]=x=>{delete window[cb];sc.remove();res(x)};sc.onerror=()=>{delete window[cb];sc.remove();rej(new Error('network'))};sc.src=API+'?'+new URLSearchParams({action,...params,callback:cb});document.head.appendChild(sc)})}
async function post(body){await fetch(API,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)});}
function init(){const nav=document.getElementById('proTeacherNav');if(!nav||$('proWorkPane'))return;const b=document.createElement('button');b.type='button';b.dataset.mode='work';b.innerHTML='<span style="font-size:22px">📥</span><span>งานและคะแนน</span>';nav.insertBefore(b,nav.lastElementChild);b.onclick=()=>show();
 const pane=document.createElement('section');pane.id='proWorkPane';pane.className='pro-pane';pane.innerHTML=`<div class="v54-grid"><article class="pro-card"><div class="pro-kicker">CLASSROOM</div><h2>ห้องเรียน</h2><select id="v54Class" class="pro-input"></select><button id="v54NewClass" class="pro-btn secondary">＋ สร้างห้องเรียน</button><div id="v54ClassInfo"></div></article><article class="pro-card"><div class="pro-kicker">ASSIGNMENT</div><h2>สร้างงาน / ใบงาน</h2><input id="v54Title" class="pro-input" placeholder="เช่น ใบงานที่ 1 เรื่อง กฎของโอห์ม"><div class="v54-row"><select id="v54Type" class="pro-input"><option value="submission">ส่งงาน</option><option value="exam">ข้อสอบออนไลน์</option></select><input id="v54Max" class="pro-input" type="number" value="10" min="1" placeholder="คะแนนเต็ม"></div><input id="v54Exam" class="pro-input" placeholder="รหัสข้อสอบ EX_... (กรณีข้อสอบ)"><input id="v54Due" class="pro-input" type="datetime-local"><button id="v54Create" class="pro-btn primary pro-full">เผยแพร่งาน</button></article><article class="pro-card v54-wide"><div class="pro-card-head"><div><div class="pro-kicker">GRADEBOOK</div><h2>สมุดคะแนนและงานที่ขาด</h2></div><button id="v54Refresh" class="pro-btn secondary">รีเฟรช</button></div><div id="v54Grade">เลือกห้องเรียน</div></article></div>`;document.getElementById('proResultsPane').insertAdjacentElement('afterend',pane);
 $('v54NewClass').onclick=newClass;$('v54Create').onclick=createWork;$('v54Refresh').onclick=loadDash;$('v54Class').onchange=loadDash;loadClasses();}
function show(){document.body.dataset.proMode='work';document.querySelectorAll('#proTeacherNav button').forEach(x=>x.classList.toggle('active',x.dataset.mode==='work'));$('proTitle').textContent='งานและคะแนน';$('proSubtitle').textContent='สร้างงาน ดูงานที่ขาด ตรวจและรวมคะแนนกับข้อสอบออนไลน์';loadClasses();}
async function loadClasses(){const r=await jsonp('listClasses').catch(()=>({classes:[]}));const sel=$('v54Class');if(!sel)return;sel.innerHTML='<option value="">เลือกห้องเรียน</option>'+((r.classes||[]).map(c=>`<option value="${esc(c.classId)}">${esc(c.className)} • ${esc(c.subject)}</option>`).join(''));if(localStorage.v54class&&[...sel.options].some(o=>o.value===localStorage.v54class))sel.value=localStorage.v54class;if(sel.value)loadDash();}
async function newClass(){const name=prompt('ชื่อห้อง เช่น ปวช.1 ชฟ.1/1 กลุ่ม 1');if(!name)return;const subject=prompt('ชื่อวิชา','')||'',code=prompt('รหัสวิชา','')||'',raw=prompt('รายชื่อนักเรียน: 1 บรรทัดต่อคน รูปแบบ รหัส,ชื่อ-สกุล','')||'';const students=raw.split(/\n/).map(x=>x.trim()).filter(Boolean).map((x,i)=>{const a=x.split(',');return {studentId:(a.shift()||String(i+1)).trim(),studentName:a.join(',').trim()||x}});await post({action:'createClass',className:name,subject,code,students});setTimeout(loadClasses,900);}
async function createWork(){const classId=$('v54Class').value,title=$('v54Title').value.trim();if(!classId||!title)return alert('เลือกห้องและใส่ชื่องานก่อน');await post({action:'createWork',classId,title,type:$('v54Type').value,maxScore:+$('v54Max').value||10,dueAt:$('v54Due').value,examId:$('v54Exam').value.trim()});$('v54Title').value='';setTimeout(loadDash,900);}
async function loadDash(){const id=$('v54Class')?.value;if(!id)return;localStorage.v54class=id;const r=await jsonp('getClassDashboard',{classId:id}).catch(()=>null);if(!r||!r.ok)return $('v54Grade').textContent='โหลดข้อมูลไม่สำเร็จ';$('v54ClassInfo').innerHTML=`<p><b>${esc(r.classInfo.className)}</b><br>${esc(r.classInfo.subject)} ${esc(r.classInfo.code)}</p><p><a href="./student-work.html?class=${encodeURIComponent(id)}" target="_blank">เปิดลิงก์สำหรับนักเรียน ↗</a></p>`;let h='<div class="v54-tablewrap"><table class="v54-table"><thead><tr><th>รหัส</th><th>ชื่อ–สกุล</th>'+r.works.map(w=>`<th>${esc(w.title)}<small>${w.maxScore} คะแนน</small></th>`).join('')+'<th>รวม</th><th>งานที่ขาด</th></tr></thead><tbody>';for(const s of r.students){h+=`<tr><td>${esc(s.studentId)}</td><td>${esc(s.studentName)}</td>`+s.items.map(i=>`<td class="${i.status==='ขาด'?'v54-miss':''}">${i.score==null?'—':i.score} / ${i.max}<small>${esc(i.status)}</small></td>`).join('')+`<td><b>${s.total} / ${s.max}</b></td><td class="v54-miss">${s.missing.length?esc(s.missing.join(', ')):'ครบ'}</td></tr>`}h+='</tbody></table></div>';$('v54Grade').innerHTML=h;}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,80));else setTimeout(init,80);
})();
