const SS_ID='PUT_YOUR_GOOGLE_SHEET_ID_HERE';
function doGet(){return out({ok:true,message:'Exam API ready'})}
function doPost(e){try{const b=JSON.parse((e.postData&&e.postData.contents)||'{}'),map={createExam,getExam,startAttempt,submitAttempt,logEvent};return out(map[b.action]?map[b.action](b):{ok:false,error:'Unknown action'})}catch(err){return out({ok:false,error:String(err.message||err)})}}
function out(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function book(){return SpreadsheetApp.openById(SS_ID)}
function sh(name,head){let s=book().getSheetByName(name);if(!s){s=book().insertSheet(name);s.appendRow(head)}return s}
function uid(p){return p+'_'+Utilities.getUuid().replace(/-/g,'').slice(0,12).toUpperCase()}
function withLock(fn){const l=LockService.getScriptLock();l.waitLock(20000);try{return fn()}finally{l.releaseLock()}}
function exams(){return sh('Exams',['examId','title','subject','code','level','year','topic','duration','maxLeave','showScore','oneAttempt','questionsJson','active','createdAt'])}
function attempts(){return sh('Attempts',['attemptId','examId','studentId','studentName','status','startAt','endAt','score','total','leaves','reason','answersJson'])}
function findExam(id){const v=exams().getDataRange().getValues();for(let r=1;r<v.length;r++)if(String(v[r][0])===String(id))return{examId:v[r][0],title:v[r][1],subject:v[r][2],code:v[r][3],level:v[r][4],year:v[r][5],topic:v[r][6],duration:+v[r][7],maxLeave:+v[r][8],showScore:String(v[r][9]).toLowerCase()==='true',oneAttempt:String(v[r][10]).toLowerCase()==='true',questions:JSON.parse(v[r][11]||'[]'),active:String(v[r][12]).toLowerCase()!=='false'};return null}
function findAttempt(id){const s=attempts(),v=s.getDataRange().getValues();for(let r=1;r<v.length;r++)if(String(v[r][0])===String(id))return{s,row:r+1,d:v[r]};return null}
function createExam(b){return withLock(()=>{if(!b.title||!Array.isArray(b.questions)||!b.questions.length)return{ok:false,error:'ข้อมูลข้อสอบไม่ครบ'};for(const q of b.questions)if(!q.q||!q.choices||!['ก','ข','ค','ง'].includes(q.answer))return{ok:false,error:'พบข้อสอบหรือเฉลยไม่สมบูรณ์'};const id=uid('EX');exams().appendRow([id,b.title,b.subject||'',b.code||'',b.level||'',b.year||'',b.topic||'',+b.duration||50,+b.maxLeave||3,!!b.showScore,!!b.oneAttempt,JSON.stringify(b.questions),true,new Date()]);return{ok:true,examId:id}})}
function getExam(b){const e=findExam(b.examId);if(!e||!e.active)return{ok:false,error:'ไม่พบข้อสอบหรือข้อสอบถูกปิดแล้ว'};return{ok:true,exam:{examId:e.examId,title:e.title,duration:e.duration,maxLeave:e.maxLeave,questions:e.questions.map(q=>({q:q.q,choices:q.choices}))}}}
function startAttempt(b){return withLock(()=>{const e=findExam(b.examId);if(!e||!e.active)return{ok:false,error:'ข้อสอบไม่เปิดใช้งาน'};if(!b.studentId||!b.studentName)return{ok:false,error:'กรอกข้อมูลนักเรียนไม่ครบ'};const s=attempts(),v=s.getDataRange().getValues();if(e.oneAttempt)for(let r=1;r<v.length;r++)if(String(v[r][1])===String(b.examId)&&String(v[r][2])===String(b.studentId)&&['STARTED','SUBMITTED'].includes(String(v[r][4])))return{ok:false,error:'รหัสนักเรียนนี้เข้าสอบชุดนี้แล้ว'};const aid=uid('AT'),start=new Date(),end=new Date(start.getTime()+e.duration*60000);s.appendRow([aid,b.examId,String(b.studentId),String(b.studentName),'STARTED',start,'','','','','','']);return{ok:true,attemptId:aid,startMs:start.getTime(),endMs:end.getTime()}})}
function submitAttempt(b){return withLock(()=>{const a=findAttempt(b.attemptId);if(!a)return{ok:false,error:'ไม่พบเซสชันการสอบ'};if(String(a.d[4])==='SUBMITTED')return{ok:false,error:'ข้อสอบนี้ถูกส่งแล้ว'};if(String(a.d[1])!==String(b.examId))return{ok:false,error:'รหัสข้อสอบไม่ตรง'};const e=findExam(b.examId);if(!e)return{ok:false,error:'ไม่พบข้อสอบ'};let score=0,ans=b.answers||{};e.questions.forEach((q,i)=>{if(String(ans[i]||'')===String(q.answer))score++});a.s.getRange(a.row,5,1,8).setValues([['SUBMITTED',a.d[5],new Date(),score,e.questions.length,+b.leaveCount||0,String(b.reason||''),JSON.stringify(ans)]]);return{ok:true,score,total:e.questions.length,showScore:e.showScore}})}
function logEvent(b){const a=findAttempt(b.attemptId);if(!a)return{ok:false,error:'ไม่พบเซสชัน'};sh('Events',['timestamp','examId','attemptId','studentId','event','leaveCount']).appendRow([new Date(),b.examId||'',b.attemptId||'',a.d[2]||'',b.event||'',+b.leaveCount||0]);return{ok:true}}
