(function(){
 const $=id=>document.getElementById(id),letters=['ก','ข','ค','ง'];let items=[];try{items=JSON.parse(localStorage.getItem('vocManualQuestions')||'[]')}catch{}let editing=-1,parsed=[];
 const box=document.createElement('section');box.className='manual-builder';box.innerHTML='<h3>✎ เพิ่มโจทย์และช้อยเอง</h3><p>โจทย์ที่เพิ่มจะต่อท้ายข้อที่ระบบสร้าง และรวมในคะแนนเต็มอัตโนมัติ</p><div class="manual-form"><label>หัวข้อ<input id="mqTopic" placeholder="เช่น กฎของโอห์ม"></label><label>คำถาม<textarea id="mqQuestion" placeholder="พิมพ์โจทย์ที่ต้องการ"></textarea></label><div id="mqChoices"></div><label>คำตอบที่ถูก<select id="mqCorrect"><option value="0">ก</option><option value="1">ข</option><option value="2">ค</option><option value="3">ง</option></select></label><div class="manual-actions"><button type="button" class="mini-btn" id="mqSave">เพิ่มโจทย์</button><button type="button" class="mini-btn secondary" id="mqCancel" hidden>ยกเลิกแก้ไข</button></div></div><details class="ai-import"><summary>✦ นำเข้าข้อสอบจาก AI</summary><p>กดเปิด ChatGPT เพื่อรับคำสั่ง แล้วคัดลอกคำตอบทั้งหมดมาวางด้านล่าง</p><div class="manual-actions"><button type="button" class="mini-btn secondary" id="aiPromptBtn">เปิด ChatGPT พร้อมคำสั่ง</button></div><label>ข้อความข้อสอบจาก AI<textarea id="aiRaw" placeholder="วางข้อสอบ ก ข ค ง หรือถาม–ตอบที่ AI สร้างไว้"></textarea></label><div class="manual-actions"><button type="button" class="mini-btn" id="aiParseBtn">วิเคราะห์ข้อความ</button><button type="button" class="mini-btn" id="aiImportBtn" hidden>นำเข้าข้อที่เลือก</button></div><div class="ai-parsed" id="aiParsed"></div></details><div class="manual-list" id="mqList"></div>';
 $('generateBtn').before(box);$('mqChoices').innerHTML=letters.map((l,i)=>'<label class="manual-choice"><b>'+l+'</b><input id="mqChoice'+i+'" placeholder="ตัวเลือก '+l+'"></label>').join('');
 function persist(){localStorage.setItem('vocManualQuestions',JSON.stringify(items));draw();document.dispatchEvent(new Event('manual-updated'));window.render()}
 function clear(){editing=-1;$('mqTopic').value='';$('mqQuestion').value='';letters.forEach((_,i)=>$('mqChoice'+i).value='');$('mqCorrect').value='0';$('mqSave').textContent='เพิ่มโจทย์';$('mqCancel').hidden=true}
 function draw(){$('mqList').innerHTML=items.map((x,i)=>'<div class="manual-card"><b>ข้อเพิ่ม '+(i+1)+' • '+escapeHtml(x.topic||'ไม่ระบุหัวข้อ')+' <em>'+(x.kind==='qna'?'ถาม–ตอบ':'ปรนัย')+'</em></b><span>'+escapeHtml(x.question)+'</span><div class="card-actions">'+(x.kind==='qna'?'':'<button type="button" class="edit" data-edit="'+i+'">แก้ไข</button>')+'<button type="button" class="remove" data-remove="'+i+'">ลบ</button></div></div>').join('');$('mqList').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(+b.dataset.edit));$('mqList').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{items.splice(+b.dataset.remove,1);persist()})}
 function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function edit(i){const x=items[i];editing=i;$('mqTopic').value=x.topic||'';$('mqQuestion').value=x.question;letters.forEach((_,n)=>$('mqChoice'+n).value=x.choices[n]);$('mqCorrect').value=String(x.correct);$('mqSave').textContent='บันทึกการแก้ไข';$('mqCancel').hidden=false;box.scrollIntoView({behavior:'smooth',block:'nearest'})}
 $('mqSave').onclick=()=>{const question=$('mqQuestion').value.trim(),choices=letters.map((_,i)=>$('mqChoice'+i).value.trim());if(!question||choices.some(x=>!x)){alert('กรุณาใส่คำถามและตัวเลือก ก ข ค ง ให้ครบ');return}const item={topic:$('mqTopic').value.trim(),question,choices,correct:+$('mqCorrect').value};if(editing>=0)items[editing]=item;else{items.push(item);const count=$('count'),current=+count.value||1;if(current<60){count.value=current+1;count.dispatchEvent(new Event('input',{bubbles:true}))}}clear();persist()};$('mqCancel').onclick=clear;
 function stripNumber(text){return String(text||'').replace(/^\s*(?:ข้อ\s*)?\d+\s*[.)-]\s*/,'').trim()}
 function parseBlock(block){const lines=String(block||'').replace(/\r/g,'').split('\n').map(x=>x.trim()).filter(Boolean);if(!lines.length)return null;let answer='',answerLetter=-1;const kept=[];for(const line of lines){const hit=line.match(/^(?:เฉลย|คำตอบ)\s*[:：-]?\s*(.*)$/i);if(hit){answer=hit[1].trim();const letter=answer.match(/^([กขคงA-Da-d])/);if(letter){const n='กขคง'.indexOf(letter[1].toUpperCase());answerLetter=n>=0?n:'ABCD'.indexOf(letter[1].toUpperCase())}continue}kept.push(line)}const optionAt=[];kept.forEach((line,i)=>{const m=line.match(/^([กขคงA-Da-d])\s*[.)]\s*(.+)$/);if(m)optionAt.push({i,letter:m[1],text:m[2].trim()})});if(optionAt.length>=4){const first=optionAt[0].i,opts=optionAt.slice(0,4).map(x=>x.text);let correct=answerLetter;if(correct<0&&answer){const found=opts.findIndex(x=>x===answer||x.includes(answer)||answer.includes(x));correct=found>=0?found:0}return{kind:'mcq',question:stripNumber(kept.slice(0,first).join(' ')),choices:opts,correct:correct>=0&&correct<4?correct:0,answer:answer||'ไม่ระบุเฉลย'}}const question=stripNumber(kept.join(' '));return question?{kind:'qna',question,answer:answer||'ไม่ระบุแนวคำตอบ'}:null}
 function parseAi(text){const blocks=String(text||'').replace(/\r/g,'').split(/(?=^\s*(?:ข้อ\s*)?\d+\s*[.)-]\s*)/m).map(x=>x.trim()).filter(Boolean);return (blocks.length?blocks:[text]).map(parseBlock).filter(x=>x&&x.question.length>3)}
 function drawParsed(){const el=$('aiParsed');el.innerHTML=parsed.map((x,i)=>'<label class="ai-item"><input type="checkbox" data-ai-item="'+i+'" checked><div><b>ข้อ '+(i+1)+' • '+(x.kind==='mcq'?'ปรนัย ก ข ค ง':'ถาม–ตอบ')+'</b><span>'+escapeHtml(x.question)+'</span></div></label>').join('');$('aiImportBtn').hidden=!parsed.length}
 $('aiParseBtn').onclick=()=>{parsed=parseAi($('aiRaw').value);drawParsed();if(!parsed.length)alert('ยังแยกข้อสอบไม่ได้ กรุณาให้ AI จัดรูปแบบโดยขึ้นต้นแต่ละข้อด้วย 1. หรือ ข้อ 1')}
 $('aiImportBtn').onclick=()=>{const selected=[...document.querySelectorAll('[data-ai-item]:checked')].map(x=>parsed[+x.dataset.aiItem]).filter(Boolean);if(!selected.length){alert('กรุณาเลือกข้อที่ต้องการนำเข้า');return}const topic=$('mqTopic').value.trim()||$('topic').value.trim();selected.forEach(x=>items.push(x.kind==='mcq'?{topic,question:x.question,choices:x.choices,correct:x.correct}:{topic,kind:'qna',question:x.question,answer:x.answer}));const count=$('count');if((+count.value||1)<items.length){count.value=Math.min(60,items.length);count.dispatchEvent(new Event('input',{bubbles:true}))}$('aiRaw').value='';parsed=[];drawParsed();persist()}
 $('aiPromptBtn').onclick=()=>{const topic=$('mqTopic').value.trim()||$('topic').value.trim(),count=Math.max(1,Math.min(60,+$('count').value||10)),kind=$('type').value.includes('ปรนัย')?'ปรนัย 4 ตัวเลือก ก ข ค ง':'ถาม–ตอบ';const prompt='สร้างข้อสอบเรื่อง “'+topic+'” จำนวน '+count+' ข้อ แบบ'+kind+' สำหรับผู้เรียนอาชีวศึกษา ใช้ภาษาไทยกระชับและถูกต้อง\n\n'+(kind.startsWith('ปรนัย')?'จัดรูปแบบทุกข้อดังนี้:\n1. คำถาม\nก. ตัวเลือก\nข. ตัวเลือก\nค. ตัวเลือก\nง. ตัวเลือก\nเฉลย: ก':'จัดรูปแบบทุกข้อดังนี้:\n1. คำถาม\nคำตอบ: แนวคำตอบสั้น ๆ')+'\n\nห้ามมีคำอธิบายนอกเหนือจากข้อสอบ';navigator.clipboard?.writeText(prompt).catch(()=>{});window.open('https://chatgpt.com/?q='+encodeURIComponent(prompt),'_blank','noopener')};
 window.worksheetManual={items:()=>items.map(x=>({...x,choices:[...x.choices]}))};draw();window.render();
})();
