(function(){
 const $=id=>document.getElementById(id),letters=['ก','ข','ค','ง'];let items=[];try{items=JSON.parse(localStorage.getItem('vocManualQuestions')||'[]')}catch{}let editing=-1;
 const box=document.createElement('section');box.className='manual-builder';box.innerHTML='<h3>✎ เพิ่มโจทย์และช้อยเอง</h3><p>โจทย์ที่เพิ่มจะต่อท้ายข้อที่ระบบสร้าง และรวมในคะแนนเต็มอัตโนมัติ</p><div class="manual-form"><label>หัวข้อ<input id="mqTopic" placeholder="เช่น กฎของโอห์ม"></label><label>คำถาม<textarea id="mqQuestion" placeholder="พิมพ์โจทย์ที่ต้องการ"></textarea></label><div id="mqChoices"></div><label>คำตอบที่ถูก<select id="mqCorrect"><option value="0">ก</option><option value="1">ข</option><option value="2">ค</option><option value="3">ง</option></select></label><div class="manual-actions"><button type="button" class="mini-btn" id="mqSave">เพิ่มโจทย์</button><button type="button" class="mini-btn secondary" id="mqCancel" hidden>ยกเลิกแก้ไข</button></div></div><div class="manual-list" id="mqList"></div>';
 $('generateBtn').before(box);$('mqChoices').innerHTML=letters.map((l,i)=>'<label class="manual-choice"><b>'+l+'</b><input id="mqChoice'+i+'" placeholder="ตัวเลือก '+l+'"></label>').join('');
 function persist(){localStorage.setItem('vocManualQuestions',JSON.stringify(items));draw();window.render()}
 function clear(){editing=-1;$('mqTopic').value='';$('mqQuestion').value='';letters.forEach((_,i)=>$('mqChoice'+i).value='');$('mqCorrect').value='0';$('mqSave').textContent='เพิ่มโจทย์';$('mqCancel').hidden=true}
 function draw(){$('mqList').innerHTML=items.map((x,i)=>'<div class="manual-card"><b>ข้อเพิ่ม '+(i+1)+' • '+escapeHtml(x.topic||'ไม่ระบุหัวข้อ')+'</b><span>'+escapeHtml(x.question)+'</span><div class="card-actions"><button type="button" class="edit" data-edit="'+i+'">แก้ไข</button><button type="button" class="remove" data-remove="'+i+'">ลบ</button></div></div>').join('');$('mqList').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(+b.dataset.edit));$('mqList').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{items.splice(+b.dataset.remove,1);persist()})}
 function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function edit(i){const x=items[i];editing=i;$('mqTopic').value=x.topic||'';$('mqQuestion').value=x.question;letters.forEach((_,n)=>$('mqChoice'+n).value=x.choices[n]);$('mqCorrect').value=String(x.correct);$('mqSave').textContent='บันทึกการแก้ไข';$('mqCancel').hidden=false;box.scrollIntoView({behavior:'smooth',block:'nearest'})}
 $('mqSave').onclick=()=>{const question=$('mqQuestion').value.trim(),choices=letters.map((_,i)=>$('mqChoice'+i).value.trim());if(!question||choices.some(x=>!x)){alert('กรุณาใส่คำถามและตัวเลือก ก ข ค ง ให้ครบ');return}const item={topic:$('mqTopic').value.trim(),question,choices,correct:+$('mqCorrect').value};if(editing>=0)items[editing]=item;else{items.push(item);const count=$('count'),current=+count.value||1;if(current<60){count.value=current+1;count.dispatchEvent(new Event('input',{bubbles:true}))}}clear();persist()};$('mqCancel').onclick=clear;
 window.worksheetManual={items:()=>items.map(x=>({...x,choices:[...x.choices]}))};draw();window.render();
})();
