(function(){
const $=id=>document.getElementById(id),previousRender=window.render,letters=['ก','ข','ค','ง'];
const banks={ohm:[
{l:'remember',q:'ข้อใดกล่าวถึงกฎของโอห์มได้ถูกต้อง',c:['กระแสไฟฟ้าแปรผันตรงกับแรงดัน เมื่อความต้านทานคงที่','กระแสไฟฟ้าแปรผกผันกับแรงดันทุกกรณี','ความต้านทานมีค่าเท่ากับกำลังไฟฟ้าเสมอ','แรงดันไฟฟ้าไม่สัมพันธ์กับกระแสไฟฟ้า'],a:'กระแสไฟฟ้าแปรผันตรงกับแรงดัน เมื่อความต้านทานคงที่'},
{l:'remember',q:'สมการใดแสดงความสัมพันธ์ตามกฎของโอห์ม',c:['V = IR','V = I/R','I = VR','R = VI'],a:'V = IR'},
{l:'apply',q:'ถ้าต้องการหากระแสไฟฟ้าจากค่าแรงดันและความต้านทาน ควรใช้สมการใด',c:['I = V/R','I = VR','I = R/V','I = V + R'],a:'I = V/R'},
{l:'analyze',q:'วงจรมีแรงดันคงที่ หากความต้านทานเพิ่มขึ้นสองเท่า กระแสไฟฟ้าจะเปลี่ยนอย่างไร',c:['ลดลงเหลือครึ่งหนึ่ง','เพิ่มขึ้นสองเท่า','มีค่าเท่าเดิม','เพิ่มขึ้นสี่เท่า'],a:'ลดลงเหลือครึ่งหนึ่ง'},
{l:'apply',q:'การวัดกระแสไฟฟ้าด้วยมัลติมิเตอร์ควรต่อเครื่องมืออย่างไร',c:['ต่ออนุกรมกับวงจร','ต่อขนานกับแหล่งจ่าย','ต่อคร่อมโหลดโดยไม่เปิดวงจร','ต่อที่จุดใดก็ได้โดยไม่เลือกย่านวัด'],a:'ต่ออนุกรมกับวงจร'},
{l:'apply',q:'ก่อนวัดค่าความต้านทานของอุปกรณ์ในวงจร ควรดำเนินการข้อใดก่อน',c:['ตัดแหล่งจ่ายไฟออกจากวงจร','เพิ่มแรงดันให้สูงที่สุด','ลัดวงจรที่ขั้วอุปกรณ์','เลือกย่านวัดกระแสสูงสุด'],a:'ตัดแหล่งจ่ายไฟออกจากวงจร'},
{l:'analyze',q:'คำนวณได้ว่ากระแสควรเป็น 2 A แต่ค่าที่วัดได้เป็นศูนย์ ควรตรวจสอบสิ่งใดก่อน',c:['การขาดของวงจรและจุดต่อสาย','เพิ่มแรงดันให้สูงขึ้นทันที','ลดค่าความต้านทานโดยไม่ตรวจวงจร','สรุปว่าเครื่องมือเสียโดยไม่ทดสอบ'],a:'การขาดของวงจรและจุดต่อสาย'},
{l:'analyze',q:'ตัวต้านทานร้อนผิดปกติหลังต่อวงจร แนวทางวิเคราะห์ใดเหมาะสมที่สุด',c:['ตรวจกำลังสูญเสียและพิกัดกำลังของตัวต้านทาน','เพิ่มกระแสเพื่อทดสอบความทนทาน','จับตัวต้านทานทันทีเพื่อตรวจอุณหภูมิ','เปลี่ยนเป็นลวดตัวนำแทนตัวต้านทาน'],a:'ตรวจกำลังสูญเสียและพิกัดกำลังของตัวต้านทาน'}],
plc:[
{l:'remember',q:'หน้าที่หลักของ PLC ในระบบควบคุมคือข้อใด',c:['รับข้อมูล ประมวลผลตามโปรแกรม และสั่งเอาต์พุต','เพิ่มแรงดันไฟฟ้าให้มอเตอร์','แปลงไฟฟ้ากระแสสลับเป็นกระแสตรงเท่านั้น','วัดค่าความต้านทานของโหลด'],a:'รับข้อมูล ประมวลผลตามโปรแกรม และสั่งเอาต์พุต'},
{l:'remember',q:'คอนแทค Normally Open ใน Ladder Diagram ทำงานอย่างไรเมื่อเงื่อนไขเป็นจริง',c:['คอนแทคมีสภาวะนำทางตรรกะ','คอนแทคตัดวงจรทางตรรกะ','เอาต์พุตทุกจุดถูกรีเซต','PLC หยุดสแกนโปรแกรม'],a:'คอนแทคมีสภาวะนำทางตรรกะ'},
{l:'apply',q:'วงจร Self-holding เหมาะสำหรับงานใด',c:['รักษาสถานะเอาต์พุตหลังปล่อยปุ่มเริ่ม','วัดความเร็วรอบของมอเตอร์','แปลงสัญญาณแอนะล็อกเป็นดิจิทัล','ป้องกันไฟฟ้าลัดวงจรที่เมนจ่ายไฟ'],a:'รักษาสถานะเอาต์พุตหลังปล่อยปุ่มเริ่ม'},
{l:'apply',q:'ต้องการให้เอาต์พุตทำงานหลังอินพุตครบเวลาที่กำหนด ควรใช้คำสั่งใด',c:['Timer แบบหน่วงเวลาเปิด','Counter แบบนับลง','คำสั่ง Reset เพียงอย่างเดียว','คอนแทคปกติปิดเพียงตัวเดียว'],a:'Timer แบบหน่วงเวลาเปิด'},
{l:'analyze',q:'ไฟสถานะอินพุตติด แต่เอาต์พุตไม่ทำงาน ขั้นตอนตรวจสอบใดเหมาะสมที่สุด',c:['ตรวจเงื่อนไขโปรแกรม สถานะคอยล์ และวงจรเอาต์พุตตามลำดับ','เปลี่ยน PLC ทันทีโดยไม่ตรวจโปรแกรม','เพิ่มแรงดันอินพุตเกินพิกัด','ลัดขั้วเอาต์พุตเพื่อทดสอบ'],a:'ตรวจเงื่อนไขโปรแกรม สถานะคอยล์ และวงจรเอาต์พุตตามลำดับ'},
{l:'analyze',q:'การใช้ SET โดยไม่มีเงื่อนไข RST ที่เหมาะสมอาจทำให้เกิดผลใด',c:['เอาต์พุตค้างทำงานและไม่กลับสู่สถานะที่ต้องการ','Timer หยุดนับทุกตัว','อินพุตทั้งหมดเปลี่ยนเป็นแอนะล็อก','หน่วยความจำถูกลบโดยอัตโนมัติ'],a:'เอาต์พุตค้างทำงานและไม่กลับสู่สถานะที่ต้องการ'}],
transformer:[
{l:'remember',q:'หลักการทำงานพื้นฐานของหม้อแปลงไฟฟ้าอาศัยปรากฏการณ์ใด',c:['การเหนี่ยวนำแม่เหล็กไฟฟ้า','การเปลี่ยนพลังงานเคมีเป็นไฟฟ้า','การสะสมประจุในตัวเก็บประจุ','การนำกระแสทางเดียวของไดโอด'],a:'การเหนี่ยวนำแม่เหล็กไฟฟ้า'},
{l:'remember',q:'หม้อแปลงแบบลดแรงดันมีความสัมพันธ์ของจำนวนรอบขดลวดอย่างไร',c:['ขดทุติยภูมิมีรอบน้อยกว่าขดปฐมภูมิ','ขดทุติยภูมิมีรอบมากกว่าขดปฐมภูมิ','ขดลวดทั้งสองต้องไม่มีแกนร่วมกัน','จำนวนรอบไม่มีผลต่อแรงดัน'],a:'ขดทุติยภูมิมีรอบน้อยกว่าขดปฐมภูมิ'},
{l:'apply',q:'การเลือกหม้อแปลงให้เหมาะกับโหลดควรพิจารณาข้อมูลใดร่วมกัน',c:['แรงดันด้านออก กระแสพิกัด และกำลังโหลด','สีฉนวนและขนาดกล่องเท่านั้น','ความยาวสายโดยไม่ดูพิกัดโหลด','แรงดันด้านเข้าเพียงค่าเดียว'],a:'แรงดันด้านออก กระแสพิกัด และกำลังโหลด'},
{l:'analyze',q:'หม้อแปลงมีเสียงดังและร้อนผิดปกติเมื่อจ่ายโหลด ควรตรวจสอบสาเหตุใดก่อน',c:['ภาระเกินพิกัดหรือการลัดวงจรด้านทุติยภูมิ','จำนวนสกรูฝาครอบไม่เท่ากัน','สีสายด้านปฐมภูมิ','ตำแหน่งฉลากบนตัวหม้อแปลง'],a:'ภาระเกินพิกัดหรือการลัดวงจรด้านทุติยภูมิ'},
{l:'analyze',q:'แรงดันด้านทุติยภูมิลดลงมากเมื่อมีโหลด แนวทางวิเคราะห์ใดเหมาะสมที่สุด',c:['ตรวจพิกัดโหลด แรงดันด้านเข้า และจุดต่อสาย','เพิ่มฟิวส์ให้ใหญ่ขึ้นทันที','ลัดขดลวดบางส่วนเพื่อเพิ่มแรงดัน','ตัดระบบป้องกันออกทั้งหมด'],a:'ตรวจพิกัดโหลด แรงดันด้านเข้า และจุดต่อสาย'}]};
function esc(s){return String(s||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
let activeTopic=null;
function data(){try{return JSON.parse(localStorage.getItem('vocResearchDraft'))||{}}catch(e){return{}}}
function topicList(){const d=data(),base=d.topics&&d.topics.length?d.topics:[$('topic').value],all=base.map(x=>String(x||'').trim()).filter(Boolean);return[...new Set(all)]}function topics(){return activeTopic===null?topicList().join(', '):activeTopic}
function facts(){const d=data(),ids=new Set(d.selected||[]);return(d.sources||[]).filter(s=>ids.has(s.id)&&(activeTopic===null||!s.topic||String(s.topic).trim()===String(activeTopic).trim())).flatMap(s=>{const raw=(s.extract||s.snippet||'').replace(/\r/g,'\n').trim(),sentences=raw.split(/(?:[.!?。]\s+|\n+)/).map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean);return sentences.flatMap(x=>x.length>260?(x.match(/.{35,240}(?:\s|$)/g)||[]):[x])}).filter((x,i,a)=>x.length>=12&&x.length<=260&&a.indexOf(x)===i)}
function domain(){const t=(topics()+(activeTopic===null?' '+$('subject').value:'')).toLowerCase();if(/โอห์ม|ohm/.test(t))return'ohm';if(/plc|ladder|gx works|โปรแกรมเมเบิล/.test(t))return'plc';if(/หม้อแปลง|transformer/.test(t))return'transformer';if(/วงจรไฟฟ้า|อนุกรม|ขนาน|เคอร์ชอฟฟ์|kirchhoff|kcl|kvl|กำลังไฟฟ้า/.test(t))return'circuit';return''}
function calcOhm(i){const vs=[6,9,12,18,24,30,36,48,60,72],rs=[2,3,4,5,6,8,10,12,15,20],v=vs[i%10],r=rs[(i*3+1)%10],a=+(v/r).toFixed(2);return{l:'apply',q:'วงจรมีแรงดัน '+v+' V และความต้านทาน '+r+' Ω กระแสไฟฟ้ามีค่าเท่าใด',c:[a+' A',+(v*r).toFixed(2)+' A',+(r/v).toFixed(2)+' A',+(a*2).toFixed(2)+' A'],a:a+' A'}}
function circuitCalc(i){const t=activeTopic||'';const patterns=/อนุกรม/.test(t)?[1,2,7]:/ขนาน/.test(t)?[3]:/KCL|กระแส.*เคอร์/i.test(t)?[5]:/KVL|แรงดัน.*เคอร์/i.test(t)?[6]:/กำลัง|พลังงาน/.test(t)?[4,8]:/โอห์ม|ohm/i.test(t)?[0,9]:null;if(patterns)i=Math.floor(i/patterns.length)*10+patterns[i%patterns.length];const k=1+Math.floor(i/10),n=i%10;let q,a,u,work;if(n===0)return calcOhm(i);if(n===1){const r1=2*k,r2=5*k;a=r1+r2;u='Ω';q='ตัวต้านทาน '+r1+' Ω และ '+r2+' Ω ต่ออนุกรมกัน ความต้านทานรวมมีค่าเท่าใด';work='Rt = R1 + R2 = '+a+' Ω'}else if(n===2){const r1=2*k,r2=4*k,v=12*k;a=+(v/(r1+r2)).toFixed(2);u='A';q='วงจรอนุกรมมี R1 = '+r1+' Ω, R2 = '+r2+' Ω ต่อกับแหล่งจ่าย '+v+' V กระแสในวงจรมีค่าเท่าใด';work='Rt = '+(r1+r2)+' Ω และ I = V/Rt = '+a+' A'}else if(n===3){const r1=6*k,r2=3*k;a=+((r1*r2)/(r1+r2)).toFixed(2);u='Ω';q='ตัวต้านทาน '+r1+' Ω และ '+r2+' Ω ต่อขนานกัน ความต้านทานรวมมีค่าเท่าใด';work='Rt = (R1R2)/(R1+R2) = '+a+' Ω'}else if(n===4){const v=12*k,current=2*k;a=v*current;u='W';q='โหลดไฟฟ้าใช้แรงดัน '+v+' V และกระแส '+current+' A กำลังไฟฟ้ามีค่าเท่าใด';work='P = VI = '+a+' W'}else if(n===5){const total=8*k,b1=3*k;a=total-b1;u='A';q='ที่จุดต่อหนึ่งมีกระแสไหลเข้า '+total+' A และไหลออกแขนงแรก '+b1+' A ตามกฎ KCL กระแสแขนงที่สองมีค่าเท่าใด';work='Iเข้า = Iออก รวม จึงได้ I2 = '+a+' A'}else if(n===6){const source=18*k,drop=7*k;a=source-drop;u='V';q='วงรอบมีแหล่งจ่าย '+source+' V และแรงดันตกคร่อมอุปกรณ์ตัวแรก '+drop+' V ตามกฎ KVL แรงดันตกคร่อมอุปกรณ์ตัวที่สองมีค่าเท่าใด';work='Vs = V1 + V2 จึงได้ V2 = '+a+' V'}else if(n===7){const v=12*k,r1=2*k,r2=4*k;a=+(v*r2/(r1+r2)).toFixed(2);u='V';q='วงจรแบ่งแรงดันมี R1 = '+r1+' Ω, R2 = '+r2+' Ω และ Vin = '+v+' V แรงดันคร่อม R2 มีค่าเท่าใด';work='Vout = Vin[R2/(R1+R2)] = '+a+' V'}else if(n===8){const p=60*k,t=3;a=p*t;u='Wh';q='อุปกรณ์กำลัง '+p+' W ทำงานเป็นเวลา '+t+' ชั่วโมง ใช้พลังงานไฟฟ้าเท่าใด';work='E = Pt = '+a+' Wh'}else{const v=24*k,current=3*k;a=+(v/current).toFixed(2);u='Ω';q='อุปกรณ์รับแรงดัน '+v+' V และมีกระแส '+current+' A ความต้านทานมีค่าเท่าใด';work='R = V/I = '+a+' Ω'}const nums=[a,+(a*2).toFixed(2),+(a/2).toFixed(2),+(a+2*k).toFixed(2)];return{l:n>=5?'analyze':'apply',q,c:nums.map(x=>x+' '+u),a:a+' '+u+'; '+work}}
function sourceItems(n){
 const fs=facts(),out=[],groups=[['แรงดันไฟฟ้า','กระแสไฟฟ้า','ความต้านทานไฟฟ้า','กำลังไฟฟ้า'],['โวลต์','แอมแปร์','โอห์ม','วัตต์'],['อนุกรม','ขนาน','วงจรผสม','ลัดวงจร'],['อินพุต','เอาต์พุต','Timer','Counter'],['SET','RST','Self-holding','Ladder Diagram'],['ปฐมภูมิ','ทุติยภูมิ','แกนเหล็ก','ขดลวด'],['ตัวต้านทาน','ตัวเก็บประจุ','ตัวเหนี่ยวนำ','ไดโอด']];
 const uniq=a=>[...new Set(a.map(x=>String(x||'').trim()).filter(Boolean))];
 const makeDistractors=(answer)=>{
   const words=answer.split(/\s+/).filter(Boolean),d=[];
   if(words.length>=2)d.push(words.slice().reverse().join(' '));
   if(words.length>=3){d.push([words[0],words[2],words[1],...words.slice(3)].join(' '));d.push([words[1],words[0],...words.slice(2)].join(' '));}
   d.push(answer.replace(/Programmable/gi,'Program'));
   d.push(answer.replace(/Controller/gi,'Control'));
   d.push(answer.replace(/Logic/gi,'Line'));
   return uniq(d).filter(x=>x!==answer);
 };
 fs.forEach(f=>{
   // 1) ตัวเลข/หน่วย: ใช้ได้เมื่อข้อมูลมีตัวเลขจริง
   const numbers=[...f.matchAll(/\d+(?:\.\d+)?(?:\s*(?:V|A|W|Ω|Hz|โวลต์|แอมแปร์|วัตต์|โอห์ม|เปอร์เซ็นต์|%))?/gi)];
   numbers.slice(0,2).forEach(m=>{const raw=m[0],value=Number((raw.match(/\d+(?:\.\d+)?/)||['0'])[0]),unit=raw.replace(/\d+(?:\.\d+)?/,'').trim(),values=[value,value+1,value*2,Math.max(0,value/2),value+2,value+3].map(v=>String(+v.toFixed(2))+(unit?' '+unit:''));out.push({l:'remember',q:f.replace(raw,'□□□□')+' ค่าที่หายไปคือข้อใด',c:uniq(values).slice(0,4),a:values[0]})});
   // 2) คำศัพท์สำคัญที่ปรากฏอยู่ในประโยค
   groups.forEach(group=>group.forEach(answer=>{if(f.toLowerCase().includes(answer.toLowerCase())){const pattern=new RegExp(answer.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i');const c=group;out.push({l:'remember',q:f.replace(pattern,'□□□□')+' คำที่หายไปคือข้อใด',c,a:answer})}}));
   // 3) นิยาม/ความหมาย/คำย่อ รองรับทั้งข้อความไทยและอังกฤษ และไม่บังคับว่าต้องมีตัวเลือกจากแหล่งอื่น
   const def=f.match(/^(.{2,100}?)(?:\s*ย่อมาจาก\s*|\s*คือ\s*|\s*หมายถึง\s*|\s*ทำหน้าที่\s*|\s*ใช้สำหรับ\s*)(.{2,220}?)(?:[.!?。]|$)/);
   if(def){
     const subject=def[1].trim(),answer=def[2].trim(),isAbbr=/ย่อมาจาก/.test(f),choices=[answer];
     if(isAbbr)choices.push(...makeDistractors(answer));
     fs.forEach(x=>{const m=x.match(/^(.{2,100}?)(?:\s*ย่อมาจาก\s*|\s*คือ\s*|\s*หมายถึง\s*|\s*ทำหน้าที่\s*|\s*ใช้สำหรับ\s*)(.{2,220}?)(?:[.!?。]|$)/);if(m&&m[2].trim()!==answer)choices.push(m[2].trim())});
     let finalChoices=uniq(choices).slice(0,4);
     // หากคำตอบเป็นคำย่อ/คำศัพท์สั้นมาก ให้สร้างตัวลวงจากโครงสร้างคำโดยตรง
     if(finalChoices.length<4)finalChoices=uniq([...finalChoices,...makeDistractors(answer),answer+' Controller',answer+' Control',answer+' Logic']).slice(0,4);
     while(finalChoices.length<4)finalChoices.push('ไม่ใช่ความหมายที่กำหนด');
     out.push({l:'remember',q:isAbbr?subject+' ย่อมาจากคำว่าอะไร':subject+' หมายถึงข้อใด',c:finalChoices,a:answer});
   }
 });
 return out.filter((x,i,a)=>x.c&&x.c.length===4&&a.findIndex(y=>y.q===x.q)===i).slice(0,n);
}
function legacyQuestions(useFacts){const n=Math.max(1,Math.min(60,window.worksheetStudio?.activeCount??(+$('count').value||1))),key=domain(),isCircuit=key==='ohm'||key==='circuit',type=$('type').value;if(!useFacts||!facts().length)return[];const theory=sourceItems(n);if(!isCircuit||type==='ถาม–ตอบ'||type==='ใบงานปฏิบัติ')return theory.slice(0,n);const rate=type==='คำนวณ'?1:type==='แบบผสม'?.65:type.includes('ปรนัย')?.55:.4,calcN=Math.min(n,Math.max(1,Math.round(n*rate))),theoryN=Math.min(theory.length,n-calcN),out=theory.slice(0,theoryN);for(let i=0;out.length<n&&i<60;i++)out.push(key==='ohm'&&i%3===0?calcOhm(i):circuitCalc(i));return out.filter((x,i,a)=>a.findIndex(y=>y.q===x.q)===i).slice(0,n)}
function questions(useFacts){
 const plan=window.worksheetStudio?.allocation()||topicList().map((topic,i,a)=>({topic,count:Math.floor(+$('count').value/a.length)+(i<(+$('count').value%a.length)?1:0)}));
 const out=[];try{for(const part of plan){if(!part.count)continue;activeTopic=part.topic;if(window.worksheetStudio)window.worksheetStudio.activeCount=part.count;
 const qs=legacyQuestions(useFacts);qs.forEach(q=>out.push({...q,topic:part.topic}));
 }}finally{activeTopic=null;if(window.worksheetStudio)window.worksheetStudio.activeCount=null}return out;
}
window.worksheetQuality={topics:topicList,questions};
function choice(item,i){const shift=i%4,rot=[...item.c.slice(shift),...item.c.slice(0,shift)],correct=item.c.indexOf(item.a.split(';')[0]),ans=letters[(correct-shift+4)%4];return{html:'<div class="choices">'+rot.map((x,n)=>'<span>'+letters[n]+'. '+esc(x)+'</span>').join('')+'</div>',answer:ans+'. '+item.a}}
function images(){const d=data(),chosen=d.image?[{src:d.image}]:[],found=[...document.querySelectorAll('#imageList img')].map(x=>({src:x.src}));return[...chosen,...found].filter((x,i,a)=>a.findIndex(y=>y.src===x.src)===i)}
function rebuild(useFacts){const list=document.querySelector('.exercise');if(!list)return;const type=$('type').value,limit=Math.max(1,Math.min(60,+$('count').value||1)),manual=(window.worksheetManual?.items()||[]).slice(0,limit),generated=questions(useFacts).slice(0,Math.max(0,limit-manual.length));list.innerHTML='';generated.forEach((item,i)=>{const li=document.createElement('li');let body='<small class="question-topic">'+esc(item.topic)+'</small>'+esc(item.q),answer=item.a;if(item.c&&item.c.length===4&&(type.includes('ปรนัย')||(type==='แบบผสม'&&i%3!==2)||type==='คำนวณ')){const c=choice(item,i);body+=c.html;answer=c.answer}else body+='<div class="answer-lines"></div>';li.innerHTML=body+'<div class="answer"><b>เฉลย/แนวคำตอบ:</b> '+esc(answer)+'</div>';list.appendChild(li)});manual.forEach(item=>{const li=document.createElement('li'),correct=letters[item.correct]||'ก';li.className='manual-question';li.innerHTML='<small class="question-topic">'+esc(item.topic||'โจทย์ที่ครูเพิ่ม')+'</small>'+esc(item.question)+'<div class="choices">'+item.choices.map((x,n)=>'<span>'+letters[n]+'. '+esc(x)+'</span>').join('')+'</div><div class="answer"><b>เฉลย:</b> '+correct+'. '+esc(item.choices[item.correct])+'</div>';list.appendChild(li)});const total=generated.length+manual.length,score=document.querySelector('.scorebox');if(score)score.innerHTML='คะแนนที่ได้ ______ / '+total+' คะแนน<br>ผู้ตรวจ __________________';const instruction=[...document.querySelectorAll('.block')].find(x=>x.querySelector('h3')?.textContent==='คำชี้แจง')?.querySelector('p');if(instruction)instruction.textContent=instruction.textContent.replace(/จำนวน \d+ ข้อ|คะแนนเต็ม \d+ คะแนน/g,m=>m.startsWith('จำนวน')?'จำนวน '+total+' ข้อ':'คะแนนเต็ม '+total+' คะแนน');if(useFacts&&$('researchStatus'))$('researchStatus').textContent=total<limit?'สร้างได้ '+total+' ข้อจากเนื้อหาที่มี • เพิ่มเนื้อหาหรือเพิ่มโจทย์เองหากต้องการให้ครบ '+limit+' ข้อ':'สร้างคำถามจากเนื้อหาที่เลือกครบ '+total+' ข้อแล้ว'}
function documentTitle(){const custom=$('customTitle').value.trim(),k=$('docKind').value,list=topicList();if(custom)return custom;if(list.length<=3){const names=list.length<2?list[0]||$('subject').value:list.slice(0,-1).join(', ')+' และ'+list[list.length-1];return k+' เรื่อง '+names}return k==='ใบงาน'?'ใบงานบูรณาการ รายวิชา'+$('subject').value:k+' รายวิชา'+$('subject').value}function docKind(){const k=$('docKind').value,meta=document.querySelector('.doc-meta h2');if(meta)meta.textContent=documentTitle();const ps=document.querySelectorAll('.doc-meta p');if(ps[1])ps[1].innerHTML='<b>รูปแบบคำถาม:</b> '+esc($('type').value);const no=document.querySelector('.doc-no');if(no)no.innerHTML='ฉบับที่<br><b>01</b>';const exam=k!=='ใบงาน';document.querySelectorAll('.block').forEach(b=>{const h=b.querySelector('h3')?.textContent||'';if(exam&&(h.includes('จุดประสงค์')||h.includes('ความรู้เบื้องต้น')))b.style.display='none'});const ins=[...document.querySelectorAll('.block')].find(x=>x.querySelector('h3')?.textContent.includes('คำชี้แจง'))?.querySelector('p');if(ins&&exam)ins.textContent='ให้ผู้เรียนทำ'+k+'ให้ครบทุกข้อ เลือกคำตอบหรือแสดงวิธีทำตามที่โจทย์กำหนด คะแนนเต็ม '+$('count').value+' คะแนน'}
function polish(useFacts){const p=$('paper');if(!p)return;p.querySelector('.foot')?.remove();p.querySelector('.worksheet-image')?.remove();[...p.querySelectorAll('.student-line span')].filter(x=>x.textContent.trim().startsWith('วันที่')).forEach(x=>x.remove());const crest=p.querySelector('.crest');if(crest)crest.innerHTML='<img src="./pic-logo.png" alt="ตราวิทยาลัยเทคนิคปากช่อง">';docKind();if(!window.worksheetStudio?.renderSpecial())rebuild(useFacts)}
let fromSources=false;if($('type').value==='วิเคราะห์')$('type').value='ปรนัย 4 ตัวเลือก ก ข ค ง';function render(){previousRender();polish(fromSources)}window.render=render;function generateFromSelected(){if(!facts().length){alert('กรุณาค้นหา เลือก หรือวางเนื้อหาก่อนสร้างคำถาม');return}fromSources=true;render();}window.worksheetQuality.generateFromSelected=generateFromSelected;$('generateBtn').onclick=generateFromSelected;$('aiGenerateBtn').onclick=generateFromSelected;
$('docKind').value=localStorage.getItem('vocDocKind')||'ใบงาน';$('customTitle').value=localStorage.getItem('vocCustomTitle')||'';function buildLabel(){$('aiGenerateBtn').textContent='สร้าง'+$('docKind').value+'จากเนื้อหาที่เลือก'}$('docKind').onchange=()=>{localStorage.setItem('vocDocKind',$('docKind').value);buildLabel();render()};$('customTitle').oninput=()=>{localStorage.setItem('vocCustomTitle',$('customTitle').value);render()};buildLabel();
$('aiGenerateBtn').onclick=generateFromSelected;
$('downloadPdfBtn').onclick=async()=>{const b=$('downloadPdfBtn'),old=b.innerHTML;if(typeof html2pdf==='undefined'){alert('ไม่สามารถเปิดตัวสร้าง PDF ได้ กรุณารีเฟรชหน้าแล้วลองใหม่');return}b.disabled=true;b.textContent='กำลังสร้าง PDF…';const name=($('docKind').value+'-'+$('subject').value).replace(/[\\/:*?"<>|]/g,'-')+'.pdf';try{await html2pdf().set({margin:0,filename:name,image:{type:'jpeg',quality:.96},html2canvas:{scale:2,useCORS:true,backgroundColor:'#ffffff',logging:false},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'},pagebreak:{mode:['css','legacy'],avoid:['li','.doc-header','.student-line','.question-visual']}}).from($('paper')).save()}catch(e){alert('สร้าง PDF ไม่สำเร็จ กรุณาใช้ปุ่มพิมพ์แล้วเลือกบันทึกเป็น PDF แทน')}finally{b.disabled=false;b.innerHTML=old}};
const reset=$('resetBtn').onclick;$('resetBtn').onclick=()=>{localStorage.removeItem('vocDocKind');localStorage.removeItem('vocCustomTitle');localStorage.removeItem('vocResearchDraft');localStorage.removeItem('vocManualQuestions');reset()};render();
})();
