(function(){
  const state={sources:[],selected:new Set(),topics:[],images:[],image:null,imageCredit:'',researched:false,openSources:new Set(),factSelections:null};
  const byId=id=>document.getElementById(id); const baseRender=window.render;
  function clean(html){const d=document.createElement('div');d.innerHTML=html||'';return(d.textContent||'').replace(/\s+/g,' ').trim()}
  function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
  function setStatus(message){const node=byId('researchStatus');node.textContent=message;delete node.dataset.tone}
  function save(){try{localStorage.setItem('vocResearchDraft',JSON.stringify({sources:state.sources,selected:[...state.selected],topics:state.topics,images:state.images,image:state.image,imageCredit:state.imageCredit,factSelections:state.factSelections?[...state.factSelections]:null}))}catch(e){}document.dispatchEvent(new Event('research-updated'))}
  function load(){try{const d=JSON.parse(localStorage.getItem('vocResearchDraft'));if(!d)return;state.sources=d.sources||[];state.selected=new Set(d.selected||[]);state.topics=d.topics||[];state.images=d.images||[];state.image=d.image||null;state.imageCredit=d.imageCredit||'';state.factSelections=Array.isArray(d.factSelections)?new Set(d.factSelections):null;drawSources();drawImages();drawTopics()}catch(e){}}
  async function mediaSearch(domain,query,label){const u=new URL('https://'+domain+'/w/api.php');u.search=new URLSearchParams({action:'query',list:'search',srsearch:query,srlimit:'3',format:'json',origin:'*'});const r=await fetch(u);if(!r.ok)throw Error(label);const j=await r.json();return(j.query?.search||[]).map(x=>({id:domain+':'+x.pageid,title:x.title,snippet:clean(x.snippet),url:'https://'+domain+'/wiki/'+encodeURIComponent(x.title.replace(/ /g,'_')),label,domain}))}
  async function commonsSearch(query){const u=new URL('https://commons.wikimedia.org/w/api.php');u.search=new URLSearchParams({action:'query',generator:'search',gsrsearch:query+' filetype:bitmap',gsrnamespace:'6',gsrlimit:'6',prop:'imageinfo',iiprop:'url|extmetadata',iiurlwidth:'500',format:'json',origin:'*'});const r=await fetch(u);if(!r.ok)throw Error('images');const j=await r.json();return Object.values(j.query?.pages||{}).map(p=>{const i=p.imageinfo?.[0]||{},m=i.extmetadata||{};return{url:i.thumburl||i.url,title:p.title.replace(/^File:/,''),credit:clean(m.Artist?.value)||'Wikimedia Commons',license:clean(m.LicenseShortName?.value)||'ตรวจสอบสัญญาอนุญาต',page:i.descriptionurl}}).filter(x=>x.url)}
  async function enrich(s){try{const u=new URL('https://'+s.domain+'/w/api.php');u.search=new URLSearchParams({action:'query',prop:'extracts',exintro:'1',explaintext:'1',pageids:s.id.split(':')[1],format:'json',origin:'*'});const j=await(await fetch(u)).json();s.extract=Object.values(j.query?.pages||{})[0]?.extract||s.snippet}catch(e){s.extract=s.snippet}return s}
  byId('researchBtn').onclick=async()=>{const q=(byId('researchQuery').value||byId('topic').value).trim();if(!q)return;setStatus('กำลังค้นหาหลายแหล่งสำหรับ “'+q+'” …');byId('researchBtn').disabled=true;try{const results=await Promise.allSettled([mediaSearch('th.wikipedia.org',q,'วิกิพีเดีย'),mediaSearch('th.wikibooks.org',q,'วิกิตำราไทย'),mediaSearch('th.wikiversity.org',q,'วิกิมหาวิทยาลัย'),mediaSearch('en.wikibooks.org',q+' '+(byId('subject').value||''),'ตำราอังกฤษ')]);const found=results.filter(x=>x.status==='fulfilled').flatMap(x=>x.value);const fresh=await Promise.all(found.map(enrich));fresh.forEach(x=>x.topic=q);state.sources=[...state.sources,...fresh].filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i);if(!state.topics.includes(q))state.topics.push(q);fresh.slice(0,5).forEach(x=>{state.selected.add(x.id);enableFacts(x)});state.researched=true;drawSources();drawImages();drawTopics();byId('researchQuery').value='';setStatus(fresh.length?'พบ '+fresh.length+' รายการจากหลายแหล่ง • เลือกข้อมูลที่ต้องการได้':'ยังไม่พบข้อมูล ให้กด “ค้นเว็บทั่วไป” หรือวางเนื้อหาเอง');save()}catch(e){setStatus('ค้นหาไม่สำเร็จ กรุณาลองคำค้นที่สั้นลงหรือวางเนื้อหาเอง')}finally{byId('researchBtn').disabled=false}};
  function sourceAnalysis(source){const fallback={raw:String(source.extract||source.snippet||'').replace(/\s+/g,' ').trim(),items:[],count:0};try{return window.worksheetQuality?.inspectSource?.(source)||fallback}catch{return fallback}}
  function allFactKeys(){return state.sources.flatMap(source=>(sourceAnalysis(source).items||[]).map(item=>item.key).filter(Boolean))}
  function factEnabled(key){return state.factSelections===null||state.factSelections.has(key)}
  function enableFacts(source){if(state.factSelections===null)return;(sourceAnalysis(source).items||[]).forEach(item=>{if(item.key)state.factSelections.add(item.key)})}
  function toggleFact(key){if(state.factSelections===null)state.factSelections=new Set(allFactKeys());state.factSelections.has(key)?state.factSelections.delete(key):state.factSelections.add(key)}
  function highlightedText(raw,items){let html=escapeHtml(raw);const parts=[...new Set((items||[]).map(item=>String(item.evidence||'').trim()).filter(Boolean))].sort((a,b)=>b.length-a.length);parts.forEach(part=>{const safe=escapeHtml(part);if(safe&&html.includes(safe))html=html.replace(safe,'<mark class="source-highlight">'+safe+'</mark>')});return html}
  function inspectorMarkup(source){const info=sourceAnalysis(source),open=state.openSources.has(source.id)?' open':'',items=info.items||[],count=info.count||0,preview=info.raw?highlightedText(info.raw,items):'ไม่มีข้อความให้ตรวจสอบ';const list=items.length?'<p class="source-choice-note">แตะ ✓ ใช้ เพื่อเลือกหรือไม่เลือกประเด็นนี้สำหรับสร้างโจทย์</p><ul class="source-fact-list">'+items.map(item=>'<li class="'+(factEnabled(item.key)?'fact-picked':'fact-skipped')+'"><button type="button" class="fact-toggle" data-fact-key="'+escapeHtml(item.key)+'" aria-pressed="'+(factEnabled(item.key)?'true':'false')+'">'+(factEnabled(item.key)?'✓ ใช้':'＋ ไม่ใช้')+'</button><div><b>'+escapeHtml(item.summary)+'</b><span>'+item.uses.map(use=>'<em>'+escapeHtml(use)+'</em>').join('')+'</span></div></li>').join('')+'</ul>':'<p class="source-no-fact">ยังไม่พบประโยคที่ใช้สร้างโจทย์ได้โดยตรง</p>';return'<details class="source-inspector" data-inspector="'+escapeHtml(source.id)+'"'+open+'><summary>ดูส่วนที่ใช้สร้างโจทย์ <strong>'+count+' ประเด็น</strong></summary><p class="source-inspector-note">เลือกได้ทีละประเด็น ระบบจะสร้างโจทย์จากทุกประเด็นที่เลือก</p><div class="source-preview">'+preview+'</div>'+list+'</details>'}
  function drawSources(){const list=byId('sourceList');list.innerHTML=state.sources.map(source=>'<div class="source-card '+(state.selected.has(source.id)?'selected':'')+'" data-id="'+escapeHtml(source.id)+'"><button type="button" class="source-select" data-select="'+escapeHtml(source.id)+'"><b>'+escapeHtml(source.label)+': '+escapeHtml(source.title)+'</b><span>'+escapeHtml(source.snippet||'เปิดอ่านข้อมูลจากแหล่งต้นทาง')+'</span><small>'+((state.selected.has(source.id))?'✓ ใช้เนื้อหานี้':'แตะเพื่อเลือกใช้เนื้อหานี้')+'</small></button>'+inspectorMarkup(source)+'</div>').join('');list.querySelectorAll('[data-select]').forEach(button=>button.onclick=()=>{const id=button.dataset.select,source=state.sources.find(x=>x.id===id);if(state.selected.has(id))state.selected.delete(id);else{state.selected.add(id);if(source)enableFacts(source)}drawSources();drawTopics();save()});list.querySelectorAll('[data-fact-key]').forEach(button=>button.onclick=e=>{e.preventDefault();e.stopPropagation();toggleFact(button.dataset.factKey);drawSources();drawTopics();save();window.render?.()});list.querySelectorAll('[data-inspector]').forEach(details=>details.ontoggle=()=>{const id=details.dataset.inspector;if(details.open)state.openSources.add(id);else state.openSources.delete(id)})}
  function drawTopics(){const basket=byId('topicBasket'),count=byId('contentCount');if(!basket)return;basket.innerHTML=state.topics.map((t,i)=>'<span class="topic-chip">'+clean(t)+'<button type="button" data-i="'+i+'" aria-label="ลบ '+clean(t)+'">×</button></span>').join('');const usable=state.sources.filter(source=>state.selected.has(source.id)).reduce((sum,source)=>sum+(sourceAnalysis(source).items||[]).filter(item=>factEnabled(item.key)).length,0);count.textContent=state.topics.length?'เลือกแล้ว '+state.topics.length+' เนื้อหา • แหล่งข้อมูล '+state.selected.size+' รายการ • ใช้สร้างโจทย์ได้ '+usable+' ประเด็น':'ยังไม่มีเนื้อหาที่เลือก';basket.querySelectorAll('button').forEach(b=>b.onclick=()=>{const topic=state.topics[+b.dataset.i];state.topics.splice(+b.dataset.i,1);const removed=state.sources.filter(s=>s.topic===topic).map(s=>s.id);removed.forEach(id=>state.selected.delete(id));state.sources=state.sources.filter(s=>s.topic!==topic);state.images=state.images.filter(im=>im.topic!==topic);drawTopics();drawSources();drawImages();save();window.render()})}
  function drawImages(){byId('imageList').hidden=true;return;
byId('imageList').innerHTML=(state.images||[]).map((im,i)=>`<button class="image-choice ${state.image===im.url?'selected':''}" data-i="${i}" title="${im.title}"><img src="${im.url}" alt="${im.title}" loading="lazy"></button>`).join('');byId('imageList').querySelectorAll('button').forEach(el=>el.onclick=()=>{const im=state.images[+el.dataset.i];state.image=im.url;state.imageCredit=`${im.title} — ${im.credit}, ${im.license}`;drawImages();window.render();save()})}
  byId('imageUpload').onchange=e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>4*1024*1024){alert('กรุณาเลือกภาพขนาดไม่เกิน 4 MB');return}const r=new FileReader();r.onload=()=>{state.image=r.result;state.imageCredit='ภาพที่ครูเพิ่มจากอุปกรณ์';window.render();save()};r.readAsDataURL(f)};
  byId('webSearchBtn').onclick=()=>{const q=(byId('researchQuery').value||byId('manualSourceTitle').value||byId('topic').value).trim();window.open('https://www.google.com/search?q='+encodeURIComponent(q),'_blank','noopener')};
  byId('addManualSourceBtn').onclick=()=>{const title=byId('manualSourceTitle').value.trim(),extract=byId('manualSourceText').value.replace(/\s+/g,' ').trim(),url=byId('manualSourceUrl').value.trim(),topic=(byId('researchQuery').value||title||byId('topic').value).trim();if(!title||extract.length<40){alert('กรุณาใส่ชื่อแหล่งข้อมูลและเนื้อหาอย่างน้อย 40 ตัวอักษร');return}const source={id:'manual:'+Date.now(),title,snippet:extract.slice(0,180)+(extract.length>180?'…':''),extract,url,label:'เนื้อหาที่ครูเพิ่ม',domain:'',topic};state.sources.push(source);state.selected.add(source.id);enableFacts(source);if(topic&&!state.topics.includes(topic))state.topics.push(topic);byId('manualSourceTitle').value='';byId('manualSourceUrl').value='';byId('manualSourceText').value='';drawSources();drawTopics();save();setStatus('เพิ่มเนื้อหาจาก “'+title+'” แล้ว')};
  function selectedSources(){return state.sources.filter(s=>state.selected.has(s.id))}
  function sentences(){return selectedSources().flatMap(s=>(s.extract||s.snippet||'').split(/(?<=[.!?。]|\sครับ|\sค่ะ)\s+/)).map(x=>x.trim()).filter(x=>x.length>45&&x.length<300).slice(0,12)}
  function injectResearch(){const paper=byId('paper');if(!paper)return;const meta=paper.querySelector('.doc-meta');if(state.image&&meta){meta.insertAdjacentHTML('afterend',`<figure class="worksheet-image"><img src="${state.image}" alt="ภาพประกอบหัวข้อใบงาน"><figcaption><p><b>ภาพประกอบการเรียนรู้</b></p><p>${state.imageCredit||'ภาพประกอบที่เลือกโดยครู'}</p></figcaption></figure>`)}const src=selectedSources();if(src.length){const score=paper.querySelector('.scorebox');score?.insertAdjacentHTML('beforebegin',`<div class="sources-print"><b>แหล่งข้อมูลประกอบ:</b> ${src.map((s,i)=>`${i+1}. ${s.label} — ${s.title}`).join(' • ')}<div class="source-warning">ครูควรตรวจสอบความถูกต้องและความเหมาะสมของเนื้อหาก่อนนำไปใช้กับผู้เรียน</div></div>`)}}
  function injectVisualOnly(){const paper=byId('paper');if(!paper||!state.image)return;const meta=paper.querySelector('.doc-meta');if(!meta)return;const figure=document.createElement('figure');figure.className='worksheet-image';figure.innerHTML='<img alt="ภาพประกอบหัวข้อใบงาน"><figcaption><p><b>ภาพประกอบการเรียนรู้</b></p></figcaption>';figure.querySelector('img').src=state.image;meta.insertAdjacentElement('afterend',figure)}
  function renderEnhanced(){baseRender()}
  window.render=renderEnhanced;byId('generateBtn').onclick=renderEnhanced;
  window.worksheetResearch={refreshSources:()=>{drawSources();drawTopics()}};
  load();renderEnhanced();
})();
