(function(){
  const state={sources:[],selected:new Set(),topics:[],images:[],image:null,imageCredit:'',researched:false};
  const byId=id=>document.getElementById(id); const baseRender=window.render;
  function clean(html){const d=document.createElement('div');d.innerHTML=html||'';return(d.textContent||'').replace(/\s+/g,' ').trim()}
  function save(){try{localStorage.setItem('vocResearchDraft',JSON.stringify({sources:state.sources,selected:[...state.selected],topics:state.topics,images:state.images,image:state.image,imageCredit:state.imageCredit}))}catch(e){}document.dispatchEvent(new Event('research-updated'))}
  function load(){try{const d=JSON.parse(localStorage.getItem('vocResearchDraft'));if(!d)return;state.sources=d.sources||[];state.selected=new Set(d.selected||[]);state.topics=d.topics||[];state.images=d.images||[];state.image=d.image||null;state.imageCredit=d.imageCredit||'';drawSources();drawImages();drawTopics()}catch(e){}}
  async function mediaSearch(domain,query,label){const u=new URL('https://'+domain+'/w/api.php');u.search=new URLSearchParams({action:'query',list:'search',srsearch:query,srlimit:'3',format:'json',origin:'*'});const r=await fetch(u);if(!r.ok)throw Error(label);const j=await r.json();return(j.query?.search||[]).map(x=>({id:domain+':'+x.pageid,title:x.title,snippet:clean(x.snippet),url:'https://'+domain+'/wiki/'+encodeURIComponent(x.title.replace(/ /g,'_')),label,domain}))}
  async function commonsSearch(query){const u=new URL('https://commons.wikimedia.org/w/api.php');u.search=new URLSearchParams({action:'query',generator:'search',gsrsearch:query+' filetype:bitmap',gsrnamespace:'6',gsrlimit:'6',prop:'imageinfo',iiprop:'url|extmetadata',iiurlwidth:'500',format:'json',origin:'*'});const r=await fetch(u);if(!r.ok)throw Error('images');const j=await r.json();return Object.values(j.query?.pages||{}).map(p=>{const i=p.imageinfo?.[0]||{},m=i.extmetadata||{};return{url:i.thumburl||i.url,title:p.title.replace(/^File:/,''),credit:clean(m.Artist?.value)||'Wikimedia Commons',license:clean(m.LicenseShortName?.value)||'ตรวจสอบสัญญาอนุญาต',page:i.descriptionurl}}).filter(x=>x.url)}
  async function enrich(s){try{const u=new URL('https://'+s.domain+'/w/api.php');u.search=new URLSearchParams({action:'query',prop:'extracts',exintro:'1',explaintext:'1',pageids:s.id.split(':')[1],format:'json',origin:'*'});const j=await(await fetch(u)).json();s.extract=Object.values(j.query?.pages||{})[0]?.extract||s.snippet}catch(e){s.extract=s.snippet}return s}
  byId('researchBtn').onclick=async()=>{const q=(byId('researchQuery').value||byId('topic').value).trim();if(!q)return;byId('researchStatus').textContent='กำลังค้นหาหลายแหล่งสำหรับ “'+q+'” …';byId('researchBtn').disabled=true;try{const results=await Promise.allSettled([mediaSearch('th.wikipedia.org',q,'วิกิพีเดีย'),mediaSearch('th.wikibooks.org',q,'วิกิตำราไทย'),mediaSearch('th.wikiversity.org',q,'วิกิมหาวิทยาลัย'),mediaSearch('en.wikibooks.org',q+' '+(byId('subject').value||''),'ตำราอังกฤษ')]);const found=results.filter(x=>x.status==='fulfilled').flatMap(x=>x.value);const fresh=await Promise.all(found.map(enrich));fresh.forEach(x=>x.topic=q);state.sources=[...state.sources,...fresh].filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i);if(!state.topics.includes(q))state.topics.push(q);fresh.slice(0,5).forEach(x=>state.selected.add(x.id));state.researched=true;drawSources();drawImages();drawTopics();byId('researchQuery').value='';byId('researchStatus').textContent=fresh.length?'พบ '+fresh.length+' รายการจากหลายแหล่ง • เลือกข้อมูลที่ต้องการได้':'ยังไม่พบข้อมูล ให้กด “ค้นเว็บทั่วไป” หรือวางเนื้อหาเอง';save()}catch(e){byId('researchStatus').textContent='ค้นหาไม่สำเร็จ กรุณาลองคำค้นที่สั้นลงหรือวางเนื้อหาเอง'}finally{byId('researchBtn').disabled=false}};
  function drawSources(){byId('sourceList').innerHTML=state.sources.map(s=>`<div class="source-card ${state.selected.has(s.id)?'selected':''}" data-id="${s.id}"><b>${s.label}: ${s.title}</b><span>${s.snippet||'เปิดอ่านข้อมูลจากแหล่งต้นทาง'}</span></div>`).join('');byId('sourceList').querySelectorAll('.source-card').forEach(el=>el.onclick=()=>{state.selected.has(el.dataset.id)?state.selected.delete(el.dataset.id):state.selected.add(el.dataset.id);drawSources();save()})}
  function drawTopics(){const basket=byId('topicBasket'),count=byId('contentCount');if(!basket)return;basket.innerHTML=state.topics.map((t,i)=>'<span class="topic-chip">'+clean(t)+'<button type="button" data-i="'+i+'" aria-label="ลบ '+clean(t)+'">×</button></span>').join('');count.textContent=state.topics.length?'เลือกแล้ว '+state.topics.length+' เนื้อหา • แหล่งข้อมูล '+state.selected.size+' รายการ':'ยังไม่มีเนื้อหาที่เลือก';basket.querySelectorAll('button').forEach(b=>b.onclick=()=>{const topic=state.topics[+b.dataset.i];state.topics.splice(+b.dataset.i,1);const removed=state.sources.filter(s=>s.topic===topic).map(s=>s.id);removed.forEach(id=>state.selected.delete(id));state.sources=state.sources.filter(s=>s.topic!==topic);state.images=state.images.filter(im=>im.topic!==topic);drawTopics();drawSources();drawImages();save();window.render()})}
  function drawImages(){byId('imageList').hidden=true;return;
byId('imageList').innerHTML=(state.images||[]).map((im,i)=>`<button class="image-choice ${state.image===im.url?'selected':''}" data-i="${i}" title="${im.title}"><img src="${im.url}" alt="${im.title}" loading="lazy"></button>`).join('');byId('imageList').querySelectorAll('button').forEach(el=>el.onclick=()=>{const im=state.images[+el.dataset.i];state.image=im.url;state.imageCredit=`${im.title} — ${im.credit}, ${im.license}`;drawImages();window.render();save()})}
  byId('imageUpload').onchange=e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>4*1024*1024){alert('กรุณาเลือกภาพขนาดไม่เกิน 4 MB');return}const r=new FileReader();r.onload=()=>{state.image=r.result;state.imageCredit='ภาพที่ครูเพิ่มจากอุปกรณ์';window.render();save()};r.readAsDataURL(f)};
  byId('webSearchBtn').onclick=()=>{const q=(byId('researchQuery').value||byId('manualSourceTitle').value||byId('topic').value).trim();window.open('https://www.google.com/search?q='+encodeURIComponent(q),'_blank','noopener')};
  byId('addManualSourceBtn').onclick=()=>{const title=byId('manualSourceTitle').value.trim(),extract=byId('manualSourceText').value.replace(/\s+/g,' ').trim(),url=byId('manualSourceUrl').value.trim(),topic=(byId('researchQuery').value||title||byId('topic').value).trim();if(!title||extract.length<40){alert('กรุณาใส่ชื่อแหล่งข้อมูลและเนื้อหาอย่างน้อย 40 ตัวอักษร');return}const source={id:'manual:'+Date.now(),title,snippet:extract.slice(0,180)+(extract.length>180?'…':''),extract,url,label:'เนื้อหาที่ครูเพิ่ม',domain:'',topic};state.sources.push(source);state.selected.add(source.id);if(topic&&!state.topics.includes(topic))state.topics.push(topic);byId('manualSourceTitle').value='';byId('manualSourceUrl').value='';byId('manualSourceText').value='';drawSources();drawTopics();save();byId('researchStatus').textContent='เพิ่มเนื้อหาจาก “'+title+'” แล้ว'};
  function selectedSources(){return state.sources.filter(s=>state.selected.has(s.id))}
  function sentences(){return selectedSources().flatMap(s=>(s.extract||s.snippet||'').split(/(?<=[.!?。]|\sครับ|\sค่ะ)\s+/)).map(x=>x.trim()).filter(x=>x.length>45&&x.length<300).slice(0,12)}
  function injectResearch(){const paper=byId('paper');if(!paper)return;const meta=paper.querySelector('.doc-meta');if(state.image&&meta){meta.insertAdjacentHTML('afterend',`<figure class="worksheet-image"><img src="${state.image}" alt="ภาพประกอบหัวข้อใบงาน"><figcaption><p><b>ภาพประกอบการเรียนรู้</b></p><p>${state.imageCredit||'ภาพประกอบที่เลือกโดยครู'}</p></figcaption></figure>`)}const src=selectedSources();if(src.length){const score=paper.querySelector('.scorebox');score?.insertAdjacentHTML('beforebegin',`<div class="sources-print"><b>แหล่งข้อมูลประกอบ:</b> ${src.map((s,i)=>`${i+1}. ${s.label} — ${s.title}`).join(' • ')}<div class="source-warning">ครูควรตรวจสอบความถูกต้องและความเหมาะสมของเนื้อหาก่อนนำไปใช้กับผู้เรียน</div></div>`)}}
  function injectVisualOnly(){const paper=byId('paper');if(!paper||!state.image)return;const meta=paper.querySelector('.doc-meta');if(!meta)return;const figure=document.createElement('figure');figure.className='worksheet-image';figure.innerHTML='<img alt="ภาพประกอบหัวข้อใบงาน"><figcaption><p><b>ภาพประกอบการเรียนรู้</b></p></figcaption>';figure.querySelector('img').src=state.image;meta.insertAdjacentElement('afterend',figure)}
  function renderEnhanced(){baseRender()}
  window.render=renderEnhanced;byId('generateBtn').onclick=renderEnhanced;
  load();renderEnhanced();
})();
