(()=>{
const $=id=>document.getElementById(id);
let slides=[],cur=0,theme='blue',researchPoints=[],researchSources=[],selectedLayer=0,saveTimer=null,db=null,dragText=null;
const DBNAME='VocSlideAssetsV40',STORE='images';
function dbOpen(){return new Promise((res,rej)=>{if(db)return res(db);const r=indexedDB.open(DBNAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
async function dbPut(id,blob){const d=await dbOpen();return new Promise((res,rej)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(blob,id);t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}
async function dbGet(id){const d=await dbOpen();return new Promise((res,rej)=>{const r=d.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function dbDel(id){if(!id)return;const d=await dbOpen();return new Promise(res=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).delete(id);t.oncomplete=()=>res();t.onerror=()=>res()})}
const uid=()=> 'img_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8);
function cleanSlides(){return slides.map(s=>({...s,images:(s.images||[]).map(im=>{const x={...im};delete x.src;return x})}))}
async function hydrateImages(){for(const s of slides){for(const im of (s.images||[])){if(im.src)continue;if(im.id){const b=await dbGet(im.id).catch(()=>null);if(b)im.src=URL.createObjectURL(b)}}s.img=s.images?.[0]?.src||''}}
async function migrateDataImages(){let changed=false;for(const s of slides){for(const im of (s.images||[])){if(im.src&&im.src.startsWith('data:')){try{const b=await (await fetch(im.src)).blob();im.id=im.id||uid();await dbPut(im.id,b);im.src=URL.createObjectURL(b);changed=true}catch(e){}}}}if(changed){localStorage.setItem('vocSlidesV41',JSON.stringify(cleanSlides()));try{localStorage.removeItem('vocSlidesV39')}catch(e){}}}

const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defaults=()=>({img:'',images:[],imageX:50,imageY:50,imageZoom:100,fade:68,fadeDir:'left',titleSize:54,bodySize:20,imageMode:'editorial',titleColor:null,bodyColor:null,titleX:5,titleY:31,titleW:49,bodyX:5,bodyY:51,bodyW:49});
const norm=s=>{s={...defaults(),...s};if((!s.images||!s.images.length)&&s.img)s.images=[{src:s.img,x:50,y:50,w:100,h:100,zoom:s.imageZoom||100,kind:'background'}];s.images=(s.images||[]).map((im,i)=>({src:im.src||'',x:im.x??(i?68:50),y:im.y??50,w:im.w??(i?30:100),h:im.h??(i?45:100),zoom:im.zoom||100,kind:im.kind||(i?'floating':'background')}));s.img=s.images[0]?.src||'';if(!s.titleColor)s.titleColor=s.images.length?'#ffffff':'#17374e';if(!s.bodyColor)s.bodyColor=s.images.length?'#ffffff':'#243746';return s};
function scheduleSave(){clearTimeout(saveTimer);setSaveState('กำลังบันทึก…');saveTimer=setTimeout(()=>{try{localStorage.setItem('vocSlidesV41',JSON.stringify(cleanSlides()));localStorage.setItem('vocSlideThemeV41',theme);setSaveState('บันทึกแล้ว ✓')}catch(e){setSaveState('บันทึกไม่สำเร็จ');}},220)}
function setSaveState(t){const e=$('ssSaveState');if(e)e.textContent=t}

function seed(){
 const subject=$('subject')?.value||'รายวิชาอาชีวศึกษา',topic=$('topic')?.value||'หัวข้อการเรียนรู้',code=$('code')?.value||'',level=$('level')?.value||'',school=$('school')?.value||'วิทยาลัยเทคนิคปากช่อง';
 slides=[
  {t:topic,k:`${subject}${code?' • '+code:''}`,b:`${level||'ผู้เรียนอาชีวศึกษา'}\nเรียนรู้ เข้าใจง่าย ฝึกปฏิบัติได้จริง`,type:'cover',...defaults()},
  {t:'เป้าหมายการเรียนรู้',k:'LEARNING OBJECTIVES',b:`อธิบายหลักการสำคัญของ ${topic} ได้\nเชื่อมโยงองค์ประกอบและหน้าที่ได้\nประยุกต์ใช้กับงานอาชีพได้อย่างเหมาะสม`,type:'bullets',...defaults()},
  {t:'ภาพรวมของบทเรียน',k:'BIG PICTURE',b:`มอง ${topic} จากภาพรวมก่อนลงรายละเอียด เพื่อเห็นความสัมพันธ์ระหว่างหลักการ องค์ประกอบ การทำงาน และการนำไปใช้จริง`,type:'visual',...defaults()},
  {t:'หลักการสำคัญ',k:'CORE CONCEPT',b:`ความหมายและพื้นฐาน\nองค์ประกอบที่เกี่ยวข้อง\nความสัมพันธ์ของแต่ละส่วน\nการตรวจสอบผลตามหลักวิชาชีพ`,type:'bullets',...defaults()},
  {t:'องค์ประกอบและหน้าที่',k:'COMPONENTS',b:`ส่วนที่ 1 • หน้าที่หลัก\nส่วนที่ 2 • การเชื่อมโยง\nส่วนที่ 3 • การควบคุม\nส่วนที่ 4 • ความปลอดภัย`,type:'cards',...defaults()},
  {t:'ตัวอย่างในงานจริง',k:'APPLICATION',b:`สังเกตการใช้งานจริงของ ${topic}\nระบุอุปกรณ์หรือข้อมูลที่เกี่ยวข้อง\nอธิบายเหตุผลของการเลือกใช้`,type:'visual',...defaults()},
  {t:'กิจกรรม/แบบฝึกคิด',k:'ACTIVITY',b:`ให้ผู้เรียนอธิบายหลักการด้วยภาษาของตนเอง\nยกตัวอย่างการใช้งานจริง 1 กรณี\nสรุปข้อควรระวังในการทำงาน`,type:'bullets',...defaults()},
  {t:'สรุปท้ายบท',k:'RECAP',b:`เข้าใจหลักการ • เห็นความสัมพันธ์ • นำไปใช้ได้ • ตรวจสอบอย่างปลอดภัย`,type:'visual',...defaults()}
 ];
}
function gradient(s){
 const a=Math.max(0,Math.min(100,Number(s.fade??62)))/100;
 const stop=Math.round(48+(a*24));
 const dir=s.fadeDir||'left';
 if(dir==='right')return `linear-gradient(270deg,rgba(4,20,34,.94) 0%,rgba(4,20,34,.78) 34%,rgba(4,20,34,.18) ${stop}%,rgba(4,20,34,0) 100%)`;
 if(dir==='top')return `linear-gradient(180deg,rgba(4,20,34,.92) 0%,rgba(4,20,34,.60) 38%,rgba(4,20,34,0) 100%)`;
 if(dir==='bottom')return `linear-gradient(0deg,rgba(4,20,34,.92) 0%,rgba(4,20,34,.60) 38%,rgba(4,20,34,0) 100%)`;
 return `linear-gradient(90deg,rgba(4,20,34,.96) 0%,rgba(4,20,34,.80) 36%,rgba(4,20,34,.18) ${stop}%,rgba(4,20,34,0) 100%)`;
}
function placeholder(topic){return `<div class="ss-placeholder"><div class="ss-placeholder-icon">▧</div><b>เพิ่มภาพประกอบ</b><span>อัปโหลด • ค้น Google • สร้างด้วย AI</span><small>${esc(topic)}</small></div>`}
function slideHTML(s,i){
 s=norm(s);const lines=String(s.b||'').split('\n').filter(Boolean);let body='';
 if(s.type==='cards')body=`<div class="cardgrid">${lines.map((x,j)=>`<div class="card"><b>${String(j+1).padStart(2,'0')}</b><p>${esc(x)}</p></div>`).join('')}</div>`;
 else if(s.type==='bullets')body=`<ul>${lines.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;else body=`<p>${esc(s.b)}</p>`;
 const ims=s.images||[],hasImg=ims.length>0,bg=ims[0];
 const bgHtml=bg?`<div class="ss-bg" style="background-image:url('${bg.src}');background-position:${bg.x}% ${bg.y}%;background-size:${bg.zoom||100}% auto"></div><div class="ss-fade" style="background:${gradient(s)}"></div>`:'';
 const floating=ims.slice(1).map((im,j)=>`<div class="ss-layer ${selectedLayer===j+1?'selected':''}" data-layer="${j+1}" style="left:${im.x}%;top:${im.y}%;width:${im.w}%;height:${im.h}%;transform:translate(-50%,-50%)"><img src="${im.src}" style="transform:scale(${(im.zoom||100)/100})"><span>${j+2}</span></div>`).join('');
 return `<div class="slide ${s.type==='cover'?'cover':''} ${hasImg?'has-image':'no-image'} image-${s.imageMode||'editorial'}" data-theme="${theme}">${bgHtml}${floating}
   <div class="ss-slide-brand"><img src="./pic-logo.png" alt="logo"><div><b>${esc($('school')?.value||'วิทยาลัยเทคนิคปากช่อง')}</b><span>PAKCHONG TECHNICAL COLLEGE</span></div></div>
   <div class="ss-text-layer ss-title-layer" data-text-layer="title" style="left:${s.titleX??5}%;top:${s.titleY??31}%;width:${s.titleW??49}%;color:${s.titleColor||'#fff'}"><div class="kicker">${esc(s.k)}</div><div class="accent"></div><h${s.type==='cover'?1:2} style="font-size:${Number(s.titleSize||54)}px">${esc(s.t)}</h${s.type==='cover'?1:2}></div><div class="ss-text-layer ss-body-layer" data-text-layer="body" style="left:${s.bodyX??5}%;top:${s.bodyY??51}%;width:${s.bodyW??49}%;color:${s.bodyColor||'#fff'};font-size:${Number(s.bodySize||20)}px"><div class="ss-bodycopy">${body}</div></div>
   <div class="visual" data-upload-zone="1" title="คลิกเพื่อใส่รูป">${hasImg?'':placeholder(s.t)}</div>
   <div class="ss-foot">เรียนรู้จริง • ฝึกปฏิบัติจริง • ต่อยอดสู่อาชีพ</div><span class="num">${String(i+1).padStart(2,'0')}</span></div>`;
}
function save(){
 const s=slides[cur];if(!s)return;if($('sstitle'))s.t=$('sstitle').value||s.t;if($('ssbodytext'))s.b=$('ssbodytext').value||s.b;if($('sstype'))s.type=$('sstype').value||s.type;
 if($('ssfade'))s.fade=Number($('ssfade').value||62);if($('ssfadeDir'))s.fadeDir=$('ssfadeDir').value||'left';if($('sstitleSize'))s.titleSize=Number($('sstitleSize').value||54);if($('ssbodySize'))s.bodySize=Number($('ssbodySize').value||20);if($('ssimageMode'))s.imageMode=$('ssimageMode').value||'editorial';scheduleSave();
}
function renderPreview(){const s=slides[cur];if(!s)return;$('sscanvas').innerHTML=slideHTML(s,cur);bindCanvasLayers();}
function renderThumbs(){ $('ssthumbs').innerHTML=slides.map((x,i)=>{x=norm(x);return `<div class="ssthumb-wrap ${i===cur?'active':''}" draggable="true" data-i="${i}"><button class="ssthumb ${i===cur?'active':''}" data-i="${i}"><div class="mini">${x.images[0]?.src?`<img src="${x.images[0].src}" alt="">`:'<span>SLIDE</span>'}</div><div><b>${i+1}. ${esc(x.t||'สไลด์ว่าง')}</b><span>${esc(x.k||'')}</span></div></button><div class="ss-thumb-move"><button data-up="${i}" ${i===0?'disabled':''}>↑</button><button data-down="${i}" ${i===slides.length-1?'disabled':''}>↓</button></div></div>`}).join('');document.querySelectorAll('.ssthumb').forEach(x=>x.onclick=()=>{cur=+x.dataset.i;selectedLayer=0;render()});document.querySelectorAll('[data-up]').forEach(b=>b.onclick=e=>{e.stopPropagation();moveSlide(+b.dataset.up,+b.dataset.up-1)});document.querySelectorAll('[data-down]').forEach(b=>b.onclick=e=>{e.stopPropagation();moveSlide(+b.dataset.down,+b.dataset.down+1)});document.querySelectorAll('.ssthumb-wrap').forEach(w=>{w.ondragstart=e=>{e.dataTransfer.setData('text/plain',w.dataset.i);w.classList.add('dragging')};w.ondragend=()=>w.classList.remove('dragging');w.ondragover=e=>e.preventDefault();w.ondrop=e=>{e.preventDefault();moveSlide(+e.dataTransfer.getData('text/plain'),+w.dataset.i)}})}
function moveSlide(from,to){if(from===to||to<0||to>=slides.length)return;const [x]=slides.splice(from,1);slides.splice(to,0,x);cur=to;scheduleSave();render()}
function render(){let s=slides[cur]=norm(slides[cur]);renderPreview();renderThumbs();if($('sscount'))$('sscount').textContent=slides.length+' หน้า';$('sstitle').value=s.t;$('ssbodytext').value=s.b;$('sstype').value=s.type;$('sstheme').value=theme;$('ssfade').value=s.fade??68;$('ssfadeValue').textContent=(s.fade??68)+'%';$('ssfadeDir').value=s.fadeDir||'left';
 if($('sstitleSize')){$('sstitleSize').value=s.titleSize||54;$('sstitleSizeValue').textContent=(s.titleSize||54)+' px'}if($('ssbodySize')){$('ssbodySize').value=s.bodySize||20;$('ssbodySizeValue').textContent=(s.bodySize||20)+' px'}if($('sstitleColor'))$('sstitleColor').value=s.titleColor||'#ffffff';if($('ssbodyColor'))$('ssbodyColor').value=s.bodyColor||'#ffffff';if($('ssmoveTo')){$('ssmoveTo').innerHTML=slides.map((_,i)=>`<option value="${i}" ${i===cur?'selected':''}>หน้า ${i+1}</option>`).join('')}if($('ssimageMode'))$('ssimageMode').value=s.imageMode||'editorial';renderLayerControls();}
function bindCanvasLayers(){const zone=$('sscanvas').querySelector('[data-upload-zone]');if(zone)zone.onclick=()=>{$('ssimage').click()};document.querySelectorAll('#sscanvas .ss-layer').forEach(el=>{el.onclick=e=>{e.stopPropagation();selectedLayer=+el.dataset.layer;renderLayerControls();document.querySelectorAll('#sscanvas .ss-layer').forEach(x=>x.classList.toggle('selected',x===el))};bindLayerDrag(el,+el.dataset.layer)});}
function bindLayerDrag(el,idx){let active=false,lx=0,ly=0;el.onpointerdown=e=>{active=true;selectedLayer=idx;lx=e.clientX;ly=e.clientY;el.setPointerCapture?.(e.pointerId);e.preventDefault()};el.onpointermove=e=>{if(!active)return;const r=$('sscanvas').getBoundingClientRect(),im=slides[cur].images[idx];im.x=Math.max(0,Math.min(100,im.x+(e.clientX-lx)/r.width*100));im.y=Math.max(0,Math.min(100,im.y+(e.clientY-ly)/r.height*100));lx=e.clientX;ly=e.clientY;el.style.left=im.x+'%';el.style.top=im.y+'%';e.preventDefault()};el.onpointerup=()=>{active=false;scheduleSave();renderLayerControls()}}
function renderLayerControls(){const s=slides[cur]=norm(slides[cur]),ims=s.images;const state=$('ssimgState');if(state)state.textContent=ims.length?`มี ${ims.length} รูปในสไลด์ • แตะรูปเพื่อเลือกและลาก`:'ยังไม่มีภาพ • กดเพิ่มภาพได้หลายรูป';const list=$('ssLayerList');if(list)list.innerHTML=ims.length?ims.map((im,i)=>`<button class="ss-layer-item ${i===selectedLayer?'active':''}" data-li="${i}"><img src="${im.src}"><span>${i===0?'พื้นหลัง':'รูป '+(i+1)}</span></button>`).join(''):'<div class="ssnotice">ยังไม่มีรูป</div>';document.querySelectorAll('[data-li]').forEach(b=>b.onclick=()=>{selectedLayer=+b.dataset.li;renderLayerControls();renderPreview()});const im=ims[selectedLayer];if($('sszoom')){$('sszoom').disabled=!im;$('sszoom').value=im?.zoom||100;$('sszoomValue').textContent=(im?.zoom||100)+'%'}if($('ssposx')){$('ssposx').disabled=!im;$('ssposx').value=im?.x??50;$('ssposxValue').textContent=Math.round(im?.x??50)+'%'}if($('ssposy')){$('ssposy').disabled=!im;$('ssposy').value=im?.y??50;$('ssposyValue').textContent=Math.round(im?.y??50)+'%'}if($('sswidth')){$('sswidth').disabled=!im||selectedLayer===0;$('sswidth').value=im?.w||30;$('sswidthValue').textContent=Math.round(im?.w||30)+'%'} }

function setImagePreset(x,y){const im=slides[cur].images?.[selectedLayer];if(!im)return;im.x=x;im.y=y;scheduleSave();renderPreview();renderLayerControls()}

async function open(){
 if(!slides.length){try{slides=JSON.parse(localStorage.getItem('vocSlidesV41')||localStorage.getItem('vocSlidesV40')||localStorage.getItem('vocSlidesV39')||localStorage.getItem('vocSlidesV36')||localStorage.getItem('vocSlidesV35')||'[]')}catch{};theme=localStorage.getItem('vocSlideThemeV41')||localStorage.getItem('vocSlideThemeV40')||localStorage.getItem('vocSlideThemeV39')||localStorage.getItem('vocSlideThemeV36')||localStorage.getItem('vocSlideThemeV35')||'blue';if(!slides.length)seed();slides=slides.map(norm);await hydrateImages().catch(()=>{});await migrateDataImages().catch(()=>{});}
 $('slideStudio').classList.add('open');render();refreshStorageInfo();
}
function close(){save();$('slideStudio').classList.remove('open');if(window.setTeacherMode)setTimeout(()=>window.setTeacherMode('worksheet'),10)}
// Public hooks used by the main teacher dashboard.
window.openSlideStudio=open;
window.closeSlideStudio=close;
function add(){save();slides.splice(cur+1,0,{t:'',k:'',b:'',type:'visual',...defaults()});cur++;scheduleSave();render()}
function del(){if(slides.length<=1)return;slides.splice(cur,1);cur=Math.max(0,cur-1);render()}
function duplicate(){save();slides.splice(cur+1,0,JSON.parse(JSON.stringify(slides[cur])));cur++;render()}
function fileToSlide(file){if(!file)return;setSaveState('กำลังเพิ่มรูป…');const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=1600,sc=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*sc);c.height=Math.round(img.height*sc);c.getContext('2d').drawImage(img,0,0,c.width,c.height);c.toBlob(async blob=>{if(!blob)return;const id=uid();try{await dbPut(id,blob);const src=URL.createObjectURL(blob),s=slides[cur]=norm(slides[cur]);if(!s.images.length){s.images.push({id,src,x:50,y:50,w:100,h:100,zoom:100,kind:'background'});selectedLayer=0}else{s.images.push({id,src,x:70,y:53,w:30,h:44,zoom:100,kind:'floating'});selectedLayer=s.images.length-1}s.img=s.images[0]?.src||'';scheduleSave();render();refreshStorageInfo()}catch(e){setSaveState('เพิ่มรูปไม่สำเร็จ')}},'image/jpeg',.80)};img.src=r.result};r.readAsDataURL(file)}
function googleImages(){const s=slides[cur],q=encodeURIComponent(`${$('subject')?.value||''} ${$('topic')?.value||''} ${s.t||''} technical education illustration`);window.open(`https://www.google.com/search?tbm=isch&q=${q}`,'_blank','noopener')}
function aiImage(){
 const s=slides[cur],sub=$('subject')?.value||'รายวิชาอาชีวศึกษา',top=$('topic')?.value||s.t,style=theme==='dark'?'cinematic dark technical':theme==='warm'?'warm educational editorial':'professional vocational education editorial';
 const prompt=`สร้างภาพประกอบสไลด์การสอนแบบ ${style} อัตราส่วน 16:9 สำหรับวิชา ${sub} เรื่อง ${top} หัวข้อสไลด์ “${s.t}” ให้ภาพดูสมจริง มืออาชีพ เหมาะกับนักเรียนอาชีวศึกษา ไม่มีข้อความบนภาพ เว้นพื้นที่ด้านซ้ายสำหรับวางหัวข้อและคำอธิบาย`;
 navigator.clipboard?.writeText(prompt).catch(()=>{});alert('คัดลอกคำสั่งสร้างภาพแล้ว ระบบจะเปิด ChatGPT ให้สร้างภาพ จากนั้นบันทึกภาพแล้วกลับมากด “อัปโหลดภาพ”');window.open('https://chatgpt.com/','_blank','noopener');
}
function splitPoints(text){return String(text||'').replace(/\[[^\]]*\]/g,' ').split(/(?<=[.!?。]|[ครับค่ะ])\s+|\n+/).map(x=>x.trim().replace(/^[-•\d.)\s]+/,'' )).filter(x=>x.length>=28&&x.length<=360).filter((x,i,a)=>a.findIndex(y=>y.slice(0,55)===x.slice(0,55))===i).slice(0,30)}
function renderResearch(msg){let box=$('ssresults');if(!box)return;if(msg){box.innerHTML=`<div class="ssnotice">${esc(msg)}</div>`;return}box.innerHTML=researchPoints.length?researchPoints.map((x,i)=>`<label class="sspoint"><input type="checkbox" data-rp="${i}" checked><span>${esc(x)}</span></label>`).join(''):`<div class="ssnotice">ยังไม่มีเนื้อหา — วางข้อความจาก AI หรือค้นจากเว็บก่อน</div>`;$('sssourceLinks').innerHTML=researchSources.map(x=>`<div>• <a href="${x.url}" target="_blank" rel="noopener">${esc(x.title)}</a></div>`).join('')}
async function wikiSearch(){let q=($('ssquery')?.value||`${$('subject')?.value||''} ${$('topic')?.value||''}`).trim();if(!q)return;renderResearch('กำลังค้นหาเนื้อหาอ้างอิง…');researchPoints=[];researchSources=[];try{let api='https://th.wikipedia.org/w/api.php?origin=*&action=query&generator=search&gsrsearch='+encodeURIComponent(q)+'&gsrlimit=5&prop=extracts|info&exintro=1&explaintext=1&inprop=url&format=json';let r=await fetch(api);if(!r.ok)throw new Error();let j=await r.json();let pages=Object.values(j.query?.pages||{});pages.forEach(pg=>{researchPoints.push(...splitPoints(pg.extract));researchSources.push({title:pg.title,url:pg.fullurl})});researchPoints=[...new Set(researchPoints)].slice(0,24);renderResearch(researchPoints.length?'':`ไม่พบเนื้อหาสำหรับ “${q}”`)}catch(e){renderResearch('ค้นหาออนไลน์ไม่สำเร็จ ลองใช้ Google หรือวางข้อความจาก AI แทน')}}
function usePasted(){let pts=splitPoints($('sspasted')?.value||'');if(!pts.length){renderResearch('ยังไม่พบประเด็นที่ใช้ได้ ลองวางเนื้อหาให้ยาวขึ้น');return}researchPoints=pts;researchSources=[{title:'เนื้อหาที่ครูวางเอง',url:'#'}];renderResearch()}
function selectedPoints(){return [...document.querySelectorAll('[data-rp]:checked')].map(x=>researchPoints[+x.dataset.rp]).filter(Boolean)}
function buildFromResearch(){let pts=selectedPoints();if(!pts.length){alert('กรุณาเลือกอย่างน้อย 1 ประเด็น');return}let subject=$('subject')?.value||'รายวิชาอาชีวศึกษา',topic=$('topic')?.value||'หัวข้อการเรียนรู้',code=$('code')?.value||'',level=$('level')?.value||'';let groups=[];for(let i=0;i<pts.length;i+=3)groups.push(pts.slice(i,i+3));slides=[{t:topic,k:`${subject}${code?' • '+code:''}`,b:`${level||'ผู้เรียนอาชีวศึกษา'}\nสร้างจากเนื้อหาที่ครูตรวจเลือก`,type:'cover',...defaults()},...groups.slice(0,9).map((g,i)=>({t:i===0?'ความรู้พื้นฐาน':`${topic} • ${i+1}`,k:'CONTENT',b:g.join('\n'),type:g.length>1?'bullets':'visual',...defaults()})),{t:'สรุปท้ายบท',k:'RECAP',b:pts.slice(0,5).map(x=>x.length>110?x.slice(0,107)+'…':x).join('\n'),type:'bullets',...defaults()}];cur=0;render()}
function ppt(){
 save();if(!window.PptxGenJS){alert('ตัวส่งออก PowerPoint ยังโหลดไม่เสร็จ');return}let p=new PptxGenJS();p.layout='LAYOUT_WIDE';p.author='Vocational Learning Studio';
 slides.forEach((s,i)=>{let sl=p.addSlide();sl.background={color:theme==='dark'?'0B1728':theme==='warm'?'FFF6E9':'F7FBFF'};if(s.img){try{sl.addImage({data:s.img,x:0,y:0,w:13.333,h:7.5});}catch(e){}sl.addShape(p.ShapeType.rect,{x:0,y:0,w:8.0,h:7.5,fill:{color:'061522',transparency:18},line:{color:'061522',transparency:100}})};(s.images||[]).slice(1).forEach(im=>{try{sl.addImage({data:im.src,x:(im.x-im.w/2)*13.333/100,y:(im.y-im.h/2)*7.5/100,w:im.w*13.333/100,h:im.h*7.5/100});}catch(e){}})
 sl.addImage({path:'./pic-logo.png',x:.55,y:.45,w:.55,h:.55});sl.addText($('school')?.value||'วิทยาลัยเทคนิคปากช่อง',{x:1.18,y:.46,w:4.2,h:.26,fontFace:'Sarabun',fontSize:10,bold:true,color:s.img?'FFFFFF':'17324A'});sl.addText(s.k,{x:.72,y:1.48,w:5.8,h:.32,fontFace:'Sarabun',fontSize:11,bold:true,color:'F0A941'});sl.addText(s.t,{x:(s.titleX??5)*13.333/100,y:(s.titleY??31)*7.5/100,w:(s.titleW??49)*13.333/100,h:1.18,fontFace:'Sarabun',fontSize:Math.max(20,Math.min(38,Number(s.titleSize||54)*.58)),bold:true,color:(s.titleColor||'#FFFFFF').replace('#',''),fit:'shrink'});let arr=String(s.b||'').split('\n').filter(Boolean);if(s.type==='bullets'||s.type==='cards')sl.addText(arr.map(v=>({text:v,options:{bullet:{indent:14}}})),{x:(s.bodyX??5)*13.333/100,y:(s.bodyY??51)*7.5/100,w:(s.bodyW??49)*13.333/100,h:2.55,fontFace:'Sarabun',fontSize:Math.max(10,Math.min(24,Number(s.bodySize||20)*.8)),color:(s.bodyColor||'#FFFFFF').replace('#',''),fit:'shrink',breakLine:true,paraSpaceAfterPt:8});else sl.addText(s.b,{x:(s.bodyX??5)*13.333/100,y:(s.bodyY??51)*7.5/100,w:(s.bodyW??49)*13.333/100,h:2.3,fontFace:'Sarabun',fontSize:Math.max(10,Math.min(25,Number(s.bodySize||20)*.85)),color:(s.bodyColor||'#FFFFFF').replace('#',''),fit:'shrink'});sl.addText(String(i+1).padStart(2,'0'),{x:12.15,y:6.85,w:.5,h:.25,fontSize:10,color:'AAB8C2'});});
 p.writeFile({fileName:`${($('subject')?.value||'บทเรียน').replace(/[\\/:*?"<>|]/g,'-')}-${($('topic')?.value||'สไลด์').replace(/[\\/:*?"<>|]/g,'-')}.pptx`})
}
async function pdf(){save();if(!window.html2pdf){alert('ระบบ PDF ยังโหลดไม่เสร็จ กรุณาลองอีกครั้ง');return}const btn=$('sspdf');btn.disabled=true;const prog=document.createElement('div');prog.className='ss-export-progress';prog.innerHTML='<div><b>กำลังเตรียม PDF…</b><span>กรุณารอสักครู่</span></div>';document.body.appendChild(prog);let host=document.createElement('div');host.id='sspdfHost';host.style.cssText='position:fixed;left:-20000px;top:0;width:1280px;background:#fff;z-index:-1';slides.forEach((sl,i)=>{let pg=document.createElement('div');pg.className='sspdfpage';pg.style.cssText='width:1280px;height:720px;overflow:hidden;page-break-after:always;position:relative;background:#fff';pg.innerHTML=`<div class="sscanvas" style="width:1280px;height:720px;border-radius:0;box-shadow:none">${slideHTML(sl,i)}</div>`;host.appendChild(pg)});document.body.appendChild(host);try{await new Promise(r=>setTimeout(r,350));prog.querySelector('b').textContent=`กำลังสร้าง PDF ${slides.length} หน้า…`;await html2pdf().set({margin:0,filename:`สไลด์-${$('subject')?.value||'บทเรียน'}.pdf`,image:{type:'jpeg',quality:.9},html2canvas:{scale:1,useCORS:true,backgroundColor:'#ffffff',logging:false},jsPDF:{unit:'px',format:[1280,720],orientation:'landscape'},pagebreak:{mode:['css','legacy']}}).from(host).save();prog.querySelector('b').textContent='สร้าง PDF สำเร็จ ✓';await new Promise(r=>setTimeout(r,700))}catch(e){console.error(e);alert('สร้าง PDF ไม่สำเร็จ กรุณาลองลดจำนวนภาพหรือใช้ปุ่ม PowerPoint')}finally{host.remove();prog.remove();btn.disabled=false}}

function bytesText(n){n=Number(n||0);if(n<1024)return n+' B';if(n<1024*1024)return (n/1024).toFixed(1)+' KB';if(n<1024*1024*1024)return (n/1024/1024).toFixed(1)+' MB';return (n/1024/1024/1024).toFixed(2)+' GB'}
function blobToDataURL(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(blob)})}
function dataURLToBlob(data){const [head,body]=String(data||'').split(',');const mime=(head.match(/data:([^;]+)/)||[])[1]||'image/jpeg';const bin=atob(body||'');const a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return new Blob([a],{type:mime})}
async function currentProjectBytes(){let total=0,seen=new Set();for(const sl of slides){for(const im of (sl.images||[])){if(!im.id||seen.has(im.id))continue;seen.add(im.id);const b=await dbGet(im.id).catch(()=>null);if(b)total+=b.size||0}}return total}
async function refreshStorageInfo(){const el=$('ssStorageInfo');if(!el)return;el.textContent='กำลังตรวจพื้นที่…';try{const project=await currentProjectBytes();const est=await (navigator.storage?.estimate?.()||Promise.resolve({}));const usage=est.usage||0,quota=est.quota||0;el.innerHTML=`<b>โปรเจกต์นี้ ${bytesText(project)}</b><span>ข้อมูลเว็บไซต์ใช้ ${bytesText(usage)}${quota?' / '+bytesText(quota):''}</span><small>รูปถูกบีบอัดและเก็บในเครื่องนี้ ไม่ได้อัปโหลดขึ้น GitHub</small>`}catch(e){el.textContent='ไม่สามารถอ่านข้อมูลพื้นที่เก็บข้อมูลได้'}}
async function exportProject(){save();setSaveState('กำลังเตรียมไฟล์โปรเจกต์…');const meta={school:$('school')?.value||'',subject:$('subject')?.value||'',code:$('code')?.value||'',level:$('level')?.value||'',topic:$('topic')?.value||''};const outSlides=[];for(const s0 of slides){const s={...s0,images:[]};delete s.img;for(const im0 of (s0.images||[])){const im={...im0};delete im.src;if(im0.id){const b=await dbGet(im0.id).catch(()=>null);if(b)im.data=await blobToDataURL(b)}s.images.push(im)}outSlides.push(s)}const payload={app:'Vocational Learning Studio',version:41,savedAt:new Date().toISOString(),theme,meta,slides:outSlides};const blob=new Blob([JSON.stringify(payload)],{type:'application/json'});const a=document.createElement('a');const safe=(meta.subject||meta.topic||'บทเรียน').replace(/[\\/:*?"<>|]/g,'-');a.href=URL.createObjectURL(blob);a.download=safe+'.vlsproject';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1200);setSaveState('บันทึกไฟล์โปรเจกต์แล้ว ✓')}
async function importProject(file){if(!file)return;setSaveState('กำลังเปิดโปรเจกต์…');try{const obj=JSON.parse(await file.text());if(!obj||!Array.isArray(obj.slides))throw new Error('bad project');const loaded=[];for(const s0 of obj.slides){const s={...s0,images:[]};for(const im0 of (s0.images||[])){const im={...im0};delete im.data;delete im.src;if(im0.data){const blob=dataURLToBlob(im0.data),id=uid();await dbPut(id,blob);im.id=id;im.src=URL.createObjectURL(blob)}else if(im.id){const b=await dbGet(im.id).catch(()=>null);if(b)im.src=URL.createObjectURL(b)}s.images.push(im)}s.img=s.images[0]?.src||'';loaded.push(norm(s))}slides=loaded.length?loaded:[{t:'',k:'',b:'',type:'visual',...defaults()}];theme=obj.theme||'blue';cur=0;selectedLayer=0;for(const [id,val] of Object.entries(obj.meta||{})){if($(id))$(id).value=val}localStorage.setItem('vocSlidesV41',JSON.stringify(cleanSlides()));localStorage.setItem('vocSlideThemeV41',theme);render();refreshStorageInfo();setSaveState('เปิดโปรเจกต์แล้ว ✓')}catch(e){console.error(e);alert('เปิดไฟล์โปรเจกต์ไม่สำเร็จ กรุณาเลือกไฟล์ .vlsproject ที่สร้างจากระบบนี้');setSaveState('เปิดโปรเจกต์ไม่สำเร็จ')}}
async function clearProject(){if(!confirm('ล้างโปรเจกต์สไลด์ปัจจุบันออกจากเครื่องนี้?\nควรบันทึกไฟล์โปรเจกต์ก่อนหากต้องการเก็บงานไว้'))return;const ids=[];slides.forEach(s=>(s.images||[]).forEach(im=>im.id&&ids.push(im.id)));for(const id of ids)await dbDel(id);slides=[];seed();cur=0;selectedLayer=0;localStorage.removeItem('vocSlidesV41');scheduleSave();render();refreshStorageInfo()}

let presentIndex=0,presentKeyHandler=null;
function presentRender(){const stage=$('ssPresentStage');if(!stage)return;stage.innerHTML=`<div class="ssp-frame">${slideHTML(slides[presentIndex],presentIndex)}</div>`;const n=$('ssPresentCount');if(n)n.textContent=`${presentIndex+1} / ${slides.length}`}
function presentMove(delta){presentIndex=Math.max(0,Math.min(slides.length-1,presentIndex+delta));presentRender()}
function closePresent(){const el=$('ssPresent');if(el)el.remove();if(presentKeyHandler){document.removeEventListener('keydown',presentKeyHandler);presentKeyHandler=null}}
function present(){save();presentIndex=cur;document.body.insertAdjacentHTML('beforeend',`<div id="ssPresent" class="ss-present"><div id="ssPresentStage" class="ss-present-stage"></div><div class="ss-present-top"><span id="ssPresentCount"></span><button id="ssPresentFull">เต็มจอ</button><button id="ssPresentClose">ปิด</button></div><button class="ss-present-nav prev" id="ssPresentPrev">‹</button><button class="ss-present-nav next" id="ssPresentNext">›</button></div>`);presentRender();$('ssPresentPrev').onclick=()=>presentMove(-1);$('ssPresentNext').onclick=()=>presentMove(1);$('ssPresentClose').onclick=closePresent;$('ssPresentFull').onclick=()=>$('ssPresent')?.requestFullscreen?.();$('ssPresentStage').onclick=e=>presentMove(e.clientX<innerWidth/2?-1:1);presentKeyHandler=e=>{if(e.key==='Escape')closePresent();else if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();presentMove(1)}else if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();presentMove(-1)}};document.addEventListener('keydown',presentKeyHandler)}

function lessonModal(){save();const old=$('ssLessonModal');if(old)old.remove();document.body.insertAdjacentHTML('beforeend',`<div class="ss-modal" id="ssLessonModal"><div class="ss-modal-card"><div class="ss-modal-head"><div><b>ใช้บทเรียนนี้ต่อ</b><span>เลือกสไลด์ แล้วให้ AI สร้างใบงานหรือข้อสอบจากเนื้อหาที่สอนจริง</span></div><button id="ssLessonClose">×</button></div><div class="ss-lesson-grid"><label>นำไปสร้าง<select id="ssLessonTarget"><option value="worksheet">ใบงาน</option><option value="exam">ข้อสอบออนไลน์</option></select></label><label>จำนวนข้อ<input id="ssLessonCount" type="number" min="1" max="60" value="10"></label><label>รูปแบบ<select id="ssLessonKind"><option value="ปรนัย 4 ตัวเลือก ก ข ค ง">ปรนัย ก ข ค ง</option><option value="ถาม–ตอบ">ถาม–ตอบ</option><option value="แบบผสม ปรนัยและถาม–ตอบ">แบบผสม</option><option value="คำนวณอย่างง่าย">คำนวณ</option></select></label></div><div class="ss-lesson-select-head"><b>เนื้อหาที่ส่งให้ AI</b><span><button id="ssLessonAll">เลือกทั้งหมด</button><button id="ssLessonNone">ไม่เลือก</button></span></div><div class="ss-lesson-slides">${slides.map((s,i)=>`<label><input type="checkbox" data-lesson-slide="${i}" ${i===0?'':'checked'}><span><b>${i+1}. ${esc(s.t||'สไลด์ว่าง')}</b><small>${esc(String(s.b||'').slice(0,90))}</small></span></label>`).join('')}</div><div class="ss-lesson-actions"><button class="ssbtn" id="ssLessonReceiver">ไปช่องวางผล AI</button><button class="ssbtn primary" id="ssLessonAI">เปิด AI พร้อม Prompt</button></div><p class="ss-lesson-note">ระบบจะสั่ง AI ให้ใช้เฉพาะข้อมูลจากสไลด์ที่เลือก ไม่ดึงข้อความหน้าปกหรือสไลด์ที่ไม่ต้องการโดยอัตโนมัติ</p></div></div>`);$('ssLessonClose').onclick=()=>$('ssLessonModal').remove();$('ssLessonAll').onclick=()=>document.querySelectorAll('[data-lesson-slide]').forEach(x=>x.checked=true);$('ssLessonNone').onclick=()=>document.querySelectorAll('[data-lesson-slide]').forEach(x=>x.checked=false);$('ssLessonAI').onclick=()=>{const prompt=lessonPrompt();if(!prompt)return;navigator.clipboard?.writeText(prompt).catch(()=>{});window.open('https://chatgpt.com/?q='+encodeURIComponent(prompt),'_blank','noopener')};$('ssLessonReceiver').onclick=()=>goLessonReceiver()}
function lessonSelected(){return [...document.querySelectorAll('[data-lesson-slide]:checked')].map(x=>slides[+x.dataset.lessonSlide]).filter(Boolean)}
function lessonPrompt(){const chosen=lessonSelected();if(!chosen.length){alert('เลือกอย่างน้อย 1 สไลด์');return ''}const target=$('ssLessonTarget').value,count=Math.max(1,Math.min(60,+$('ssLessonCount').value||10)),kind=$('ssLessonKind').value,subject=$('subject')?.value||'รายวิชาอาชีวศึกษา',topic=$('topic')?.value||'บทเรียน',level=$('level')?.value||'อาชีวศึกษา';const content=chosen.map((s,i)=>`[${i+1}] ${s.t}\n${s.b}`).join('\n\n');let format=kind.startsWith('ปรนัย')?'ทุกข้อจัดรูปแบบ:\n1. คำถาม\nก. ตัวเลือก\nข. ตัวเลือก\nค. ตัวเลือก\nง. ตัวเลือก\nเฉลย: ก':kind==='ถาม–ตอบ'?'ทุกข้อจัดรูปแบบ:\n1. คำถาม\nคำตอบ: แนวคำตอบสั้น ๆ':'จัดรูปแบบแต่ละข้อให้ชัดเจน โดยข้อปรนัยใช้ ก ข ค ง และระบุเฉลย ส่วนถาม–ตอบใช้ “คำตอบ:”';return `สร้าง${target==='exam'?'ข้อสอบออนไลน์':'ใบงาน'} วิชา “${subject}” เรื่อง “${topic}” ระดับ ${level} จำนวน ${count} ข้อ รูปแบบ ${kind}\n\nกติกาสำคัญ:\n- ใช้เฉพาะข้อมูลจากบทเรียนด้านล่าง ห้ามออกนอกเนื้อหา\n- ภาษาไทยกระชับ ระดับความยากเหมาะกับผู้เรียน\n- หลีกเลี่ยงคำถามกำกวม เช่น “ตามเนื้อหาที่เลือก”\n- ไม่ต้องมีคำอธิบายนอกเหนือจากชุดคำถาม\n\n${format}\n\nเนื้อหาบทเรียน:\n${content}`}
function goLessonReceiver(){const target=$('ssLessonTarget')?.value||'worksheet';$('ssLessonModal')?.remove();close();if(window.setTeacherMode)window.setTeacherMode(target==='exam'?'exam':'worksheet');setTimeout(()=>{if(target==='exam'){const raw=$('onlineAiRaw');if(raw){raw.focus();raw.scrollIntoView({behavior:'smooth',block:'center'})}}else{const d=document.querySelector('.ai-import');if(d)d.open=true;const raw=$('aiRaw');if(raw){raw.focus();raw.scrollIntoView({behavior:'smooth',block:'center'})}}},250)}

document.addEventListener('DOMContentLoaded',()=>{
 document.body.insertAdjacentHTML('beforeend',`<div id="slideStudio">
  <header class="ssbar"><div class="ssbrand"><img src="./pic-logo.png"><div><b>Vocational Learning Studio</b><span>Slide Studio • สื่อการสอน 16:9</span></div></div><div class="sstools"><button class="ssbtn" id="ssadd">＋ เพิ่มสไลด์</button><button class="ssbtn" id="ssdup">ทำสำเนา</button><button class="ssbtn danger" id="ssdel">ลบ</button><button class="ssbtn accent" id="ssuseLesson">ใช้บทเรียนต่อ</button><button class="ssbtn accent" id="sspresent">▶ นำเสนอ</button><button class="ssbtn" id="ssFocus">⛶ ขยายพื้นที่</button><button class="ssbtn" id="ssSaveProject">บันทึกโปรเจกต์</button><button class="ssbtn" id="ssOpenProject">เปิดโปรเจกต์</button><input id="ssProjectFile" type="file" accept=".vlsproject,application/json" hidden><button class="ssbtn" id="sspdf">PDF</button><button class="ssbtn primary" id="ssppt">PowerPoint</button><button class="ssbtn" id="ssclose">ปิด</button></div></header>
  <div class="ssbody">
   <aside class="ssleft"><div class="ssleft-title"><b>รายการสไลด์</b><span id="sscount"></span></div><div id="ssthumbs"></div></aside>
   <main class="sscenter"><div class="sseditbar"><span>สไลด์ปัจจุบัน</span><em id="ssSaveState" class="ss-save-state">พร้อมแก้ไข</em><button id="ssquickUpload">▣ เพิ่มภาพ</button><button id="ssquickGoogle">G ค้น Google</button><button id="ssquickAI">✦ AI สร้างภาพ</button></div><div class="sscanvas" id="sscanvas"></div><div class="sseditpanel"><div><label>หัวข้อหลัก</label><input id="sstitle"></div><div><label>เนื้อหา</label><textarea id="ssbodytext"></textarea></div><div><label>รูปแบบ</label><select id="sstype"><option value="cover">หน้าปก</option><option value="visual">ข้อความ + ภาพ</option><option value="bullets">หัวข้อย่อย</option><option value="cards">การ์ดข้อมูล</option></select></div><div class="ss-font-control"><label>ขนาดหัวข้อ <b id="sstitleSizeValue">54 px</b></label><input id="sstitleSize" type="range" min="28" max="78" value="54"></div><div class="ss-font-control"><label>ขนาดเนื้อหา <b id="ssbodySizeValue">20 px</b></label><input id="ssbodySize" type="range" min="12" max="34" value="20"></div><div class="ss-color-control"><label>สีหัวข้อ</label><input id="sstitleColor" type="color" value="#ffffff"></div><div class="ss-color-control"><label>สีเนื้อหา</label><input id="ssbodyColor" type="color" value="#ffffff"></div><div class="ss-move-control"><label>ย้ายสไลด์ไป</label><select id="ssmoveTo"></select></div><div class="ss-live-note">ลากหัวข้อ/เนื้อหาบนสไลด์เพื่อย้ายตำแหน่ง • บันทึกอัตโนมัติ</div></div></main>
   <aside class="ssright">
    <div class="ss-tabs"><button class="active" data-sstab="image">รูปภาพ</button><button data-sstab="content">เนื้อหา</button><button data-sstab="style">สไตล์</button><button data-sstab="project">โปรเจกต์</button></div>
    <section id="sstab-image" class="sstabpane active"><h3>รูปภาพสไลด์</h3><p class="ssmuted" id="ssimgState"></p><div class="sssourceBtns"><button class="ssaction ai" id="ssaiimage">✦ สร้างภาพด้วย AI</button><button class="ssaction" id="ssgoogleimg">G ค้น Google Images</button><label class="ssaction upload">▣ อัปโหลดเอง<input id="ssimage" type="file" accept="image/*"></label></div><div class="ssnote"><b>ใส่รูปง่าย:</b> ถ้ายังไม่มีภาพ จะเห็นปุ่ม + เพิ่มรูปภาพบนสไลด์ เมื่อใส่แล้วลากภาพด้วยนิ้ว/เมาส์เพื่อจัดตำแหน่งได้</div><div id="ssLayerList" class="ss-layer-list"></div><div class="sscontrol"><label>ความกว้างรูปที่เลือก <b id="sswidthValue">30%</b></label><input id="sswidth" type="range" min="15" max="70" value="30"></div><div class="ss-image-controls"><div class="sscontrol"><label>ซูมภาพ <b id="sszoomValue">100%</b></label><input id="sszoom" type="range" min="100" max="240" value="100"></div><div class="sscontrol"><label>ตำแหน่งแนวนอน <b id="ssposxValue">50%</b></label><input id="ssposx" type="range" min="0" max="100" value="50"></div><div class="sscontrol"><label>ตำแหน่งแนวตั้ง <b id="ssposyValue">50%</b></label><input id="ssposy" type="range" min="0" max="100" value="50"></div><div class="ss-presets"><button data-pos="0,50">ซ้าย</button><button data-pos="50,50">กลาง</button><button data-pos="100,50">ขวา</button><button data-pos="50,0">บน</button><button data-pos="50,100">ล่าง</button></div></div><div class="sscontrol"><label>การวางภาพ</label><select id="ssimageMode"><option value="editorial">Editorial เต็มพื้นหลัง + เฟด</option><option value="split">Split ภาพด้านขวา</option><option value="panel">Panel ภาพในกรอบ</option></select></div><div class="sscontrol"><label>แถบไล่เฟดทับภาพ <b id="ssfadeValue">68%</b></label><input id="ssfade" type="range" min="0" max="100" value="62"></div><div class="sscontrol"><label>ทิศทางเฟด</label><select id="ssfadeDir"><option value="left">ซ้าย → ขวา</option><option value="right">ขวา → ซ้าย</option><option value="top">บน → ล่าง</option><option value="bottom">ล่าง → บน</option></select></div><button class="ssaction danger" id="ssremoveimg">ลบรูปออกจากสไลด์</button></section>
    <section id="sstab-content" class="sstabpane"><h3>หาเนื้อหา</h3><div class="sssourceBtns"><button class="ssaction ai" id="ssai">เปิด AI พร้อมคำสั่ง</button><button class="ssaction" id="ssgoogle">G ค้น Google</button></div><textarea class="sspaste" id="sspasted" placeholder="วางข้อความจาก AI / เอกสาร / เว็บไซต์ตรงนี้"></textarea><div class="ssrow"><button class="sssmall" id="ssusepaste">วิเคราะห์ข้อความ</button><button class="sssmall" id="sssearch">ค้น Wikipedia</button></div><input id="ssquery" class="ssinput" placeholder="คำค้น: ชื่อวิชา + หัวข้อ"><div id="ssresults" class="ssresults"></div><div id="sssourceLinks" class="sssourceLinks"></div><button class="ssaction ai" id="ssbuildcontent">สร้างสไลด์จากประเด็นที่เลือก</button></section>
    <section id="sstab-style" class="sstabpane"><h3>ชุดรูปแบบ</h3><div class="ssthemes"><button data-theme="blue" class="active"><span class="theme blue"></span><b>Modern Blue</b></button><button data-theme="dark"><span class="theme dark"></span><b>Dark Tech</b></button><button data-theme="warm"><span class="theme warm"></span><b>Warm Classroom</b></button><button data-theme="minimal"><span class="theme minimal"></span><b>Minimal Clean</b></button></div><select id="sstheme" hidden><option value="blue">blue</option><option value="dark">dark</option><option value="warm">warm</option><option value="minimal">minimal</option></select></section><section id="sstab-project" class="sstabpane"><h3>โปรเจกต์และพื้นที่</h3><div id="ssStorageInfo" class="ss-storage-card">กำลังตรวจพื้นที่…</div><button class="ssaction ai" id="ssProjectSave2">บันทึกโปรเจกต์ลง Files</button><button class="ssaction" id="ssProjectOpen2">เปิดโปรเจกต์จาก Files</button><div class="ssnote"><b>ย้ายเครื่องได้:</b> ไฟล์ .vlsproject จะรวมสไลด์ ข้อความ ตำแหน่ง และรูปทั้งหมด เปิดต่อบน iPad หรือคอมได้</div><button class="ssaction danger" id="ssClearProject">ล้างโปรเจกต์ในเครื่องนี้</button></section>
   </aside>
  </div>
 </div>`);
 const bind=(id,fn)=>$(id)&&( $(id).onclick=fn );
 bind('ssclose',close);bind('ssadd',add);bind('ssdup',duplicate);bind('ssdel',del);bind('sspdf',pdf);bind('ssppt',ppt);bind('sspresent',present);bind('ssFocus',()=>{const studio=$('slideStudio');studio.classList.toggle('ss-focus');const on=studio.classList.contains('ss-focus');$('ssFocus').textContent=on?'⊞ แสดงเครื่องมือ':'⛶ ขยายพื้นที่';});bind('ssuseLesson',lessonModal);bind('ssSaveProject',exportProject);bind('ssOpenProject',()=>$('ssProjectFile').click());bind('ssProjectSave2',exportProject);bind('ssProjectOpen2',()=>$('ssProjectFile').click());bind('ssClearProject',clearProject);$('ssProjectFile').onchange=e=>{importProject(e.target.files?.[0]);e.target.value=''};bind('ssremoveimg',async()=>{const s=slides[cur]=norm(slides[cur]);if(!s.images.length)return;const [gone]=s.images.splice(selectedLayer,1);await dbDel(gone?.id);selectedLayer=Math.max(0,Math.min(selectedLayer,s.images.length-1));s.img=s.images[0]?.src||'';scheduleSave();render();refreshStorageInfo()});bind('ssgoogleimg',googleImages);bind('ssquickGoogle',googleImages);bind('ssaiimage',aiImage);bind('ssquickAI',aiImage);bind('ssquickUpload',()=>$('ssimage').click());
 $('ssimage').onchange=e=>{fileToSlide(e.target.files?.[0]);e.target.value=''};$('ssfade').oninput=e=>{$('ssfadeValue').textContent=e.target.value+'%';slides[cur].fade=Number(e.target.value);renderPreview();scheduleSave()};$('ssfadeDir').onchange=e=>{slides[cur].fadeDir=e.target.value;renderPreview();scheduleSave()};
 $('sstitleSize').oninput=e=>{slides[cur].titleSize=Number(e.target.value);$('sstitleSizeValue').textContent=e.target.value+' px';renderPreview();scheduleSave()};
 $('ssbodySize').oninput=e=>{slides[cur].bodySize=Number(e.target.value);$('ssbodySizeValue').textContent=e.target.value+' px';renderPreview();scheduleSave()};
 $('sstitleColor').oninput=e=>{slides[cur].titleColor=e.target.value;renderPreview();scheduleSave()};$('ssbodyColor').oninput=e=>{slides[cur].bodyColor=e.target.value;renderPreview();scheduleSave()};$('ssmoveTo').onchange=e=>moveSlide(cur,Number(e.target.value));
 $('ssimageMode').onchange=e=>{slides[cur].imageMode=e.target.value;renderPreview();scheduleSave()};
 if($('sszoom'))$('sszoom').oninput=e=>{const im=slides[cur].images?.[selectedLayer];if(!im)return;im.zoom=Number(e.target.value);$('sszoomValue').textContent=e.target.value+'%';renderPreview();scheduleSave()};
 if($('ssposx'))$('ssposx').oninput=e=>{const im=slides[cur].images?.[selectedLayer];if(!im)return;im.x=Number(e.target.value);$('ssposxValue').textContent=e.target.value+'%';renderPreview();scheduleSave()};
 if($('ssposy'))$('ssposy').oninput=e=>{const im=slides[cur].images?.[selectedLayer];if(!im)return;im.y=Number(e.target.value);$('ssposyValue').textContent=e.target.value+'%';renderPreview();scheduleSave()};
 if($('sswidth'))$('sswidth').oninput=e=>{const im=slides[cur].images?.[selectedLayer];if(!im||selectedLayer===0)return;im.w=Number(e.target.value);$('sswidthValue').textContent=e.target.value+'%';renderPreview();scheduleSave()};
 ['sstitle','ssbodytext'].forEach(id=>{if($(id))$(id).oninput=()=>{const sl=slides[cur];if(id==='sstitle')sl.t=$(id).value;else sl.b=$(id).value;renderPreview();scheduleSave()}});if($('sstype'))$('sstype').onchange=e=>{slides[cur].type=e.target.value;renderPreview();scheduleSave()};
 document.querySelectorAll('[data-pos]').forEach(b=>b.onclick=()=>{const [x,y]=b.dataset.pos.split(',').map(Number);setImagePreset(x,y)});
 document.querySelectorAll('[data-sstab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-sstab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.sstabpane').forEach(x=>x.classList.remove('active'));$('sstab-'+b.dataset.sstab).classList.add('active');if(b.dataset.sstab==='project')refreshStorageInfo()});
 document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{theme=b.dataset.theme;document.querySelectorAll('[data-theme]').forEach(x=>x.classList.toggle('active',x===b));save();render()});
 bind('ssgoogle',()=>{let q=encodeURIComponent(`${$('subject')?.value||''} ${$('topic')?.value||''}`.trim());window.open('https://www.google.com/search?q='+q,'_blank','noopener')});
 bind('ssai',()=>{let sub=$('subject')?.value||'รายวิชาอาชีวศึกษา',top=$('topic')?.value||'หัวข้อบทเรียน',lvl=$('level')?.value||'อาชีวศึกษา';let prompt=`สร้างเนื้อหาสไลด์การสอน วิชา ${sub} เรื่อง ${top} ระดับ ${lvl} จำนวน 10 สไลด์ ภาษาไทยกระชับ ถูกต้อง เรียงจากพื้นฐานไปประยุกต์ แต่ละสไลด์ให้มีหัวข้อและเนื้อหา 2-4 ประเด็น`;navigator.clipboard?.writeText(prompt).catch(()=>{});window.open('https://chatgpt.com/','_blank','noopener')});
 bind('sssearch',wikiSearch);bind('ssusepaste',usePasted);bind('ssbuildcontent',buildFromResearch);renderResearch();
 // If Slides was the last selected teacher mode, open the editor after all controls exist.
 if(localStorage.getItem('teacherMode')==='slides') setTimeout(()=>open().catch(()=>{}),60);
});
})();
