(()=>{const $=id=>document.getElementById(id);let slides=[],cur=0,theme='blue';
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const art=(topic,i)=>`<svg viewBox="0 0 600 400" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="#0d668f"/><stop offset="1" stop-color="#5db5d8"/></linearGradient></defs><rect x="35" y="55" width="530" height="290" rx="32" fill="#edf7fb"/><circle cx="300" cy="200" r="112" fill="white" stroke="url(#g)" stroke-width="8"/><path d="M160 240 C220 110 380 110 440 240" fill="none" stroke="#f2b84b" stroke-width="18" stroke-linecap="round"/><circle cx="210" cy="238" r="27" fill="#0d668f"/><circle cx="390" cy="238" r="27" fill="#0d668f"/><path d="M270 235 L330 165 L330 235 Z" fill="#5db5d8" opacity=".8"/><text x="300" y="315" text-anchor="middle" font-family="sans-serif" font-size="22" font-weight="700" fill="#0c4566">${esc(topic).slice(0,34)}</text></svg>`;
function seed(){let subject=$('subject')?.value||'รายวิชาอาชีวศึกษา',topic=$('topic')?.value||'หัวข้อการเรียนรู้',code=$('code')?.value||'',level=$('level')?.value||'',school=$('school')?.value||'';slides=[
{t:topic,k:`${subject}${code?' • '+code:''}`,b:`บทเรียนสำหรับ ${level||'ผู้เรียนอาชีวศึกษา'}\n${school}`,type:'cover'},
{t:'เป้าหมายการเรียนรู้',k:subject,b:`เข้าใจหลักการสำคัญของ ${topic}\nอธิบายองค์ประกอบและหน้าที่ได้\nนำความรู้ไปเชื่อมโยงกับงานจริงได้`,type:'bullets'},
{t:'ภาพรวมของบทเรียน',k:'BIG PICTURE',b:`${topic} คือหัวข้อที่ควรเรียนจากภาพรวมไปสู่รายละเอียด โดยเชื่อมโยง “หลักการ – องค์ประกอบ – การทำงาน – การประยุกต์ใช้”`,type:'visual'},
{t:'หลักการสำคัญ',k:'CORE CONCEPT',b:`เริ่มจากความหมายและหลักการพื้นฐาน\nแยกตัวแปรหรือองค์ประกอบที่เกี่ยวข้อง\nพิจารณาความสัมพันธ์ของแต่ละส่วน\nตรวจสอบผลตามหลักวิชาชีพ`,type:'bullets'},
{t:'องค์ประกอบและหน้าที่',k:'COMPONENTS',b:`ส่วนที่ 1 • หน้าที่หลัก\nส่วนที่ 2 • การเชื่อมโยง\nส่วนที่ 3 • การควบคุมหรือเงื่อนไข\nส่วนที่ 4 • การตรวจสอบและความปลอดภัย`,type:'cards'},
{t:'ลำดับการทำงาน',k:'HOW IT WORKS',b:`1. รับข้อมูลหรือพลังงานเข้าสู่ระบบ\n2. ประมวลผลตามหลักการของ ${topic}\n3. เกิดผลลัพธ์ที่ต้องการ\n4. ตรวจสอบและแก้ไขเมื่อผลไม่เป็นไปตามเงื่อนไข`,type:'visual'},
{t:'ตัวอย่างในงานจริง',k:'APPLICATION',b:`สังเกตว่า ${topic} ถูกนำไปใช้ที่ใด\nระบุอุปกรณ์หรือข้อมูลที่เกี่ยวข้อง\nอธิบายเหตุผลของการเลือกใช้\nเชื่อมโยงกับสถานการณ์ในงานอาชีพ`,type:'cards'},
{t:'สรุปท้ายบท',k:'RECAP',b:`จำหลักการให้ได้ • เข้าใจหน้าที่ของแต่ละส่วน • มองลำดับการทำงานเป็นระบบ • นำไปใช้และตรวจสอบอย่างปลอดภัย`,type:'visual'}];}
function slideHTML(s,i){let lines=s.b.split('\n').filter(Boolean),body=s.type==='cards'?`<div class="cardgrid">${lines.map((x,j)=>`<div class="card"><b>${String(j+1).padStart(2,'0')}</b><p contenteditable="true">${esc(x)}</p></div>`).join('')}</div>`:s.type==='bullets'?`<ul>${lines.map(x=>`<li contenteditable="true">${esc(x)}</li>`).join('')}</ul>`:`<p contenteditable="true">${esc(s.b)}</p>`;return `<div class="slide ${s.type==='cover'?'cover':''}" data-theme="${theme}"><div><div class="kicker" contenteditable="true">${esc(s.k)}</div><div class="accent"></div><h${s.type==='cover'?1:2} contenteditable="true">${esc(s.t)}</h${s.type==='cover'?1:2}>${body}</div><div class="visual">${art(s.t,i)}</div><span class="num">${String(i+1).padStart(2,'0')}</span></div>`}
function render(){let c=$('sscanvas');c.innerHTML=slideHTML(slides[cur],cur);$('ssthumbs').innerHTML=slides.map((s,i)=>`<div class="ssthumb ${i===cur?'active':''}" data-i="${i}"><b>${i+1}. ${esc(s.t)}</b><span>${esc(s.b).slice(0,100)}</span></div>`).join('');document.querySelectorAll('.ssthumb').forEach(x=>x.onclick=()=>{save();cur=+x.dataset.i;render()});$('sstitle').value=slides[cur].t;$('ssbodytext').value=slides[cur].b;$('sstype').value=slides[cur].type;}
function save(){let s=slides[cur];if(!s)return;s.t=$('sstitle')?.value||s.t;s.b=$('ssbodytext')?.value||s.b;s.type=$('sstype')?.value||s.type}
function open(){if(!slides.length)seed();$('slideStudio').classList.add('open');render()}
function close(){save();$('slideStudio').classList.remove('open')}
function add(){save();slides.splice(cur+1,0,{t:'หัวข้อใหม่',k:'NEW SLIDE',b:'คลิกหรือพิมพ์เพื่อแก้ไขเนื้อหา',type:'visual'});cur++;render()}
function del(){if(slides.length<=1)return;slides.splice(cur,1);cur=Math.max(0,cur-1);render()}
function ppt(){save();if(!window.PptxGenJS){alert('ไม่สามารถโหลดตัวส่งออก PowerPoint ได้ กรุณาเชื่อมต่ออินเทอร์เน็ตแล้วลองใหม่');return}let p=new PptxGenJS();p.layout='LAYOUT_WIDE';p.author='Vocational Slide Studio';p.subject=$('subject')?.value||'';p.title=$('topic')?.value||'';slides.forEach((s,i)=>{let x=p.addSlide();x.background={color:'F8FBFD'};x.addShape(p.ShapeType.rect,{x:0,y:0,w:13.333,h:.16,fill:{color:'0D668F'},line:{color:'0D668F'}});x.addText(s.k,{x:.8,y:.55,w:7.8,h:.35,fontFace:'Sarabun',fontSize:11,bold:true,color:'C47B00'});x.addText(s.t,{x:.8,y:1.05,w:7.6,h:1.15,fontFace:'Sarabun',fontSize:s.type==='cover'?30:25,bold:true,color:'0C4566',breakLine:false,fit:'shrink'});let arr=s.b.split('\n').filter(Boolean);if(s.type==='bullets'||s.type==='cards')x.addText(arr.map(v=>({text:v,options:{bullet:{indent:16}}})),{x:.9,y:2.35,w:7.1,h:3.7,fontFace:'Sarabun',fontSize:17,color:'243746',breakLine:true,fit:'shrink',paraSpaceAfterPt:10});else x.addText(s.b,{x:.9,y:2.35,w:7.1,h:3.2,fontFace:'Sarabun',fontSize:18,color:'243746',fit:'shrink',valign:'mid'});x.addShape(p.ShapeType.ellipse,{x:9.1,y:1.7,w:3.1,h:3.1,fill:{color:'E8F3F8'},line:{color:'5DB5D8',width:2}});x.addText(String(i+1).padStart(2,'0'),{x:11.8,y:6.8,w:.6,h:.3,fontSize:10,color:'78909F'});});p.writeFile({fileName:`${($('subject')?.value||'บทเรียน').replace(/[\\/:*?"<>|]/g,'-')}-${($('topic')?.value||'สไลด์').replace(/[\\/:*?"<>|]/g,'-')}.pptx`})}
function pdf(){save();let host=document.createElement('div');host.id='ssprintHost';slides.forEach((s,i)=>{let pg=document.createElement('div');pg.className='ssprintpage';pg.innerHTML=`<div class="sscanvas">${slideHTML(s,i)}</div>`;host.appendChild(pg)});$('slideStudio').appendChild(host);document.body.classList.add('ssprinting');setTimeout(()=>{window.print();setTimeout(()=>{document.body.classList.remove('ssprinting');host.remove()},600)},150)}
let researchPoints=[],researchSources=[];
function splitPoints(text){return String(text||'').replace(/\[[^\]]*\]/g,' ').split(/(?<=[.!?。]|[ครับค่ะ])\s+|\n+/).map(x=>x.trim().replace(/^[-•\d.)\s]+/,'' )).filter(x=>x.length>=35&&x.length<=360).filter((x,i,a)=>a.findIndex(y=>y.slice(0,55)===x.slice(0,55))===i).slice(0,30)}
function renderResearch(msg){let box=$('ssresults');if(!box)return;if(msg){box.innerHTML=`<div class="ssnotice">${esc(msg)}</div>`;return}box.innerHTML=researchPoints.length?researchPoints.map((x,i)=>`<label class="sspoint"><input type="checkbox" data-rp="${i}" checked><span>${esc(x)}</span></label>`).join(''):`<div class="ssnotice">ยังไม่มีเนื้อหา กด “ค้นหาเนื้อหา” หรือวางข้อความอ้างอิงของครู</div>`;$('sssourceLinks').innerHTML=researchSources.map(x=>`<div>• <a href="${x.url}" target="_blank" rel="noopener">${esc(x.title)}</a></div>`).join('')}
async function wikiSearch(){let q=($('ssquery')?.value||`${$('subject')?.value||''} ${$('topic')?.value||''}`).trim();if(!q)return;renderResearch('กำลังค้นหาจาก Wikipedia…');researchPoints=[];researchSources=[];try{let api='https://th.wikipedia.org/w/api.php?origin=*&action=query&generator=search&gsrsearch='+encodeURIComponent(q)+'&gsrlimit=5&prop=extracts|info&exintro=1&explaintext=1&inprop=url&format=json';let r=await fetch(api);if(!r.ok)throw new Error();let j=await r.json();let pages=Object.values(j.query?.pages||{}).sort((a,b)=>(a.index||0)-(b.index||0));pages.forEach(pg=>{researchPoints.push(...splitPoints(pg.extract));researchSources.push({title:pg.title,url:pg.fullurl})});researchPoints=[...new Set(researchPoints)].slice(0,24);renderResearch(researchPoints.length?'':`ไม่พบเนื้อหาที่ใช้ได้สำหรับ “${q}” ลองลดคำค้น หรือวางเนื้อหาอ้างอิงด้านล่าง`)}catch(e){renderResearch('ค้นหาออนไลน์ไม่สำเร็จ ตรวจสอบอินเทอร์เน็ต หรือลองวางเนื้อหาอ้างอิงของครูแทน')}}
function usePasted(){let t=$('sspasted')?.value||'';let pts=splitPoints(t);if(!pts.length){renderResearch('ข้อความยังสั้นเกินไปหรือไม่มีประโยคที่ใช้เป็นเนื้อหาได้');return}researchPoints=pts;researchSources=[{title:'เนื้อหาที่ครูวางเอง',url:'#'}];renderResearch()}
function selectedPoints(){return [...document.querySelectorAll('[data-rp]:checked')].map(x=>researchPoints[+x.dataset.rp]).filter(Boolean)}
function buildFromResearch(){let pts=selectedPoints();if(!pts.length){alert('กรุณาเลือกอย่างน้อย 1 ประเด็น');return}let subject=$('subject')?.value||'รายวิชาอาชีวศึกษา',topic=$('topic')?.value||'หัวข้อการเรียนรู้',code=$('code')?.value||'',level=$('level')?.value||'';let groups=[];for(let i=0;i<pts.length;i+=3)groups.push(pts.slice(i,i+3));slides=[{t:topic,k:`${subject}${code?' • '+code:''}`,b:`บทเรียนสำหรับ ${level||'ผู้เรียนอาชีวศึกษา'}\nสร้างจากประเด็นเนื้อหาที่ครูตรวจเลือก`,type:'cover'},...groups.slice(0,10).map((g,i)=>({t:i===0?'ความรู้พื้นฐาน':i===groups.length-1?'ประเด็นสำคัญท้ายบท':`${topic} • ${i+1}`,k:'CONTENT',b:g.join('\n'),type:g.length>1?'bullets':'visual'})),{t:'สรุปท้ายบท',k:'RECAP',b:pts.slice(0,5).map(x=>x.length>115?x.slice(0,112)+'…':x).join('\n'),type:'bullets'}];cur=0;render()}
document.addEventListener('DOMContentLoaded',()=>{document.body.insertAdjacentHTML('beforeend',`<div id="slideStudio"><div class="ssbar"><strong>Slide Studio • สื่อการสอน 16:9</strong><button class="ssbtn" id="ssadd">+ สไลด์</button><button class="ssbtn" id="ssdel">ลบ</button><button class="ssbtn" id="sspdf">PDF</button><button class="ssbtn primary" id="ssppt">PowerPoint</button><button class="ssbtn" id="ssclose">ปิด</button></div><div class="ssbody"><aside class="ssleft" id="ssthumbs"></aside><main class="sscenter"><div class="sscanvas" id="sscanvas"></div></main><aside class="ssright" id="ssright"><h3>แก้ไขสไลด์</h3><div class="ssfield"><label>หัวข้อ</label><input id="sstitle"></div><div class="ssfield"><label>เนื้อหา (ขึ้นบรรทัดใหม่เพื่อแยกข้อ)</label><textarea id="ssbodytext"></textarea></div><div class="ssfield"><label>รูปแบบ</label><select id="sstype"><option value="visual">ข้อความ + ภาพ</option><option value="bullets">หัวข้อย่อย</option><option value="cards">การ์ดข้อมูล</option><option value="cover">หน้าปก</option></select></div><div class="ssrow"><button class="sssmall" id="ssapply">อัปเดต</button><button class="sssmall" id="ssregen">สร้างใหม่จากข้อมูลวิชา</button></div><div class="ssresearch"><h3>ค้นหาเนื้อหา</h3><div class="ssnotice">V34 ค้นข้อมูลออนไลน์จริงจาก Wikipedia แล้วให้ครูเลือกประเด็นก่อนสร้างสไลด์ ไม่ใช่ AI เดาเนื้อหา</div><div class="sssearchrow"><input id="ssquery" placeholder="ชื่อวิชา + หัวข้อ"><button class="sssmall" id="sssearch">ค้นหาเนื้อหา</button></div><div class="sssource">ประเด็นที่ใช้ได้ — ติ๊กเฉพาะสิ่งที่ต้องการสอน</div><div class="ssresults" id="ssresults"></div><div class="sssourceLinks" id="sssourceLinks"></div><div class="sssource">หรือวางเนื้อหาจากเอกสาร/คู่มือของครู</div><textarea class="sspaste" id="sspasted" placeholder="วางข้อความอ้างอิงที่นี่…"></textarea><div class="ssrow"><button class="sssmall" id="ssusepaste">วิเคราะห์ข้อความ</button><button class="sssmall primary" id="ssbuildcontent">สร้างสไลด์จากที่เลือก</button></div></div><p style="font-size:12px;color:#657b8a;line-height:1.55">แก้ข้อความได้จากแถบนี้หรือแตะข้อความบนสไลด์โดยตรง สัดส่วน 16:9 คงที่ทั้ง iPad และคอมพิวเตอร์</p></aside></div></div>`);$('slideBuilderBtn')?.addEventListener('click',open);$('ssclose').onclick=close;$('ssadd').onclick=add;$('ssdel').onclick=del;$('ssapply').onclick=()=>{save();render()};$('ssregen').onclick=()=>{seed();cur=0;render()};$('ssppt').onclick=ppt;$('sspdf').onclick=pdf;$('sssearch').onclick=wikiSearch;$('ssusepaste').onclick=usePasted;$('ssbuildcontent').onclick=buildFromResearch;renderResearch();});})();
