(()=>{'use strict';
const $=id=>document.getElementById(id),{get,mutate,esc,date,files,normalizeUrl}=WorkAPI,C=new URLSearchParams(location.search).get('class')||'';
const savedKey='workStudent:'+C;
let entryMode='simple';
let data=null,busy=false,loading=false,filter='all',dirty=false,previewUrls=[];const drafts=new Map();
const credentials=()=>({classId:C,studentId:$('sid').value.trim(),accessCode:$('accessCode').value.trim()});
function notice(s,bad=false){$('notice').textContent=s;$('notice').className=bad?'miss':''}
async function load(){if(loading||busy)return;if(!$('sid').value.trim()){notice('กรอกรหัสนักเรียนก่อนครับ',true);$('sid').focus();return}if(entryMode==='personal'&&!$('accessCode').value){notice('ห้องนี้ใช้ลิงก์ส่วนตัว เปิดจากลิงก์ที่ครูส่งให้ได้เลย',true);return}if(!C){notice('ลิงก์ไม่มีรหัสห้องเรียน กรุณาสแกน QR หรือลิงก์จากครู',true);return}loading=true;$('go').disabled=true;try{const r=await get('getStudentWork',credentials());if(r.apiVersion!=='V56')throw Error('ครูต้อง Deploy Apps Script V56 ก่อน');data=r;localStorage.setItem('swid',credentials().studentId);if($('rememberMe').checked)localStorage.setItem(savedKey,JSON.stringify(credentials()));else localStorage.removeItem(savedKey);$('login').classList.add('hide');dirty=drafts.size>0;render();notice('พร้อมส่งงาน • เลือกไฟล์หรือพิมพ์คำตอบ แล้วกดส่ง');}catch(e){notice(e.message,true)}finally{loading=false;$('go').disabled=false}}
function render(){previewUrls.forEach(URL.revokeObjectURL);previewUrls=[];const s=data.student,subs=Object.fromEntries(data.submissions.map(x=>[x.workId,x]));
 $('app').innerHTML=`<section class="card"><div class="muted">${esc(data.classInfo.className)} • ${esc(data.classInfo.subject)}</div><h1>${esc(s.studentName)}</h1><div class="score">${s.total} / ${s.max} คะแนน</div><p class="grade">เกรดคำนวณ <b>${esc(s.grade??'—')}</b>${s.gradeProvisional?' • ยังมีงานขาดหรือรอตรวจ':''}</p><div class="stats"><div><small>งานทั้งหมด</small><b>${data.works.length}</b></div><div><small>ส่งแล้ว</small><b>${data.works.length-s.missing.length}</b></div><div><small>ขาด</small><b>${s.missing.length}</b></div><div><small>คะแนน</small><b>${s.percent}%</b></div></div>${s.pending?`<p class="muted">มี ${s.pending} งานที่รอตรวจ คะแนนอาจเปลี่ยนเมื่อครูตรวจครบ</p>`:''}<div class="row"><button id="refresh" class="secondary">อัปเดตคะแนน</button><button id="logout" class="secondary">เปลี่ยนผู้ใช้</button></div><label>แสดงงาน<select id="filter"><option value="all">งานทั้งหมด</option><option value="missing">งานที่ยังไม่ส่ง</option><option value="pending">งานรอตรวจ</option><option value="graded">ตรวจแล้ว</option></select></label></section><div id="workList">${data.works.map(w=>{const i=s.items.find(x=>x.workId===w.workId),sub=subs[w.workId];let content='';
 if(w.type==='exam')content=`<p><a href="./student-exam.html?exam=${encodeURIComponent(w.examId)}" target="_blank" rel="noopener">เปิดข้อสอบ →</a></p><small>ใช้รหัสนักเรียน ${esc(s.studentId)} ในหน้าสอบเพื่อเชื่อมคะแนน</small>`;
 else content=`${sub?.feedback?`<p class="feedback"><b>ความคิดเห็นครู:</b> ${esc(sub.feedback)}</p>`:''}${sub?`<p class="muted">ส่งล่าสุด ${date(sub.submittedAt)}</p>`:''}<details ${sub?'':'open'}><summary>${sub?'ดูงาน / ส่งฉบับแก้ไข':'ส่งงาน'}</summary><form data-work="${esc(w.workId)}" novalidate><label>คำตอบ (ถ้าส่งไฟล์ ไม่จำเป็นต้องพิมพ์)<textarea name="answerText" rows="4" maxlength="20000">${esc(sub?.answerText||'')}</textarea></label><details class="optional-link"><summary>แนบลิงก์เพิ่มเติม</summary><label>ลิงก์งาน<input name="answerUrl" type="text" placeholder="https://..." value="${esc(sub?.answerUrl||'')}"></label></details>${(sub?.attachments||[]).map(f=>`<label class="attachment"><input type="checkbox" name="keep" value="${esc(f.id)}" checked>เก็บไฟล์ ${esc(f.name)}</label>`).join('')}<label>แนบรูป / ไฟล์ / PDF<input type="file" name="files" accept="image/*,.heic,.heif,.pdf,.docx,.xlsx,.pptx,.txt" multiple></label><small class="muted">สูงสุด 3 ไฟล์ ไฟล์ละ 3 MB รวม 6 MB • รูป JPG/PNG/WebP ขนาดใหญ่จะย่อให้อัตโนมัติ • ไฟล์ส่งให้ครูแบบส่วนตัว</small><div class="file-preview"></div>${sub?'<p class="muted">การส่งฉบับแก้ไขจะล้างคะแนนเดิมของงานนี้เพื่อให้ครูตรวจใหม่</p>':''}<button>${sub?'ส่งฉบับแก้ไข':'ส่งงานให้ครู'}</button><p class="send-status" role="status"></p></form></details>`;
 return `<section class="card work" data-status="${esc(i.status)}"><h2>${esc(w.title)}</h2>${w.worksheetName?`<p>ใบงาน: ${esc(w.worksheetName)}</p>`:''}${w.description?`<p class="description">${esc(w.description)}</p>`:''}<div class="row"><span class="tag ${i.status==='ขาด'?'miss':'ok'}">${i.status==='ขาด'?'ยังไม่ส่ง':esc(i.status)}${i.late?' • ส่งช้า':''}</span><b>${i.score==null?'ยังไม่มีคะแนน':i.score} / ${w.maxScore}</b></div><p class="muted">กำหนดส่ง ${date(w.dueAt)}</p>${content}</section>`;}).join('')||'<section class="card">ครูยังไม่ได้เผยแพร่งาน</section>'}</div>`;
 $('filter').value=filter;$('filter').onchange=()=>{filter=$('filter').value;applyFilter()};applyFilter();
 $('refresh').onclick=()=>{if(!busy&&(!dirty||confirm('มีงานที่ยังไม่ได้ส่ง ต้องการโหลดข้อมูลใหม่หรือไม่?'))){drafts.clear();load()}};
 $('logout').onclick=()=>{if(busy)return;if(dirty&&!confirm('มีงานที่ยังไม่ได้ส่ง ต้องการออกหรือไม่?'))return;localStorage.removeItem(savedKey);data=null;dirty=false;drafts.clear();$('app').innerHTML='';$('login').classList.remove('hide');$('accessCode').value='';previewUrls.forEach(URL.revokeObjectURL);previewUrls=[];notice('กรอกรหัสของผู้ใช้ใหม่')};
 $('app').querySelectorAll('form[data-work]').forEach(f=>{const remember=()=>{dirty=true;drafts.set(f.dataset.work,{text:f.elements.answerText.value,url:f.elements.answerUrl.value,files:f.elements.files.files,keep:Array.from(f.querySelectorAll('[name=keep]:checked'),x=>x.value)})};const draft=drafts.get(f.dataset.work);if(draft){f.elements.answerText.value=draft.text;f.elements.answerUrl.value=draft.url;f.elements.files.files=draft.files;f.querySelectorAll('[name=keep]').forEach(x=>x.checked=draft.keep.includes(x.value));f.closest('details').open=true;}f.oninput=remember;f.elements.files.onchange=()=>{remember();const box=f.querySelector('.file-preview');box.innerHTML='';Array.from(f.elements.files.files).forEach(file=>{const span=document.createElement('span');span.textContent=file.name+' ('+(file.size/1024).toFixed(0)+' KB)';box.append(span);if(/^image\/(jpeg|png|webp)$/.test(file.type)){const img=document.createElement('img');img.alt=file.name;img.src=URL.createObjectURL(file);previewUrls.push(img.src);box.append(img)}})};
 if(draft)f.elements.files.onchange();
 f.onsubmit=async e=>{e.preventDefault();if(busy)return;const sub=subs[f.dataset.work];if(sub&&!confirm('ส่งฉบับแก้ไขและให้ครูตรวจคะแนนใหม่หรือไม่?'))return;busy=true;const b=f.querySelector('button'),msg=f.querySelector('.send-status'),label=b.textContent;b.textContent='กำลังส่ง…';$('app').querySelectorAll('button').forEach(x=>x.disabled=true);msg.textContent='กำลังส่งและรอการยืนยัน กรุณาอย่าปิดหน้านี้';let success=false;
 try{msg.textContent='กำลังเตรียมไฟล์…';const upload=await files(f.elements.files.files);const keep=Array.from(f.querySelectorAll('[name="keep"]:checked'),x=>x.value);if(upload.length+keep.length>3)throw Error('ไฟล์เดิมและไฟล์ใหม่รวมได้ไม่เกิน 3 ไฟล์');const answerUrl=normalizeUrl(f.elements.answerUrl.value);if(answerUrl&&!WorkAPI.safeUrl(answerUrl))throw Error('ลิงก์ไม่ถูกต้อง แก้ลิงก์หรือลบช่องลิงก์แล้วส่งใหม่');if(!f.elements.answerText.value.trim()&&!answerUrl&&!upload.length&&!keep.length)throw Error('เลือกไฟล์หรือพิมพ์คำตอบก่อนกดส่ง');await mutate({action:'submitWork',...credentials(),workId:f.dataset.work,revision:sub?.revision||0,answerText:f.elements.answerText.value,answerUrl,files:upload,keepFileIds:keep},text=>{msg.textContent=text});success=true;drafts.delete(f.dataset.work);dirty=drafts.size>0;msg.textContent='ส่งงานสำเร็จ เซิร์ฟเวอร์ยืนยันแล้ว';notice('ส่งงานสำเร็จ');}
 catch(e){msg.textContent=e.message;notice(e.message,true);msg.classList.add('miss');msg.scrollIntoView({block:'center',behavior:'smooth'})}finally{b.textContent=label;busy=false;$('app').querySelectorAll('button').forEach(x=>x.disabled=false)}if(success){await load();notice('✓ ส่งงานสำเร็จแล้ว ครูได้รับงานแล้ว')}};});
}
function applyFilter(){$('app').querySelectorAll('.work').forEach(el=>{const s=el.dataset.status;el.hidden=!(filter==='all'||(filter==='missing'&&s==='ขาด')||(filter==='pending'&&['ส่งแล้ว','ส่งช้า','รอตรวจข้อเขียน'].includes(s))||(filter==='graded'&&s==='ตรวจแล้ว'))})}
$('loginForm').onsubmit=e=>{e.preventDefault();load()};
async function init(){
 if(!C){notice('ลิงก์ไม่มีห้องเรียน กรุณาเปิดลิงก์จากครู',true);return}
 try{await WorkAPI.health();const info=await get('getWorkEntry',{classId:C});entryMode=info.entryMode;$('login').querySelector('h1').textContent=info.className+' • '+info.subject;
 const fragment=new URLSearchParams(location.hash.slice(1));let saved=null;try{saved=JSON.parse(localStorage.getItem(savedKey)||'null')}catch{}
 if(fragment.get('student')&&fragment.get('token')){$('sid').value=fragment.get('student');$('accessCode').value=fragment.get('token');history.replaceState(null,'',location.pathname+location.search);load();}
 else if(saved){$('sid').value=saved.studentId;$('accessCode').value=saved.accessCode||'';load();}
 else if(entryMode==='personal'){notice('เปิดลิงก์ส่วนตัวที่ครูแจกเพื่อดูงานได้ทันที ไม่ต้องพิมพ์รหัสลับ',true);}
 }catch(e){notice(e.message,true)}
}
init();
window.addEventListener('beforeunload',e=>{if(dirty||busy){e.preventDefault();e.returnValue=''}});
})();
