(function(){
 const $=id=>document.getElementById(id),special=['มายแมป','จับคู่ภาพกับชื่อหรือเนื้อหา'];
 special.forEach(t=>{presets[t]={instruction:t==='มายแมป'?'เติมแนวคิดและความสัมพันธ์ลงในแผนผังแต่ละหัวข้อ':'เขียนหมายเลขคำตอบให้ตรงกับภาพแต่ละข้อ',objectives:['จัดหมวดหมู่และเชื่อมโยงความรู้ได้']};if(![...$('type').options].some(o=>o.value===t))$('type').add(new Option(t,t))});
 let config={counts:{},manual:false,pairs:[],mindmapImage:''};try{Object.assign(config,JSON.parse(localStorage.getItem('vocStudio')||'{}'))}catch{}
 const panel=document.createElement('section');panel.className='research-box';panel.innerHTML='<h3>จัดสัดส่วนรายหัวข้อ</h3><label><input id="manualAllocation" type="checkbox"> กำหนดจำนวนข้อเอง</label><div id="allocationRows"></div><p id="allocationStatus" role="status"></p><section id="mindmapEditor" class="mindmap-upload" hidden><label>ภาพตรงกลางของมายแมป (PNG, JPG หรือ WebP ไม่เกิน 4 MB)<input id="mindmapImage" type="file" accept="image/png,image/jpeg,image/webp"></label><img id="mindmapPreview" class="mindmap-preview" alt="ตัวอย่างภาพตรงกลาง" hidden></section><section id="pairEditor" hidden><h3>ภาพและคำตอบสำหรับจับคู่</h3><p>แต่ละรายการ = 1 ข้อ เลือกภาพและแก้ชื่อหรือคำอธิบายได้</p><div id="pairRows"></div><button id="addPair" type="button" class="btn btn-light">＋ เพิ่มคู่ภาพ</button></section>';
 $('generateBtn').before(panel);$('manualAllocation').checked=config.manual;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function persist(){try{localStorage.setItem('vocStudio',JSON.stringify(config))}catch{$('allocationStatus').textContent='พื้นที่เก็บแบบร่างเต็ม การแก้ไขล่าสุดยังอยู่ในหน้านี้'}}
 function topicList(){return window.worksheetQuality.topics()}
 function allocation(){const ts=topicList(),n=Math.max(1,Math.min(60,+$('count').value||1));return ts.map((topic,i)=>({topic,count:config.manual?Math.max(0,Math.min(60,Math.floor(+config.counts[topic]||0))):Math.floor(n/ts.length)+(i<n%ts.length?1:0)}))}
 function manualCount(){return window.worksheetManual?.items().length||0}
 function refresh(){const rows=allocation(),total=+$('count').value||1,manual=manualCount(),sourceTotal=Math.min(rows.reduce((n,x)=>n+x.count,0),Math.max(0,total-manual)),mindmap=$('type').value===special[0],preview=$('mindmapPreview');$('allocationRows').innerHTML=rows.map((r,i)=>'<label class="allocation-row"><span>'+esc(r.topic)+'</span><input aria-label="จำนวนข้อ '+esc(r.topic)+'" data-index="'+i+'" type="number" min="0" max="60" value="'+r.count+'" '+(!config.manual?'disabled':'')+'></label>').join('');$('pairEditor').hidden=$('type').value!==special[1];$('mindmapEditor').hidden=!mindmap;preview.hidden=!config.mindmapImage;if(config.mindmapImage)preview.src=config.mindmapImage;$('allocationStatus').textContent=manual?'จากเนื้อหา '+sourceTotal+' ข้อ + โจทย์ที่ครูเพิ่ม '+manual+' ข้อ (รวม '+total+' ข้อ)':'รวม '+sourceTotal+' / '+total+' ข้อ';$('allocationRows').querySelectorAll('input').forEach(input=>input.onchange=()=>{config.counts[rows[+input.dataset.index].topic]=Math.max(0,Math.min(60,Math.floor(+input.value||0)));persist();refresh()})}
 function validate(){if($('type').value===special[1]){if(config.pairs.length<2||config.pairs.some(p=>!p.src||!p.label.trim())){alert('เพิ่มอย่างน้อย 2 คู่ พร้อมภาพและคำตอบให้ครบ');return false}return true}const total=allocation().reduce((n,x)=>n+x.count,0),requested=+$('count').value||1,expected=config.manual?Math.max(0,requested-manualCount()):requested;if(total!==expected){alert('จำนวนข้อจากเนื้อหาต้องรวม '+expected+' ข้อ (ระบบกันไว้ '+manualCount()+' ข้อสำหรับโจทย์ที่ครูเพิ่ม)');return false}return true}
 $('manualAllocation').onchange=()=>{if(!config.manual)allocation().forEach(r=>config.counts[r.topic]=r.count);config.manual=$('manualAllocation').checked;persist();refresh()};
 function pairRows(){ $('pairRows').innerHTML=config.pairs.map((p,i)=>'<div class="pair-edit"><b>คู่ที่ '+(i+1)+'</b>'+(p.src?'<img src="'+p.src+'" alt="ภาพที่เลือก">':'')+'<label>เลือก / เปลี่ยนภาพ<input data-file="'+i+'" type="file" accept="image/png,image/jpeg,image/webp"></label><label>ชื่อหรือเนื้อหาที่ตรงกับภาพ<input data-label="'+i+'" value="'+esc(p.label)+'"></label><button type="button" data-remove="'+i+'">ลบคู่นี้</button></div>').join('');
 $('pairRows').querySelectorAll('[data-label]').forEach(x=>x.oninput=()=>{config.pairs[+x.dataset.label].label=x.value;persist()});
 $('pairRows').querySelectorAll('[data-remove]').forEach(x=>x.onclick=()=>{config.pairs.splice(+x.dataset.remove,1);persist();pairRows()});
 $('pairRows').querySelectorAll('[data-file]').forEach(x=>x.onchange=async()=>{const f=x.files[0];if(!f)return;if(!/^image\/(png|jpeg|webp)$/.test(f.type)||f.size>4*1024*1024){alert('ใช้ภาพ PNG, JPG หรือ WebP ไม่เกิน 4 MB');return}const p=config.pairs[+x.dataset.file];const reader=new FileReader();reader.onload=()=>{p.src=reader.result;persist();pairRows()};reader.readAsDataURL(f)});
 }
 $('addPair').onclick=()=>{if(config.pairs.length>=60)return;config.pairs.push({src:'',label:''});persist();pairRows()};
 $('mindmapImage').onchange=e=>{const f=e.target.files?.[0];if(!f)return;if(!/^image\/(png|jpeg|webp)$/.test(f.type)||f.size>4*1024*1024){alert('ใช้ภาพ PNG, JPG หรือ WebP ไม่เกิน 4 MB');e.target.value='';return}const reader=new FileReader();reader.onload=()=>{config.mindmapImage=reader.result;persist();refresh();window.render()};reader.readAsDataURL(f)};
 function renderSpecial(){const type=$('type').value;if(!special.includes(type))return false;const list=$('paper').querySelector('.exercise');list.innerHTML='';let total=0;
 if(type===special[0]){allocation().filter(r=>r.count).forEach(r=>{for(let offset=0;offset<r.count;offset+=6){const size=Math.min(6,r.count-offset),li=document.createElement('li');li.className='mindmap-sheet';const image=config.mindmapImage?'<img src="'+config.mindmapImage+'" alt="ภาพกลางมายแมป">':'';li.innerHTML='<div class="map-artboard"><div class="map-center">'+image+'<span>'+esc(r.topic)+'</span></div><div class="map-branches">'+Array.from({length:size},()=>'<div class="map-branch"><div class="map-space" aria-label="พื้นที่เติมแนวคิด"></div></div>').join('')+'</div></div><div class="answer">เกณฑ์: จัดวางแนวคิดและออกแบบกรอบเชื่อมโยงได้อย่างสร้างสรรค์ โดยเนื้อหาสัมพันธ์กับหัวข้อ</div>';list.appendChild(li);total+=size}})}
 else{total=config.pairs.length;const ordered=config.pairs.map((p,i)=>({p,i}));if(ordered.length>1)ordered.push(ordered.shift());const bank=document.createElement('div');bank.className='match-bank';bank.innerHTML='<b>ชุดคำตอบ</b><br>'+ordered.map((x,j)=>(j+1)+'. '+esc(x.p.label)).join('<br>');list.before(bank);config.pairs.forEach((p,i)=>{const li=document.createElement('li');li.className='match-item';li.innerHTML=(p.src?'<img src="'+p.src+'" alt="ภาพข้อ '+(i+1)+'">':'<div>ยังไม่ได้เลือกภาพ</div>')+'<p>คำตอบหมายเลข ______</p><div class="answer">เฉลย: '+(ordered.findIndex(x=>x.i===i)+1)+' — '+esc(p.label)+'</div>';list.appendChild(li)})}
 const instruction=[...$('paper').querySelectorAll('.block')].find(x=>x.querySelector('h3')?.textContent==='คำชี้แจง');if(instruction)instruction.querySelector('p').textContent=presets[type].instruction+' รวม '+total+' '+(type===special[0]?'ช่องความคิด':'ข้อ')+' คะแนนเต็ม '+total+' คะแนน';$('paper').querySelector('.scorebox').innerHTML='คะแนนที่ได้ ______ / '+total+' คะแนน<br>ผู้ตรวจ __________________';return true;
 }
 window.worksheetStudio={allocation,renderSpecial,activeCount:null,isManual:()=>config.manual};
 for(const id of ['generateBtn','aiGenerateBtn']){const previous=$(id).onclick;$(id).onclick=()=>{refresh();if(!validate())return;if(special.includes($('type').value)){window.render();return}if(id==='aiGenerateBtn'&&window.worksheetQuality?.generateFromSelected){window.worksheetQuality.generateFromSelected();return}if(typeof previous==='function'){previous();return}window.render()}}
 $('count').addEventListener('input',refresh);$('type').addEventListener('change',refresh);$('topic').addEventListener('input',refresh);new MutationObserver(refresh).observe($('topicBasket'),{childList:true});
 document.addEventListener('research-updated',refresh);
 document.addEventListener('manual-updated',refresh);
 pairRows();refresh();window.render();
})();
