(()=>{'use strict';
const $=id=>document.getElementById(id),{get,mutate,esc,date,files,normalizeUrl}=WorkAPI,C=new URLSearchParams(location.search).get('class')||'';
const savedKey='workStudent:'+C;
const cats={worksheet:'ใบงาน',quiz:'แบบทดสอบ',practical:'ปฏิบัติ',other:'จิตพิสัย / อื่น ๆ'},num=x=>Number(x||0).toLocaleString('th-TH',{maximumFractionDigits:2});
let entryMode='simple';
let data=null,busy=false,loading=false,filter='all',dirty=false,previewUrls=[],activeWork='';const drafts=new Map();
const credentials=()=>({classId:C,studentId:$('sid').value.trim(),accessCode:$('accessCode').value.trim()});
function notice(s,bad=false){$('notice').textContent=s;$('notice').className=bad?'miss':''}
async function load(){if(loading||busy)return;if(!$('sid').value.trim()){notice('กรอกรหัสนักเรียนก่อนครับ',true);$('sid').focus();return}if(entryMode==='personal'&&!$('accessCode').value){notice('ห้องนี้ใช้ลิงก์ส่วนตัว เปิดจากลิงก์ที่ครูส่งให้ได้เลย',true);return}if(!C){notice('ลิงก์ไม่มีรหัสห้องเรียน กรุณาสแกน QR หรือลิงก์จากครู',true);return}loading=true;$('go').disabled=true;try{const r=await get('getStudentWork',credentials());if(r.apiVersion!=='V67')throw Error('ครูต้อง Deploy Apps Script V67 ก่อน');data=r;localStorage.setItem('swid',credentials().studentId);if($('rememberMe').checked)localStorage.setItem(savedKey,JSON.stringify(credentials()));else localStorage.removeItem(savedKey);$('login').classList.add('hide');dirty=drafts.size>0;render();notice('พร้อมส่งงาน • ส่งตามรูปแบบที่ครูกำหนด');}catch(e){notice(e.message,true)}finally{loading=false;$('go').disabled=false}}
function render(){previewUrls.forEach(URL.revokeObjectURL);previewUrls=[];const s=data.student,showScores=['scores','full'].includes(data.classInfo.resultVisibility),showGrade=data.classInfo.resultVisibility==='full',subs=Object.fromEntries(data.submissions.map(x=>[x.workId,x]));
 $('app').innerHTML=`<section class="card"><div class="muted">${esc(data.classInfo.className)} • ${esc(data.classInfo.subject)}</div><h1>${esc(s.studentName)}</h1>${showScores?`<div class="score">${num(s.percent)} <small>/ 100 คะแนน</small></div>`:'<p class="results-hidden">ครูยังไม่เผยแพร่คะแนนและเกรด</p>'}${showGrade?`<p class="grade">เกรดระหว่างเรียน <b>${esc(s.grade??'—')}</b>${s.gradeProvisional?' • ผลยังไม่ครบทุกงานหรือทุกหมวด':''}</p>`:showScores?'<p>ครูยังไม่เผยแพร่เกรด</p>':''}<div class="stats"><button type="button" data-filter="all"><small>งานทั้งหมด</small><b>${data.works.length}</b></button><button type="button" data-filter="missing" class="missing-tile"><small>ยังไม่ส่ง / งานขาด</small><b>${s.missing.length}</b><span>แตะดูงานที่ต้องส่ง →</span></button><button type="button" data-filter="pending"><small>รอตรวจ</small><b>${s.pending}</b></button><button type="button" data-filter="graded"><small>ตรวจแล้ว</small><b>${s.items.filter(i=>i.status==='ตรวจแล้ว').length}</b></button></div>${showScores&&data.classInfo.scoringMode==='weighted'?`<details class="category-detail"><summary>ดูคะแนนแยกหมวด</summary><div class="category-grid">${(s.categories||[]).map(c=>`<div><small>${cats[c.id]}</small><b>${num(c.points)} / ${c.weight}</b><small>${c.max?`${num(c.earned)} / ${num(c.max)} คะแนนดิบ`:'ยังไม่มีงาน'}</small></div>`).join('')}</div></details>`:''}${s.pending?`<p class="muted">มี ${s.pending} งานที่รอตรวจ คะแนนอาจเปลี่ยนเมื่อครูตรวจครบ</p>`:''}<div class="row"><button id="refresh" class="secondary">อัปเดตงาน</button><button id="logout" class="secondary">เปลี่ยนผู้ใช้</button></div><label>แสดงงาน<select id="filter"><option value="all">งานทั้งหมด</option><option value="missing">งานที่ยังไม่ส่ง</option><option value="pending">งานรอตรวจ</option><option value="graded">ตรวจแล้ว</option></select></label></section><section id="latestWork" class="card"></section><div id="studentTable"></div><div id="workList">${data.works.map(w=>{const i=s.items.find(x=>x.workId===w.workId),sub=subs[w.workId],overdue=i.status==='ขาด'&&w.dueAt&&Date.now()>Date.parse(w.dueAt);const flex=['submission','worksheet'].includes(w.type),allowText=flex||w.type==='text',allowLink=flex||w.type==='link',allowFiles=flex||['file','image','pdf'].includes(w.type),accept=w.type==='image'?'image/jpeg,image/png,image/webp,.heic,.heif':w.type==='pdf'?'.pdf':'image/*,.heic,.heif,.pdf,.docx,.xlsx,.pptx,.txt',typeLabel={manual:'ครูกรอกคะแนน • ไม่ต้องส่งงาน',exam:'ทำข้อสอบออนไลน์',file:'แนบไฟล์เท่านั้น',image:'แนบรูปภาพเท่านั้น',pdf:'แนบ PDF เท่านั้น',text:'พิมพ์คำตอบ',link:'ส่งลิงก์'}[w.type]||'ส่งข้อความ ลิงก์ หรือไฟล์';let content='';
 if(w.type==='manual')content='<p>งานนี้ครูประเมินและกรอกคะแนนให้ นักเรียนไม่ต้องส่งงานผ่านเว็บ</p>';
 else if(w.type==='exam')content=`<p><a href="./student-exam.html?exam=${encodeURIComponent(w.examId)}" target="_blank" rel="noopener">เปิดข้อสอบ →</a></p><small>ใช้รหัสนักเรียน ${esc(s.studentId)} ในหน้าสอบเพื่อเชื่อมคะแนน</small>`;
 else content=`${sub?.feedback?`<p class="feedback"><b>ความคิดเห็นครู:</b> ${esc(sub.feedback)}</p>`:''}${sub?`<p class="muted">ส่งล่าสุด ${date(sub.submittedAt)}</p>`:''}<details ${sub?'':'open'}><summary>${sub?'ดูงานที่ส่ง / ส่งใหม่':w.type==='image'?'เลือกรูปแล้วส่งงาน':'เริ่มส่งงานนี้'}</summary><form data-work="${esc(w.workId)}" novalidate>${allowText?`<label>คำตอบ<textarea name="answerText" rows="4" maxlength="20000">${esc(sub?.answerText||'')}</textarea></label>`:'<input type="hidden" name="answerText" value="">'}${allowLink?`<label>ลิงก์งาน<input name="answerUrl" type="text" placeholder="https://..." value="${esc(sub?.answerUrl||'')}"></label>`:'<input name="answerUrl" type="hidden" value="">'}${(allowFiles?(sub?.attachments||[]):[]).map(f=>`<label class="attachment"><input type="checkbox" name="keep" value="${esc(f.id)}" checked>เก็บไฟล์ ${esc(f.name)}</label>`).join('')}${allowFiles?`<label class="upload-zone"><span class="upload-icon">${w.type==='image'?'▧':'↑'}</span><b>${esc(typeLabel)}</b><small>${w.type==='image'?'ถ่ายรูปงาน หรือเลือกจากคลังรูป':'เลือกไฟล์งานจากเครื่อง'}</small><input type="file" name="files" accept="${accept}" multiple></label><small class="muted">สูงสุด 3 ไฟล์ ไฟล์ละ 3 MB รวม 6 MB • รูป JPG/PNG/WebP ขนาดใหญ่จะย่อให้อัตโนมัติ</small>`:'<input type="file" name="files" hidden>'}<div class="file-preview"></div>${sub?'<p class="muted">การส่งฉบับแก้ไขจะล้างคะแนนเดิมของงานนี้เพื่อให้ครูตรวจใหม่</p>':''}<button>${sub?'ส่งฉบับแก้ไข':w.type==='image'?'ส่งรูปงานให้ครู':'ส่งงานให้ครู'}</button><p class="send-status" role="status"></p></form></details>`;
 return `<section class="card work ${i.status==='ขาด'?'work-missing':''}" data-work-detail="${esc(w.workId)}" data-status="${esc(i.status)}"><div class="work-kicker">${cats[w.category]||'งาน'} · ${esc(typeLabel)}</div><h2>${esc(w.title)}</h2>${w.worksheetName?`<p>ใบงาน: ${esc(w.worksheetName)}</p>`:''}<div class="assignment-brief"><b>งานที่ต้องทำ</b><p class="description">${esc(w.description||'ทำงานตามชื่องานและคำชี้แจงที่ครูให้ในชั้นเรียน หากยังไม่มีโจทย์ให้สอบถามครูก่อนส่ง')}</p>${WorkAPI.safeUrl(w.referenceUrl)?`<a class="reference-button" href="${esc(WorkAPI.safeUrl(w.referenceUrl))}" target="_blank" rel="noopener noreferrer">ดูใบงาน / ตัวอย่างที่ครูแนบ ↗</a>`:''}</div><div class="row"><span class="tag ${i.status==='ขาด'?'miss':'ok'}">${i.status==='ขาด'?(overdue?'เลยกำหนด • ยังไม่ส่ง':'ยังไม่ส่ง'):esc(i.status)}${i.late?' • ส่งช้า':''}</span>${showScores?`<b>${i.score==null?'ยังไม่มีคะแนน':i.score} / ${w.maxScore}</b>`:`<span>คะแนนเต็ม ${w.maxScore}</span>`}</div><p class="muted">กำหนดส่ง ${date(w.dueAt)}</p>${content}</section>`;}).join('')||'<section class="card">ครูยังไม่ได้เผยแพร่งาน</section>'}</div>`;
 const latest=data.works.map((w,index)=>({w,index})).sort((a,b)=>(Date.parse(b.w.createdAt)||0)-(Date.parse(a.w.createdAt)||0)||b.index-a.index).slice(0,3).map(x=>x.w);
 $('latestWork').innerHTML='<h2>งานล่าสุด</h2>'+latest.map(w=>`<div class="latest-item"><div><b>${esc(w.title)}</b><small>สั่งเมื่อ ${date(w.createdAt)} · ${w.type==='manual'?'ครูกรอกคะแนน':w.accepting===false?'ปิดรับงาน':'เปิดรับงาน'}</small></div><button type="button" data-open-work="${esc(w.workId)}">ดูงาน</button></div>`).join('')+(latest.length?'':'<p>ยังไม่มีงาน</p>');
 $('studentTable').innerHTML=`<div class="student-table-wrap"><table class="student-table"><thead><tr><th>งาน / กำหนดส่ง</th><th>สถานะ</th><th>เปิดงาน</th></tr></thead><tbody>${data.works.map(w=>{const i=s.items.find(x=>x.workId===w.workId);return `<tr data-work-row="${esc(w.workId)}" data-status="${esc(i.status)}"><td><b title="${esc(w.title)}">${esc(w.title)}</b><small>${date(w.dueAt)}</small>${!['exam','manual'].includes(w.type)?`<small>${w.type==='manual'?'ครูกรอกคะแนน':w.accepting===false?'ปิดรับงาน':'เปิดรับงาน'}</small>`:''}</td><td class="${i.status==='ขาด'?'miss':'ok'}">${w.type==='manual'?(i.status==='ตรวจแล้ว'?'ประเมินแล้ว':'รอครูประเมิน'):i.status==='ขาด'?'ยังไม่ส่ง':i.late?'ส่งช้า':'ส่งแล้ว'}</td><td><button type="button" data-open-work="${esc(w.workId)}">ดู / ส่ง</button></td></tr>`}).join('')}</tbody></table></div>`;
 $('app').querySelectorAll('[data-open-work]').forEach(b=>b.onclick=()=>{activeWork=b.dataset.openWork;filter='all';$('filter').value='all';applyFilter();const el=Array.from($('app').querySelectorAll('.work')).find(x=>x.dataset.workDetail===activeWork);el.scrollIntoView({behavior:'smooth',block:'start'});});
 $('app').querySelectorAll('.work').forEach(el=>{const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent='กลับตารางงาน';b.onclick=()=>{activeWork='';applyFilter();$('studentTable').scrollIntoView({block:'start'})};el.prepend(b)});
 $('app').querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$('filter').value=filter;applyFilter();$('studentTable').scrollIntoView({behavior:'smooth',block:'start'})});
 $('filter').value=filter;$('filter').onchange=()=>{filter=$('filter').value;applyFilter()};applyFilter();
 $('refresh').onclick=()=>{if(!busy&&(!dirty||confirm('มีงานที่ยังไม่ได้ส่ง ต้องการโหลดข้อมูลใหม่หรือไม่?'))){drafts.clear();load()}};
 $('logout').onclick=()=>{if(busy)return;if(dirty&&!confirm('มีงานที่ยังไม่ได้ส่ง ต้องการออกหรือไม่?'))return;localStorage.removeItem(savedKey);data=null;dirty=false;drafts.clear();$('app').innerHTML='';$('login').classList.remove('hide');$('accessCode').value='';previewUrls.forEach(URL.revokeObjectURL);previewUrls=[];notice('กรอกรหัสของผู้ใช้ใหม่')};
 $('app').querySelectorAll('form[data-work]').forEach(f=>{const remember=()=>{dirty=true;drafts.set(f.dataset.work,{text:f.elements.answerText.value,url:f.elements.answerUrl.value,files:f.elements.files.files,keep:Array.from(f.querySelectorAll('[name=keep]:checked'),x=>x.value)})};const draft=drafts.get(f.dataset.work);if(draft){f.elements.answerText.value=draft.text;f.elements.answerUrl.value=draft.url;f.elements.files.files=draft.files;f.querySelectorAll('[name=keep]').forEach(x=>x.checked=draft.keep.includes(x.value));f.closest('details').open=true;}f.oninput=remember;f.elements.files.onchange=()=>{remember();const box=f.querySelector('.file-preview');box.innerHTML='';Array.from(f.elements.files.files).forEach(file=>{const span=document.createElement('span');span.textContent=file.name+' ('+(file.size/1024).toFixed(0)+' KB)';box.append(span);if(/^image\/(jpeg|png|webp)$/.test(file.type)){const img=document.createElement('img');img.alt=file.name;img.src=URL.createObjectURL(file);previewUrls.push(img.src);box.append(img)}})};
 if(draft)f.elements.files.onchange();
 const closed=data.works.find(w=>w.workId===f.dataset.work)?.accepting===false;if(closed){Array.from(f.elements).forEach(el=>el.disabled=true);f.querySelector('.send-status').textContent='ปิดรับงานแล้ว • ดูงานเดิมได้ แต่ส่งหรือแก้ไขไม่ได้';}
 f.onsubmit=async e=>{e.preventDefault();if(busy)return;if(data.works.find(w=>w.workId===f.dataset.work)?.accepting===false){notice('ครูปิดรับงานนี้แล้ว',true);return}const sub=subs[f.dataset.work];if(sub&&!confirm('ส่งฉบับแก้ไขและให้ครูตรวจคะแนนใหม่หรือไม่?'))return;busy=true;const b=f.querySelector('button'),msg=f.querySelector('.send-status'),label=b.textContent;b.textContent='กำลังส่ง…';$('app').querySelectorAll('button').forEach(x=>x.disabled=true);msg.textContent='กำลังส่งและรอการยืนยัน กรุณาอย่าปิดหน้านี้';let success=false;
 try{msg.textContent='กำลังเตรียมไฟล์…';const upload=await files(f.elements.files.files);const keep=Array.from(f.querySelectorAll('[name="keep"]:checked'),x=>x.value);if(upload.length+keep.length>3)throw Error('ไฟล์เดิมและไฟล์ใหม่รวมได้ไม่เกิน 3 ไฟล์');const w=data.works.find(x=>x.workId===f.dataset.work);if(['file','image','pdf'].includes(w.type)&&!upload.length&&!keep.length)throw Error('กรุณาแนบไฟล์ก่อนส่งงาน');const re=w.type==='image'?/\.(jpe?g|png|webp|heic|heif)$/i:w.type==='pdf'?/\.pdf$/i:null;if(re&&upload.some(x=>!re.test(x.name)))throw Error('ชนิดไฟล์ไม่ตรงกับที่ครูกำหนด');const answerUrl=normalizeUrl(f.elements.answerUrl.value);if(answerUrl&&!WorkAPI.safeUrl(answerUrl))throw Error('ลิงก์ไม่ถูกต้อง แก้ลิงก์หรือลบช่องลิงก์แล้วส่งใหม่');if(!f.elements.answerText.value.trim()&&!answerUrl&&!upload.length&&!keep.length)throw Error('เลือกไฟล์หรือพิมพ์คำตอบก่อนกดส่ง');await mutate({action:'submitWork',...credentials(),workId:f.dataset.work,revision:sub?.revision||0,answerText:f.elements.answerText.value,answerUrl,files:upload,keepFileIds:keep},text=>{msg.textContent=text});success=true;drafts.delete(f.dataset.work);dirty=drafts.size>0;msg.textContent='ส่งงานสำเร็จ เซิร์ฟเวอร์ยืนยันแล้ว';notice('ส่งงานสำเร็จ');}
 catch(e){msg.textContent=e.message;notice(e.message,true);msg.classList.add('miss');msg.scrollIntoView({block:'center',behavior:'smooth'})}finally{b.textContent=label;busy=false;$('app').querySelectorAll('button').forEach(x=>x.disabled=!!(x.closest('form[data-work]')&&data.works.find(w=>w.workId===x.closest('form[data-work]').dataset.work)?.accepting===false))}if(success){await load();notice('✓ ส่งงานสำเร็จแล้ว ครูได้รับงานแล้ว')}};});
}
function applyFilter(){
 const matches=s=>filter==='all'||(filter==='missing'&&s==='ขาด')||(filter==='pending'&&['ส่งแล้ว','ส่งช้า','รอตรวจข้อเขียน'].includes(s))||(filter==='graded'&&s==='ตรวจแล้ว');
 $('app').querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===filter)));
 $('app').querySelectorAll('[data-work-row]').forEach(el=>el.hidden=!matches(el.dataset.status));
 $('app').querySelectorAll('.work').forEach(el=>el.hidden=el.dataset.workDetail!==activeWork||!matches(el.dataset.status));
 let empty=$('emptyFilter');if(!empty){empty=document.createElement('p');empty.id='emptyFilter';empty.className='card empty-state';$('studentTable').append(empty)}empty.textContent=filter==='missing'?'ส่งครบแล้ว ไม่มีงานค้าง ✓':'ไม่มีงานในรายการนี้';empty.hidden=Array.from($('app').querySelectorAll('[data-work-row]')).some(e=>!e.hidden);
}
$('loginForm').onsubmit=e=>{e.preventDefault();load()};
async function init(){
 if(!C){notice('ลิงก์ไม่มีห้องเรียน กรุณาเปิดลิงก์จากครู',true);return}
 try{
 const fragment=new URLSearchParams(location.hash.slice(1));let saved=null;try{saved=JSON.parse(localStorage.getItem(savedKey)||'null')}catch{}
 if(fragment.get('student')&&fragment.get('token')){$('sid').value=fragment.get('student');$('accessCode').value=fragment.get('token');history.replaceState(null,'',location.pathname+location.search);await load();return;}
 if(saved?.studentId){$('sid').value=saved.studentId;$('accessCode').value=saved.accessCode||'';await load();return;}
 const info=await get('getWorkEntry',{classId:C});if(info.apiVersion!=='V67')throw Error('ครูต้อง Deploy Apps Script V67 ก่อน');entryMode=info.entryMode;$('login').querySelector('h1').textContent=info.className+' • '+info.subject;
 if(entryMode==='personal')notice('เปิดลิงก์ส่วนตัวที่ครูแจกเพื่อดูงานได้ทันที ไม่ต้องพิมพ์รหัสลับ',true);
 }catch(e){notice(e.message,true)}
}
init();
window.addEventListener('beforeunload',e=>{if(dirty||busy){e.preventDefault();e.returnValue=''}});
})();
